---

- name: Installing kubectl
  ansible.builtin.include_tasks:
    file: kubectl.yml

- name: Installing flux
  ansible.builtin.include_tasks:
    file: flux.yml

- name: Installing sops
  ansible.builtin.include_tasks:
    file: sops.yml

- name: Installing age and age-keygen
  ansible.builtin.include_tasks:
    file: age.yml

- name: Installing talosctl and tools
  ansible.builtin.include_tasks:
    file: talos.yml
