---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name homepage
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: homepage
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: true
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    serviceAccount:
      homepage: {}
    rbac:
      roles:
        homepage-discovery:
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["namespaces", "pods", "nodes", "services"]
              verbs: ["get", "list"]
            - apiGroups: ["extensions", "networking.k8s.io"]
              resources: ["ingresses"]
              verbs: ["get", "list"]
            - apiGroups: ["metrics.k8s.io"]
              resources: ["nodes", "pods"]
              verbs: ["get", "list"]
      bindings:
        homepage-discovery:
          type: ClusterRoleBinding
          roleRef:
            identifier: homepage-discovery
          subjects:
            - identifier: homepage
              serviceAccount: homepage
    configMaps:
      config:
        enabled: true
        data:
          bookmarks.yaml: |
            ---
          docker.yaml: |
            ---
          kubernetes.yaml: |
            mode: cluster
          services.yaml: |
            ---
            - Media:
                - Sonarr:
                    icon: sonarr.png
                    href: "https://sonarr.${SECRET_DEFAULT_DOMAIN}"
                    description: TV Shows
                    namespace: media
                    app: media-sonarr
                    widget:
                      type: sonarr
                      url: "https://sonarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_SONARR_API_KEY}"
                - Radarr:
                    icon: radarr.png
                    href: "https://radarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Movies
                    namespace: media
                    app: media-radarr
                    widget:
                      type: radarr
                      url: "https://radarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_RADARR_API_KEY}"
                - Lidarr:
                    icon: lidarr.png
                    href: "https://lidarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Music
                    namespace: media
                    app: media-lidarr
                    widget:
                      type: lidarr
                      url: "https://lidarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_LIDARR_API_KEY}"
                - Bazarr:
                    icon: bazarr.png
                    href: "https://bazarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Subtitles
                    namespace: media
                    app: media-bazarr
                    widget:
                      type: bazarr
                      url: "https://bazarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_BAZARR_API_KEY}"
                - Prowlarr:
                    icon: prowlarr.png
                    href: "https://prowlarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Indexers
                    namespace: media
                    app: media-prowlarr
                    widget:
                      type: prowlarr
                      url: "https://prowlarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_PROWLARR_API_KEY}"
                - Readarr:
                    icon: readarr.png
                    href: "https://readarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Ebooks
                    namespace: media
                    app: media-readarr
                    widget:
                      type: readarr
                      url: "https://readarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_READARR_API_KEY}"
                - Speakarr:
                    icon: readarr.png
                    href: "https://speakarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Audiobooks
                    namespace: media
                    app: media-speakarr
                    widget:
                      type: readarr
                      url: "https://speakarr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_SPEAKARR_API_KEY}"
                - Tdarr:
                    icon: tdarr.png
                    href: "https://tdarr.${SECRET_DEFAULT_DOMAIN}"
                    description: Transcode
                    namespace: media
                    app: media-tdarr
                    widget:
                      type: tdarr
                      url: "https://tdarr.${SECRET_DEFAULT_DOMAIN}"
            - Streaming:
                - Jellyfin:
                    icon: jellyfin.png
                    href: "https://jellyfin.${SECRET_DEFAULT_DOMAIN}"
                    description: Media Server
                    namespace: media
                    app: media-jellyfin
                    widget:
                      type: jellyfin
                      url: "https://jellyfin.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_JELLYFIN_TOKEN}"
                      enableNowPlaying: true
                - Plex:
                    icon: plex.png
                    href: "https://plex.${SECRET_DEFAULT_DOMAIN}"
                    description: Media Server
                    namespace: media
                    app: media-plex
                    widget:
                      type: plex
                      url: "https://plex.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_PLEX_TOKEN}"
                - Tautulli:
                    icon: tautulli.png
                    href: "https://tautulli.${SECRET_DEFAULT_DOMAIN}"
                    description: Plex Analytics
                    namespace: media
                    app: media-tautulli
                - Seerr:
                    icon: overseerr.png
                    href: "https://seerr.${SECRET_DEFAULT_DOMAIN}"
                    description: Requests
                    namespace: media
                    app: media-seerr
                    widget:
                      type: overseerr
                      url: "https://seerr.${SECRET_DEFAULT_DOMAIN}"
                      key: "${SECRET_SEERR_API_KEY}"
          settings.yaml: |
            title: Dashboard
            favicon: https://gethomepage.dev/favicon.ico
            background:
              image: ""
            theme: dark
            color: slate
            headerStyle: clean
            layout:
              Media:
                style: row
                columns: 4
              Streaming:
                style: row
                columns: 4
            hideVersion: true
          custom.css: ""
          custom.js: ""
          proxmox.yaml: |
            ---
          widgets.yaml: |
            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "cluster"
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
    controllers:
      homepage:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          homepage:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.12.1@sha256:9627769818fbfb14147d3e633e57cef9c27c0c5f07585f5a1d6c3d3425b3b33c
            env:
              TZ: "${TIMEZONE}"
              HOMEPAGE_ALLOWED_HOSTS: "homepage.${SECRET_DEFAULT_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      homepage:
        controller: *name
        ports:
          http:
            port: &port 3000
    ingress:
      homepage:
        enabled: true
        annotations:
          haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
          haproxy.org/ssl-redirect-port: "443"
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "DENY"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        hosts:
          - host: &host "homepage.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: homepage
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: configMap
        name: homepage
        globalMounts:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
          - path: /app/config/docker.yaml
            subPath: docker.yaml
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
          - path: /app/config/services.yaml
            subPath: services.yaml
          - path: /app/config/settings.yaml
            subPath: settings.yaml
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
          - path: /app/config/custom.css
            subPath: custom.css
          - path: /app/config/custom.js
            subPath: custom.js
          - path: /app/config/proxmox.yaml
            subPath: proxmox.yaml
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
    rawResources:
      cilium-kube-api:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        spec:
          spec:
            endpointSelector:
              matchLabels:
                app.kubernetes.io/controller: *name
            egress:
              - toEntities:
                  - kube-apiserver
                toPorts:
                  - ports:
                      - port: "6443"
                        protocol: TCP
    networkpolicies:
      homepage:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: 443
                  protocol: TCP
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: *port
