apiVersion: v1
kind: Secret
metadata:
    name: awx-basic-auth
    namespace: awx
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uFRk,iv:JXk4mXFcElB+Ah3K4eY4x8S8RZCRwqjjuabx1onmhEs=,tag:D+q6nCsff2mdjuXAUSsajg==,type:str]
    password: ENC[AES256_GCM,data:rNUn3195JnjPycVBT1RbtkLajX4cYvqlcghQ5Pe+bDneDBR633wssNe5yYsNS2wB1agrojj12IYmeM09VEQ+CQ==,iv:rgEmKgN9Tm2XizA7b3lM2QJAITEdHMHh7VYs5N85pbI=,tag:fvHX7GgwUQTELMVrRl1EOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eVR5Vm52YWRYZUprUy8v
            ZVZldzBzclJlNDQxWXhhejZDamVYWDhPQVdZCmVPdXZFcEVZelh4bmF3bWZYcS9k
            dnY0NCtDTUtPV0t3ZXhwbUFFczFxUlUKLS0tIG5YTFVveWVpb25xaXd5dGRXSWxy
            NzZWTHhkZEtNRTk4Kzg0UDBUL0pJL1EKRUevTw2RJRWq3z8mXAMe7GBrgKvdlf6R
            WPd2EBkFCZH4+s12eqnSbTVuHaG3smge53y4Pd46AcBJlmkBm19Qkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:tYTRhlnnmHA6g2esVCGmv8GkMeteYMQhVhnhx9n/nVBVXtbfKWRbBAFHhpSPWy8ma8YB1C3gor+LWeRTZ5wLOWDP+2Shq5OPUNqHF8JutM67oHW4518JH7guLq5Ccd4Zd91lWyuetQfC+ut5l7DURHelzkiqlQ5n2K0Mr+Cqa+c=,iv:KdGA7cXPrhCt0ev60fcWjpu+ZuqnoVtSHrnWMDAvgNU=,tag:FZsQC77hZ0+d0JacBE0EpQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: awx-postgres-v18
    namespace: awx
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:L6JsxkWTKGMVbo3hCcyFdxZwWnXu/Xw98uA=,iv:qO1Eu8FQ9jddtULIbqiEb/EMS900HGZtDVUPZ3P+ckU=,tag:JBvinItEzK7IlvcFrV+x9A==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:RrddxQ3VheoRBe1RZOa/Zxt32H0J/CJ1zGarDSyowjNTr8/JSfyuZTkYNtRMDD2y63w34+cnfgwI2whyK+kpgg==,iv:GDhpmUFV5XXES/MBDz4WQUt5O++iIeDWHTcvcsn7Ck0=,tag:506N7x24/329XbDp02O40g==,type:str]
    region: ENC[AES256_GCM,data:JQ4/m/ba,iv:HYPDq76/eIUXWWBEeAXW/odaFAD6e6F0X2TPLMxW0wg=,tag:2zSM+GMLzsEnC4DafIxHNw==,type:str]
    password: ENC[AES256_GCM,data:MCTIg8aKPqo3lnCDyL8UXAjcPyZeURffIa5Mg3AIxzf0jRwZzdsjOYRFkjumi65CpdLPqBsDOJQQrGJmAOnI1g==,iv:YFdTYEv+32ZgSyssFTPJVhmApCKJPuGwBRES4v9Bzz0=,tag:JXwStgTiTKSx1nl9ku7MKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eVR5Vm52YWRYZUprUy8v
            ZVZldzBzclJlNDQxWXhhejZDamVYWDhPQVdZCmVPdXZFcEVZelh4bmF3bWZYcS9k
            dnY0NCtDTUtPV0t3ZXhwbUFFczFxUlUKLS0tIG5YTFVveWVpb25xaXd5dGRXSWxy
            NzZWTHhkZEtNRTk4Kzg0UDBUL0pJL1EKRUevTw2RJRWq3z8mXAMe7GBrgKvdlf6R
            WPd2EBkFCZH4+s12eqnSbTVuHaG3smge53y4Pd46AcBJlmkBm19Qkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:tYTRhlnnmHA6g2esVCGmv8GkMeteYMQhVhnhx9n/nVBVXtbfKWRbBAFHhpSPWy8ma8YB1C3gor+LWeRTZ5wLOWDP+2Shq5OPUNqHF8JutM67oHW4518JH7guLq5Ccd4Zd91lWyuetQfC+ut5l7DURHelzkiqlQ5n2K0Mr+Cqa+c=,iv:KdGA7cXPrhCt0ev60fcWjpu+ZuqnoVtSHrnWMDAvgNU=,tag:FZsQC77hZ0+d0JacBE0EpQ==,type:str]
    version: 3.13.3
