---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-controller
  namespace: flux-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: haproxy-ingress
      version: 0.16.1
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
      interval: 30m
  targetNamespace: haproxy-controller
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: haproxy-controller
    controller:
      kind: DaemonSet
      ingressClass: haproxy
      ingressClassResource:
        enabled: true
        default: true
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.1.41
        externalTrafficPolicy: Local
      stats:
        enabled: "${MONITORING_PROMETHEUS}"
      metrics:
        enabled: "${MONITORING_PROMETHEUS}"
      serviceMonitor:
        enabled: "${MONITORING_PROMETHEUS}"
