apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-basic-auth
    namespace: pocket-id
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:DJ8KsGDOlcU=,iv:FcUMeLYTtAuPJjC6KpAvBR68I3MjpqBRkhsC34K3qpI=,tag:IJnXkjaymkOoc9SiofoCcw==,type:str]
    password: ENC[AES256_GCM,data:0v+rNPL+0pktlYI+TB59OkBDnPakr9AKams0KjRlIolKJ8uCXloscy/Pawa6MZ+z/uGoaxJ9rjMwbuUOgM50cQ==,iv:YGHfoANFcrQAnPVcntRNHLTvVrO+9u1Wfb+I4ZHCd0I=,tag:NhMwnWFuOnBgU3ChiC2ZWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVRKQXk0SlkwdWJwVGFs
            a25QVTRSc1B3SkhqQTBSVHc2NDVtVFNsMUdNClFpYndJaDd5VVl3Vkd0NDFXOW1w
            b2FsZi9ZeDg2emNpcW5LVkRrNHhlSmMKLS0tIFpqRzgwd09NMTNGajFqeVBhcEJE
            ZFZGeE1udVpuVFV5eTV1dmVqdGtzaGcKNFxOGowl7tcz0C+++oERZeA2D9g5OPuq
            9OfCqINAwNIYnADFxCI1UBaEx1oJhWjw2I9C/nSp7QZ9iFFLiR4QZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T16:26:26Z"
    mac: ENC[AES256_GCM,data:wO5ca0bvSM35GE4OzELojQDeU6G3a1/9a/MTT1Gq3LUV+KFIzNRfbPdEg63ifj+/e0eAl0PTwU8K6hMiM8J4THrkhTcHHtXENylkRBqVsER/Pqx7ohxSbXxlJ2e+KVovxj1aHJ0kdNmFQX23qL4JgLCy3fTA3Jdofg1CrMPuVnY=,iv:tq7jESkD60ZJTmIwYKvh6M+liqrYxoFnolKqFSqdYHU=,tag:amNbGhkWgR8PZ56Y474i7w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-postgres-v18
    namespace: pocket-id
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:hIJ8j6XCUpklSSnpB8Py30aDat4ymbBFHyI=,iv:ov1vGBeAHTRu+VaapHa15px3NOmaAaprOLsfJsHg8+4=,tag:RHlwI8tWJOaIQMJmEwuXLA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:7oRUwe0zcnPu7qDRJc6MxgeLboW0BKTVWGTGm53YwKetgbwtQ534zQrHDiBtiI68JMvoPoSLIOhJ72iH6yjRtQ==,iv:GiOYjjnpiPMl/z1U4RKkg6Mc4CWPOAQb+JQKYBcqgpQ=,tag:7dpYVKbzvVEGXsWRIc/8Kw==,type:str]
    region: ENC[AES256_GCM,data:iavpv+va,iv:xYedC2XgG9yl6NeS64RjZD2eEB81I9Tu2sbIoXPsIhQ=,tag:w4n8tCVxH18mEOv1Jigxhg==,type:str]
    password: ENC[AES256_GCM,data:wng5bWeKXvzBKusPplCqcvJMw0lyTRAd5dgjyt1tkgDoWwlCTzwkTn9VxrBB9uq1yHg8H149ewi2a4Za9gn2mA==,iv:7MC1XNFdBTwx5i0HKIe/uV1DE9DesH23a9qmCV2/InE=,tag:ECVMuOqvQwP+Pn+cWsvZqA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:nm0mLEZpnvO2/bgX2jI03YaX6pnu00QxgfkjZG0Y91j3Ib8SsgrOWqEimjHsHyiEDFzshQ17I80psH2AaKjt78E46WjAJr65aEtIV4XeMqCfZg3cdbSuLbBBshbPK7wKSFashjWG+l5fRlBREvQ4SGmD8oilx6RvcpEcFmm0lCf4xxF1JoEMyGkkv+BGCke8SwA3UocnuAIsN6Sf7Y7FJA==,iv:4kFNppgjNCyHLR6FtbyuexnppKdUr89z1e8TgfN/Hl4=,tag:sWpZZVXwtQLYk6rWHg2CAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVRKQXk0SlkwdWJwVGFs
            a25QVTRSc1B3SkhqQTBSVHc2NDVtVFNsMUdNClFpYndJaDd5VVl3Vkd0NDFXOW1w
            b2FsZi9ZeDg2emNpcW5LVkRrNHhlSmMKLS0tIFpqRzgwd09NMTNGajFqeVBhcEJE
            ZFZGeE1udVpuVFV5eTV1dmVqdGtzaGcKNFxOGowl7tcz0C+++oERZeA2D9g5OPuq
            9OfCqINAwNIYnADFxCI1UBaEx1oJhWjw2I9C/nSp7QZ9iFFLiR4QZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T16:26:26Z"
    mac: ENC[AES256_GCM,data:wO5ca0bvSM35GE4OzELojQDeU6G3a1/9a/MTT1Gq3LUV+KFIzNRfbPdEg63ifj+/e0eAl0PTwU8K6hMiM8J4THrkhTcHHtXENylkRBqVsER/Pqx7ohxSbXxlJ2e+KVovxj1aHJ0kdNmFQX23qL4JgLCy3fTA3Jdofg1CrMPuVnY=,iv:tq7jESkD60ZJTmIwYKvh6M+liqrYxoFnolKqFSqdYHU=,tag:amNbGhkWgR8PZ56Y474i7w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: pocket-id
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:QW9vGU/trUdkc7GsJ/At03ONZpT5jW7/9R1fcjNoVsuQc8wL/p+y/YGK9cs=,iv:gEriLz9VLrE85M64EOjmicVtn5oqPYeT5Ule/Is2d74=,tag:3my1qz1BLsMn3OKrfTRgPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVRKQXk0SlkwdWJwVGFs
            a25QVTRSc1B3SkhqQTBSVHc2NDVtVFNsMUdNClFpYndJaDd5VVl3Vkd0NDFXOW1w
            b2FsZi9ZeDg2emNpcW5LVkRrNHhlSmMKLS0tIFpqRzgwd09NMTNGajFqeVBhcEJE
            ZFZGeE1udVpuVFV5eTV1dmVqdGtzaGcKNFxOGowl7tcz0C+++oERZeA2D9g5OPuq
            9OfCqINAwNIYnADFxCI1UBaEx1oJhWjw2I9C/nSp7QZ9iFFLiR4QZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T16:26:26Z"
    mac: ENC[AES256_GCM,data:wO5ca0bvSM35GE4OzELojQDeU6G3a1/9a/MTT1Gq3LUV+KFIzNRfbPdEg63ifj+/e0eAl0PTwU8K6hMiM8J4THrkhTcHHtXENylkRBqVsER/Pqx7ohxSbXxlJ2e+KVovxj1aHJ0kdNmFQX23qL4JgLCy3fTA3Jdofg1CrMPuVnY=,iv:tq7jESkD60ZJTmIwYKvh6M+liqrYxoFnolKqFSqdYHU=,tag:amNbGhkWgR8PZ56Y474i7w==,type:str]
    version: 3.13.3
