apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-basic-auth
    namespace: pocket-id
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tVb0Ci4Raek=,iv:UPSjRRtsKvkLmD3QuMZGhBlxVNVcjL+5AUEn43V/pA0=,tag:Pa2yxG32ykNf5CbDrdHrGA==,type:str]
    password: ENC[AES256_GCM,data:+F9itWvrOjZL/4PWl2e/O+R2p663d8I581oLw9w+SJRngi9rT5jxtObOlf9lfvJuHMfH8xC3ntVmbH5gXwi0cg==,iv:syCKl3bzsg63f1VYPJyjpyVYvGiuidCwvyEST6XcRvw=,tag:ld0NGeYFdqpDcKskLhziSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxKzdBNU4rRGIxaU1KdnIr
            TzdEb1lpUlFWYjNCQVFUWjNjYVhucWtOZTNBCkIwU2JaOG1OZUhJM2dWcC8raVNy
            SW9VeFdkcDRlczVINFFUaDBHT1B3OTgKLS0tIHBWbERTY0cyNXVoMWRlU0tMUmtn
            c2NENlEvQXRvUEhISXdhWHFyUlo4SDAKnda/sNPwqH1N8HpxVm8dgr/y3CMMukXW
            knaLGZDeVpRW7PRjtFfKZTVGj1m7NRtNjosnZXxK9zk9ELp8s38lKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:WbxcLS0A1WdLgBquxotmI/R4HxrWSmeHZawiOYfnQoYM3JLQ4ltLeOckhCpv5Hc5/KinNMrciHZTF54rv/z4ETopEp21sojtZGuIZHwc+dLEjJt3P9iIe0mzOHkKBWCqALJBsUEnvKcZirWIvS+SkUonpeNA+tk6XWov8Q9ePns=,iv:9/HmvztvnflKy28Fas7Fn474q2EIJpQyKG/rTs/CPoY=,tag:/1R374kMwe/kcTZzWCyRmg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-postgres-v18
    namespace: pocket-id
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:boSFqUBdBwSIi5RXRwLba+MftCWzd+jYz1E=,iv:ySOtwxngcKyOnlwPGkgTdBBzBtgYRO7IeJwaZJ7ztA4=,tag:g7qdOQOk/M566ziZsx1I7w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:hXbO5vNK/PTl91KERVjNWmPIEQqQsuAg25aUL5oUHycuqggxtSWe1VxN88bN22s8DxgsTZ9hQANN6yaKXTFoCw==,iv:vXDVdi18VLo/4ylgKj3l/rcP1e+6pKEPzKg/Dbbw9xA=,tag:H2BghmNr/FWYXRCbeKKxnA==,type:str]
    region: ENC[AES256_GCM,data:1PP8LKc0,iv:GL9acZMcs2+JJxeiS6ZA9XIyAYpE6XlB0iVcU50BJow=,tag:0RCdn1rTd+MC3TYX4MTwUQ==,type:str]
    password: ENC[AES256_GCM,data:6e7uLU8uJFGEAYHOJC+YAc4s/t/T46StVZFqyJQT2LKa6PMBOA7CsSXeCyuAxrb+48HeTkN52JtHgCzRS89XbQ==,iv:JcZjdSd62MFaP3zCIAcKpHdzevDbMM/L+Whjw7mxDYI=,tag:x8jawfmEYOfXNmrx9okw8g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dZSIKjhVXGkyl0lGmbXXOgabzgVjSlXr95mELsKRDq9JefUaU2StA9RPhWxb6GjAI5BlTKb2YOsPqhfRDn45sE+fGUzZsThx3UdggMdthRNo4DaR/5AaqvdW7gLIPDYUym078eWqi+ZLAaG9n1DF3gyPuyOHYORBHaFyPCyUl+UCU6ZjqBo0QnccRkJ6GSTdGXWa7B+NIO/hirrXAE2XhQ==,iv:baOXPJxDFA751l32njjVMQx3HfxX7mNmiw1jZX+7Qbk=,tag:XtYm4PJThs4xtLUtazhJKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxKzdBNU4rRGIxaU1KdnIr
            TzdEb1lpUlFWYjNCQVFUWjNjYVhucWtOZTNBCkIwU2JaOG1OZUhJM2dWcC8raVNy
            SW9VeFdkcDRlczVINFFUaDBHT1B3OTgKLS0tIHBWbERTY0cyNXVoMWRlU0tMUmtn
            c2NENlEvQXRvUEhISXdhWHFyUlo4SDAKnda/sNPwqH1N8HpxVm8dgr/y3CMMukXW
            knaLGZDeVpRW7PRjtFfKZTVGj1m7NRtNjosnZXxK9zk9ELp8s38lKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:WbxcLS0A1WdLgBquxotmI/R4HxrWSmeHZawiOYfnQoYM3JLQ4ltLeOckhCpv5Hc5/KinNMrciHZTF54rv/z4ETopEp21sojtZGuIZHwc+dLEjJt3P9iIe0mzOHkKBWCqALJBsUEnvKcZirWIvS+SkUonpeNA+tk6XWov8Q9ePns=,iv:9/HmvztvnflKy28Fas7Fn474q2EIJpQyKG/rTs/CPoY=,tag:/1R374kMwe/kcTZzWCyRmg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: pocket-id
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:6ZNCWXpH7FhE3+pxObfjhDa5FZ6/bU3gA9/2USZ9MYb7EVnaM9i7LxCNnWU=,iv:nDYXHGs0tRd+26Xc3705b7eAm6bSAfYYiXsNh37453A=,tag:FVolVakkhjL6vio+7/fm6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxKzdBNU4rRGIxaU1KdnIr
            TzdEb1lpUlFWYjNCQVFUWjNjYVhucWtOZTNBCkIwU2JaOG1OZUhJM2dWcC8raVNy
            SW9VeFdkcDRlczVINFFUaDBHT1B3OTgKLS0tIHBWbERTY0cyNXVoMWRlU0tMUmtn
            c2NENlEvQXRvUEhISXdhWHFyUlo4SDAKnda/sNPwqH1N8HpxVm8dgr/y3CMMukXW
            knaLGZDeVpRW7PRjtFfKZTVGj1m7NRtNjosnZXxK9zk9ELp8s38lKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:WbxcLS0A1WdLgBquxotmI/R4HxrWSmeHZawiOYfnQoYM3JLQ4ltLeOckhCpv5Hc5/KinNMrciHZTF54rv/z4ETopEp21sojtZGuIZHwc+dLEjJt3P9iIe0mzOHkKBWCqALJBsUEnvKcZirWIvS+SkUonpeNA+tk6XWov8Q9ePns=,iv:9/HmvztvnflKy28Fas7Fn474q2EIJpQyKG/rTs/CPoY=,tag:/1R374kMwe/kcTZzWCyRmg==,type:str]
    version: 3.13.3
