---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crosspoint-sync
  namespace: crosspoint-sync
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
