apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ha-mcp-config
    namespace: ha-mcp
stringData:
    HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:/XgLNN9fb8zXDJTxCmSPBPv2adgGN3Md13X/B40Latef/Etblitp62av7tpgk0vmANpGiAprpXrOaDydslKPQuEm2H5NjIcKGFyPMZjK3u57kiTOISmCXv3y1NVDfDFDoNEc4fVklenRkyfYIS76YiMYcf0IjWevTHA08ylXYX/NurAocoefaD0okrgsZn5B0ncTFwAUcUOL0toD/Nz/OL/QPnQmHw5lVUUa7tzhRYco2X79F9sS,iv:qU9KQT/VMBXxnYObh9DEx0qctU7xr/KYJKQrmSgZuKQ=,tag:sCgOZlrshmFCRv9c0TNZLg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSE1CblpLU0xjT2Y0U2w4
            WlcwdmNMTldxdDRjcXFPSzAwaVh3WFNPaW5zClNFUHlUYW94R3lVN3NjbDFWbWFC
            eVFHQU0zTENuRG1taGhtZU5KT3JSTkUKLS0tIFNwaFBZQXVmNTlKRkwwM2RsRUJT
            UmhqaUU5MG9wOFFhVmx2bUlwK0NDSWsK9RFxInb5YTL17/Eg3EUb2STvG1dC0yIo
            Tv94Fv6pQD2XZrk1n+wHdTKBGMfhi/gn+TEupX1lsIPNJ00UN2bjpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T14:25:08Z"
    mac: ENC[AES256_GCM,data:0h/SisjueohqvHma9KZj/Pv8DixOxwzBKsDheM/Pyqs3kGc7DmPJTePNaMfTD///ve1TiC92VX7Y0NJGEQC01UPsjV1S0RWPoQAoNRRkNDD05PGUAlJGFHcbcSrxJSCo54roMidSlzHevTxxOSgPtD3TeBHZdasQcvQMwiyvx+U=,iv:hUzvvkgeP4A3r9CkJNy6148jRXOx6D4KiMdDVB6Ev7o=,tag:wW8KVv1nWQwvHiVFhOry3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
