apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-basic-auth
    namespace: vaultwarden
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:t20NB41YgVo3xhI=,iv:fjgZ5/z9hJZ4k5+v2aVltJUNKH2V10krurc0nL19A50=,tag:IewEmT2Nhycz7XhTmgxjNQ==,type:str]
    password: ENC[AES256_GCM,data:ZJDflhlIoVK1YFZXeHgfKyTBAWb7HCy6SA1WIAAsowthcEslEAdbN7H0YVPNmNR0u3mjlBPSeP35EeSODMslyg==,iv:Ta/mIC/9GfTnOaqsTk82mbz3VM7FeQBQEMvj8zNdWZg=,tag:xmP+obwvGafkcuY4MYRF5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUDRDYXFadFRyNVg1SFI4
            a2NybGQyYWkwWVFzUjlrYjZxVmpsRnMveWlBCnY4OGtQN2txTUVHQmdnVTVVNjhC
            Y241OERlcnRvSVdwVE1lc2FNQlFzYmsKLS0tIFB6S3hqV2lQS2NtY1R6cGJIVTky
            Y1ArN3IyV0R6TW1ud1BDeVoySVpFUDAKw5TW8UhpFIPEh7hufVBQgqC2fS/dnnD4
            xw2B5P01+pv8M8PdsLPaJvX9KZx0hBKk5Uc5X5lr0TlQc4G2wgo8Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:SBZwI8BKU0UTaN7gqeET9dgamPPduPzaVZqfOFHjBAx4HI7D57Rl0errS0FDfYlwT7XOLISDM2lKAsDMShN3SOTy01068HYxrUYXmlDYbcBQ6XjNRZPuXItXy5qLGiHsEtqp+lOU6ozNf06GVEo9u4g/5TYI1pDAwJkAyGLpTOc=,iv:WjEwbMjr1c3MYOLswW0nXct6BmMGxO1Avs/iR0oAOd8=,tag:E4Brf4q0/zEPjoFNdtfg+g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-postgres-v18
    namespace: vaultwarden
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:cPchoYmL6gIXCVmyfEtBOFawZlvGzcwKFhI=,iv:La/p2t0kxA4LYmO3te4yNAvFhLdln2eT1Z5KNk2dD3w=,tag:BrKUJ3xX8pig74pLlMlmuA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:IuaAMwaIEVJepDxSUtg6aZtrMotfY0cerZzaYY5iK+StUOLkCwgqZoCicr0tbzkimrY7C0GxEHFClNTxKpgoLQ==,iv:+vCd2jzRmDYG2Nr5F4Hx3tBj6975LD8d/UUd+OPGaWQ=,tag:x+Vni9AwohbWXJY5Dn1/sA==,type:str]
    region: ENC[AES256_GCM,data:RHqSw/jd,iv:iZs9tWlmnHx4hqJk40V2nT77gvfyNAraE62IFaRXDI0=,tag:va74mj1YC/sJ1/lTmI/ZWQ==,type:str]
    password: ENC[AES256_GCM,data:CDXscgf3FSZgUIi2coCy8BipV2ZBp8Dd+Oq9F0Ar6HIw4bK6qS+dnA4ujawb5iogL5WoUmgrIDNsm1BU8JOiNA==,iv:Eyp6whHNA4VcE58yIip+MpVE9J+wzIcOGOBE1Rc7r7E=,tag:Bo7jNzJ+2X5p0Cmtdw17fw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:C6cuuhnK81RfXANjEKjOiObNfnz55TKY5NHFCea1ZhDGmM69WU2qRQDY3scGNonDlRzTRyBfS/I7skiG62ZAMnS2V1E9Q0g16QdO8ie/FnXcBNvPVTP2nxtzbUFXd7iJYEowRwRjOdVoI3AZKJ/6DLY3ObXIWQQA0n9Q6RHtDsdd319Duxwm1KJoUv7fLsFDQVX9w8UYBOthb9pV+QEnP+ncaFk=,iv:V2DUp/54dKd6vAW+L/E1BXfO0BStXKjhqXocXUDnuBM=,tag:MiR+9wL5DvyYqtaQYSqTDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUDRDYXFadFRyNVg1SFI4
            a2NybGQyYWkwWVFzUjlrYjZxVmpsRnMveWlBCnY4OGtQN2txTUVHQmdnVTVVNjhC
            Y241OERlcnRvSVdwVE1lc2FNQlFzYmsKLS0tIFB6S3hqV2lQS2NtY1R6cGJIVTky
            Y1ArN3IyV0R6TW1ud1BDeVoySVpFUDAKw5TW8UhpFIPEh7hufVBQgqC2fS/dnnD4
            xw2B5P01+pv8M8PdsLPaJvX9KZx0hBKk5Uc5X5lr0TlQc4G2wgo8Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:SBZwI8BKU0UTaN7gqeET9dgamPPduPzaVZqfOFHjBAx4HI7D57Rl0errS0FDfYlwT7XOLISDM2lKAsDMShN3SOTy01068HYxrUYXmlDYbcBQ6XjNRZPuXItXy5qLGiHsEtqp+lOU6ozNf06GVEo9u4g/5TYI1pDAwJkAyGLpTOc=,iv:WjEwbMjr1c3MYOLswW0nXct6BmMGxO1Avs/iR0oAOd8=,tag:E4Brf4q0/zEPjoFNdtfg+g==,type:str]
    version: 3.13.3
