apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-basic-auth
    namespace: vaultwarden
type: kubernetes.io/basic-auth
stringData:
    username: vaultwarden
    password: PLACEHOLDER_NEEDS_SOPS_ENCRYPTION
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-config
    namespace: vaultwarden
type: Opaque
stringData:
    DATABASE_URL: "postgresql://vaultwarden:PLACEHOLDER_NEEDS_SOPS_ENCRYPTION@vaultwarden-postgres-v18-rw.vaultwarden.svc.cluster.local:5432/vaultwarden"
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-postgres-v18
    namespace: vaultwarden
type: Opaque
stringData:
    s3-access-key: PLACEHOLDER_NEEDS_SOPS_ENCRYPTION
    s3-secret-key: PLACEHOLDER_NEEDS_SOPS_ENCRYPTION
    region: PLACEHOLDER_NEEDS_SOPS_ENCRYPTION
    password: PLACEHOLDER_NEEDS_SOPS_ENCRYPTION
