apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-basic-auth
    namespace: vaultwarden
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0g3oP1EMF1LW5x4=,iv:RmKPNGp9JIFiJVhbruueA2r9YMaukRFbg+Ene9wkatE=,tag:yfrY6U74MsY3KztCxIF2Mg==,type:str]
    password: ENC[AES256_GCM,data:5FN4MY4sqYk3Sc87W/WXsisIlZp2CZVga1zXF1mWEhHDDR2dFROwgqPHvzBbqUlXnlWo0ifYXdObTRkPmGVbPg==,iv:RFiR/5MSvn+VtZDD6P/9fFc9uvCrAk12knf5s9aXcoM=,tag:JCZfhbL9EE+6NnD2AApdNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSEdRV0M0MkF5dUoxajFo
            ZmptTmppa1BScUh4M2JkWWNDc1Q3ekI1NlRnCkFLNG1UM0todEVjQkdCZjM1Si94
            dzFyOVRlU3dCQkhqM1VIWXRIT01wMDQKLS0tIGI3SDFSaFlyL3FUUVJncHJORFZT
            UXg4cFNLZ2NQVXVIWEk5V1BTc29TUWMKINEI3dbJ0oyER2QUTs0dJIbjm/Y4LI0l
            2srD87Njq5+fwjKB5L6ol1BHU5G0UgqvLPxnTsYM4pZTCDeKet9KbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:40:17Z"
    mac: ENC[AES256_GCM,data:3UaAbc3Y8ZuWU3LyndiT3SRVLI7XQ1QDscop0DwmgaeAI8jEdx8ymJyTz1T/6ByjPNJLQMwU08zmn7h+qmXbzClY1EoNpxtRHoePcW/vraa7XoJ/UbqVsFXTTuZHHbGhJGliFjinxhdXgojM3WU2Hp1JSoUNaWkgAnz2VAZM6lo=,iv:9myepo00iZsNgE+YU7XoeJdFFG3Bzznl0D3MGsW9MCs=,tag:XViYFdTt6wqht4lOZVMoBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-postgres-v18
    namespace: vaultwarden
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:IiNAKHyJsJY5x9o3fK/n+8U2FFn0nimADoY=,iv:s6+to4Y1c05b+TqeTxNficyhkXuJL8r0jDtkcBqdUJc=,tag:fOqkQXKdmoAUMgYL0nDAdQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:ANjtCFWqstL1QZudkbVLZUM58228wURbGPVV8+Fp5+c5yLsqbqY9bTu/+5Vx259v7fYLffwk3A3fkSz7QT3lmw==,iv:lFaFQuxZ42bBuR9I1JAoYMSLxWC7mEFtYQIgQ5kj87Q=,tag:KERsVJgOQKZa5LQeuxf9uw==,type:str]
    region: ENC[AES256_GCM,data:/AzVAGl4,iv:E2MXkCbAoxHBDcNh6CXSqUtStsoVdEDgw5WavlA5/v4=,tag:V2d5QY7omK6GB/dyBIXXxw==,type:str]
    password: ENC[AES256_GCM,data:kw+I72brq2wfLMq8gf3gB/8jg4YEtE0PUXJAX6aqgIG8Y+smKfi9F6P/Pv6WxaqEl1B0+2eG5nlzkdm3Fp1xVA==,iv:+fqLWaER7eqJEyCC/CXJJdA/syYtPB6tYSm6Zgr7MH0=,tag:GKXPMw0hJO15eAcpKw0ZwQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Vq0/le6oiq86HCITonuqKUng8uXw9ZDgksB8t54mdgcRpfROf19hKZEHYBKXKYDRGM8mSWTwVSgp4diDmyhTzPH0DgWCOiKkrNcmhHOtrGGEk/MmN0Kg+EUBf6oC4RLB1j7ofpkSm/7WnJi9vO3m17fKbgDV3ikqyjPvSrL6Dahzbg2pUdj4QigXOnX6ENWhrQqqKgvpFm2slUyt1QiCmw+9r9g=,iv:tYDAWzqwqd+LJhnP4CvWZXjAs4vplH/qwo3piG0PzVo=,tag:AZBQ6qrmnPM/YpjV3WT9yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSEdRV0M0MkF5dUoxajFo
            ZmptTmppa1BScUh4M2JkWWNDc1Q3ekI1NlRnCkFLNG1UM0todEVjQkdCZjM1Si94
            dzFyOVRlU3dCQkhqM1VIWXRIT01wMDQKLS0tIGI3SDFSaFlyL3FUUVJncHJORFZT
            UXg4cFNLZ2NQVXVIWEk5V1BTc29TUWMKINEI3dbJ0oyER2QUTs0dJIbjm/Y4LI0l
            2srD87Njq5+fwjKB5L6ol1BHU5G0UgqvLPxnTsYM4pZTCDeKet9KbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:40:17Z"
    mac: ENC[AES256_GCM,data:3UaAbc3Y8ZuWU3LyndiT3SRVLI7XQ1QDscop0DwmgaeAI8jEdx8ymJyTz1T/6ByjPNJLQMwU08zmn7h+qmXbzClY1EoNpxtRHoePcW/vraa7XoJ/UbqVsFXTTuZHHbGhJGliFjinxhdXgojM3WU2Hp1JSoUNaWkgAnz2VAZM6lo=,iv:9myepo00iZsNgE+YU7XoeJdFFG3Bzznl0D3MGsW9MCs=,tag:XViYFdTt6wqht4lOZVMoBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
