---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name vaultwarden
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: vaultwarden
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: vaultwarden-postgres-v18
      namespace: flux-system
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      vaultwarden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          vaultwarden:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
            env:
              TZ: "${TIMEZONE}"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-postgres-v18
                    key: DATABASE_URL
              DOMAIN: "https://vaultwarden.${SECRET_DEFAULT_DOMAIN}"
              SIGNUPS_ALLOWED: "false"
              INVITATIONS_ALLOWED: "true"
              SHOW_PASSWORD_HINT: "false"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    service:
      vaultwarden:
        controller: *name
        primary: true
        ports:
          http:
            port: &port 80
    ingress:
      vaultwarden:
        enabled: true
        annotations:
          haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
          haproxy.org/ssl-redirect-port: "443"
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "DENY"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        hosts:
          - host: &host "vaultwarden.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: vaultwarden
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: vaultwarden
      tmp:
        enabled: true
        type: emptyDir
    networkpolicies:
      vaultwarden:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to:
                - podSelector:
                    matchLabels:
                      cnpg.io/cluster: vaultwarden-postgres-v18
                      cnpg.io/instanceRole: primary
              ports:
                - port: 5432
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: *port
