apiVersion: v1
kind: Secret
metadata:
    name: litellm-basic-auth
    namespace: litellm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FcY3ojbP4Q==,iv:9X1AazJExCyNdVZPk01oI12m2PdKnn7l/t/WoiqtKM8=,tag:s8t8xosQGot02U9iy8MJpQ==,type:str]
    password: ENC[AES256_GCM,data:VnVp+JwpMV/5ecyBQsaeY3VFM+5TgPG/0eq+d7+vHw9ELhwG3P/w7dzc8AcpnNO/1t9c0FZ6X7hsnN4v0HYCUg==,iv:xkv6EvYQKbymGCtvykAqqpoLvM9uX3GHzovLrt0uTvw=,tag:qdEoJ7sVBeF4F75gzP77lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZDJKRmV4c3A1YlJXYkF3
            NmMzZEdubVFVOXZzN1ZLdEF3MGNyQ25rb0VjCkZsdHRkRkZCTXhsM0J1Q3RCK1kx
            dVUyYWxvcEFnK3BPL3lWZjZvZytJWTgKLS0tIHQ4dXdYM0ZiVHZ0eGMxYU1MZnQ1
            aFdFWDVjdHIrQXp3TUVIRmMwdU5hUkEK5b5CPJKZNpzqoWE8VYMa7cjj4+v/PTgz
            FqHrGT27IU8xZcxg2WIKkcGVxPDQadua3SUwW4mk0mPp9PEZ+1V68A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T22:27:43Z"
    mac: ENC[AES256_GCM,data:Iugcxhu3Irs74l71vTWlSBkfyv/NiBtrZnUSO1zZLjRl3rA0jvYrq1K+vwnHfNDXsTfbOgAHgDmC3d1zYun9dIcb9V88b/X58z4Jw7mzEkWioLJ0DN2eP6Sxn2JuVh1SayeCjXIrRuXZYEyA04qC36oqj4WpiLwrYYjMSHeKPr0=,iv:/V67G1ha45zF22Ls48dSn9zpEOxaki8uxfQUKA+wVZ0=,tag:OEu+Ac2nD33za7VKYV8S7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-postgres-v18
    namespace: litellm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:o2k2t9RO2bxoSj8QcigxiaHNBrz1JKfyb4E=,iv:bvY2O4VxQlh6vmZgIdNZ8omVcfXaG40gqvF9fFJ/+9E=,tag:FzGTUIb7EhsfcVRx8OZeDA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:96Z5vbDywSFB0+BtgKkOZk+Uv2I4y7FOJOojW6bvjsL6dcE7GMbbs9x7Ff+Bvun01C3jf/6N3LSZAtz975Dq/Q==,iv:QTOOGu3v+XWiuJ1tgCW30YbwW4V67DZG/ljTwGdQwoQ=,tag:ppH0wtn7UccmqSddJOSFCQ==,type:str]
    region: ENC[AES256_GCM,data:x54M08xD,iv:Lo5g10J4hQBQVNJNt8jV9kv0QgbucMFoLQ+WOWxnU74=,tag:6/1pkwPabmMkj3mzCxxMPA==,type:str]
    password: ENC[AES256_GCM,data:yuEhYq5Tv1qj3HXQlII1tTLj9li01L9eS3i27WXqY4+4j/SGfGz1LQM7iNhRWB7mR3QEeKv2xnxZIDRBWlj/fA==,iv:kZXVpuaCj7KX3gA+29E0S0FDKP95qiZYMQ80ojFo1HE=,tag:l/6FL5xbTIQhXUeIG+phPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZDJKRmV4c3A1YlJXYkF3
            NmMzZEdubVFVOXZzN1ZLdEF3MGNyQ25rb0VjCkZsdHRkRkZCTXhsM0J1Q3RCK1kx
            dVUyYWxvcEFnK3BPL3lWZjZvZytJWTgKLS0tIHQ4dXdYM0ZiVHZ0eGMxYU1MZnQ1
            aFdFWDVjdHIrQXp3TUVIRmMwdU5hUkEK5b5CPJKZNpzqoWE8VYMa7cjj4+v/PTgz
            FqHrGT27IU8xZcxg2WIKkcGVxPDQadua3SUwW4mk0mPp9PEZ+1V68A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T22:27:43Z"
    mac: ENC[AES256_GCM,data:Iugcxhu3Irs74l71vTWlSBkfyv/NiBtrZnUSO1zZLjRl3rA0jvYrq1K+vwnHfNDXsTfbOgAHgDmC3d1zYun9dIcb9V88b/X58z4Jw7mzEkWioLJ0DN2eP6Sxn2JuVh1SayeCjXIrRuXZYEyA04qC36oqj4WpiLwrYYjMSHeKPr0=,iv:/V67G1ha45zF22Ls48dSn9zpEOxaki8uxfQUKA+wVZ0=,tag:OEu+Ac2nD33za7VKYV8S7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
