apiVersion: v1
kind: Secret
metadata:
    name: litellm-basic-auth
    namespace: litellm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fhJFDIaYcw==,iv:ilYbALXhpl1pinmPHyEr+ywK4F4DlmfGmEmpLvl2/n4=,tag:EH1vAW0klT2xefPDS/CRPQ==,type:str]
    password: ENC[AES256_GCM,data:N8N9A9viIXdeEjKwBriy4uhafJj6n3UW7wyGwcEZB3C8JlWuEJTf/ZQD0vSnsNW+k2fnZxl7uw2PlL8a3WhNFQ==,iv:YJSD9KxF3+R253npbEulfWgJRnvOKupKVO/xBxtVOCw=,tag:Omj/CQiNsHHRg2cMdTU1FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbHRMa1poSmpNTjhEY01F
            NGozZTk1RHliUVNCT1A5aFdFRnhuWXhTTWhVCnhTT1ZkYnZ5RnN5MG95dHFkeUpx
            QTF4VlJsL2hGWXRYTzh1YjgxdjEyWVUKLS0tIFlobjd1YnBWSUUzS09BenFQQ3Jp
            V2E0NUJDdkdSbDdBUHhQc2VXc3AwNUUK1UNAVuo7twMYDU04Fhv3MHlucOCIYOow
            CD5VAHXmtKf0UkWyx0H1qupy9sCt5kRjOSisyRby6j4YtzK37Hy4iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:kZZ4wgqMa+pbhG7FpjiddfehrYThwJTpy22Pb33O1wUZ2i2JaeJmqIM9R9F+cCoXSZlTrpFlXdaX0dNIlke66CyUAT8nRFnyGFhdEHmCMNjnXK6Dci7wGVVMI60E2lxlW6U451xZ/iLCvnFU9IDTHCayqSVWywwJsJzpXVp7+P4=,iv:vfk1XBFRmTC+HnJLoDdLgY46RaXzfAI3ZTmqvEJ91iE=,tag:KVp6Vat3sRJPYQH1DGAkFg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-postgres-v18
    namespace: litellm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:2nXItme6ZhI977oJojyWYqQgfDymB1HssDI=,iv:LhWl5tFs7tcNUaEbZgeiM5UoQtjwGZvVIHO67k0VVLE=,tag:hTTZQlczbBkJDfS6w70Ocg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:/MzRd7QYOrf6ytNWkP/Z33QvWGRZf0Xp14iZE0d7kGBhi5L/dIBpbeknCAhCqrfdWD8GfVIBkUexQ7tkrMw14A==,iv:iaIxJxMeHL2hBOyUGxnqggT1xjZ7bQZVdxV0baOx+0o=,tag:1dTJ2kzMfnXC2L9xdB0emw==,type:str]
    region: ENC[AES256_GCM,data:zGpIOdlo,iv:EKax1heC0SeBz0Fz/KP8Y9g51/oxYcHK5UfgaUk0n98=,tag:dedAOtCGFIZYWjPMbslvrA==,type:str]
    password: ENC[AES256_GCM,data:/L0RXYGiCEvgbPox7RuWlJsFLZGlCcaH8pXQbDb/YdY9k13lpB1QwtHqBtAjgeURDrVLSJ2Jk2rNyEk14N7u2A==,iv:CDQdAQyYKbIjFbkw4Cpqi0GYMRJZ8AA+Y+dAv9SprYU=,tag:vREvE6BVayPC75wPbEgHfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbHRMa1poSmpNTjhEY01F
            NGozZTk1RHliUVNCT1A5aFdFRnhuWXhTTWhVCnhTT1ZkYnZ5RnN5MG95dHFkeUpx
            QTF4VlJsL2hGWXRYTzh1YjgxdjEyWVUKLS0tIFlobjd1YnBWSUUzS09BenFQQ3Jp
            V2E0NUJDdkdSbDdBUHhQc2VXc3AwNUUK1UNAVuo7twMYDU04Fhv3MHlucOCIYOow
            CD5VAHXmtKf0UkWyx0H1qupy9sCt5kRjOSisyRby6j4YtzK37Hy4iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:kZZ4wgqMa+pbhG7FpjiddfehrYThwJTpy22Pb33O1wUZ2i2JaeJmqIM9R9F+cCoXSZlTrpFlXdaX0dNIlke66CyUAT8nRFnyGFhdEHmCMNjnXK6Dci7wGVVMI60E2lxlW6U451xZ/iLCvnFU9IDTHCayqSVWywwJsJzpXVp7+P4=,iv:vfk1XBFRmTC+HnJLoDdLgY46RaXzfAI3ZTmqvEJ91iE=,tag:KVp6Vat3sRJPYQH1DGAkFg==,type:str]
    version: 3.13.3
