apiVersion: v1
kind: Secret
metadata:
    name: litellm-basic-auth
    namespace: litellm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:GIs9uuS/2Q==,iv:FKdXLEnWwOhLRYg7lla1GuTB/IadkLDP6X89A/5SCWU=,tag:C89+blIj7iCCoFrLm9UT+g==,type:str]
    password: ENC[AES256_GCM,data:Z1+j/8YreKI6+SJUODbY0yJZqz17y2trSXhtW8KSYvEMqd0aJWVQTdzI/sjJ9pjae39BEFSqs3GffPqwxk2zaQ==,iv:i791TNu4aNuN1tr3NRLVJmmvBijFbujLHoBrqCkqg9Y=,tag:W2KO1qJNZYHFXIhEGhIxVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYk5QeGRLME00QiszOVVo
            dmduMG1rTDQ0TVZ1N0VzaGtnbm02cjBxQW5RCmhWeUVFM0kvR2FwTnJhYW1zZDZS
            UG8rYlRnWEVlek5BMFdDZHFrMjJIT3MKLS0tIC84YWZ1WUdDRnM3bENKMS9uMVBE
            TnRROFFiT2NPS1hlUDBtY0RDOWpzWXcKc7DdMxsE8vUJ4fEWp/lts7ddXlMHSW4J
            ac135RfML+aVb2jObM1YuBLlNXJV1tmPQTofMIYz12SH2SurpvJRmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T20:02:18Z"
    mac: ENC[AES256_GCM,data:o1h6S7rWGRuoBTn4cd10OIxnRcht09H4BdArFCtJo9Z5Cos04oSeXYd8IXMabvVTdO69NF2sosvIVrbd8lUbfrBPrYIfbt+DPmZII9akvyQ5/5G00YlUNaf5z2h/+gzVxrssK4L3s9Yoj7+u+aMGz8EvaFthEZrhI3F2nHcwaIw=,iv:mgnSgLD2PfLcJjcP8TcmVMJsqZTyIFMzPbTR9cscgFY=,tag:FOf/7drAW6gwerD51zxoUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-postgres-v18
    namespace: litellm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:EPghU0vardPqPF7ira5h5/hb0f8VA/bf4dE=,iv:DB8tzfgaTgMpEHUT68oUhmAB4AapSq4E9fXM5ckDyP8=,tag:MVXaPY55s61qjL3ssGPSvg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:cj+asQLFgfvVnaFq7b9ldjr7aVsmRTIpnOw5jgSRSEI0WHcSbpn6J+U/YTAEUNI1iuDHBMcq1rEZM/Cb/Mt8fQ==,iv:I3EDlpOoPTjKpQg3tY0KoGKqWnIcAQoVWeyw4C+O6g8=,tag:T/PoulMfO89PESdwtkB5Cg==,type:str]
    region: ENC[AES256_GCM,data:Cr21px9w,iv:GYeeZkf3nqTtS6Z2+gK18Viegr70SNWaKFX05LNpICY=,tag:NZ4JKTSrgLWmdleUAbv0aw==,type:str]
    password: ENC[AES256_GCM,data:r0zH5upChYv2epM0CQcuX7e7Y8suf/QYGvIuImrQvwStiBIrOkvHLXlYWFachSP/BdxoXIncvYRgc2zygC+BAA==,iv:U7OTBt1j4p46PswieNAKTUWTQJ6CDaKVAi5O9khKXxQ=,tag:Lx2EvQ8Hy0AVH+dUTZIadA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYk5QeGRLME00QiszOVVo
            dmduMG1rTDQ0TVZ1N0VzaGtnbm02cjBxQW5RCmhWeUVFM0kvR2FwTnJhYW1zZDZS
            UG8rYlRnWEVlek5BMFdDZHFrMjJIT3MKLS0tIC84YWZ1WUdDRnM3bENKMS9uMVBE
            TnRROFFiT2NPS1hlUDBtY0RDOWpzWXcKc7DdMxsE8vUJ4fEWp/lts7ddXlMHSW4J
            ac135RfML+aVb2jObM1YuBLlNXJV1tmPQTofMIYz12SH2SurpvJRmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T20:02:18Z"
    mac: ENC[AES256_GCM,data:o1h6S7rWGRuoBTn4cd10OIxnRcht09H4BdArFCtJo9Z5Cos04oSeXYd8IXMabvVTdO69NF2sosvIVrbd8lUbfrBPrYIfbt+DPmZII9akvyQ5/5G00YlUNaf5z2h/+gzVxrssK4L3s9Yoj7+u+aMGz8EvaFthEZrhI3F2nHcwaIw=,iv:mgnSgLD2PfLcJjcP8TcmVMJsqZTyIFMzPbTR9cscgFY=,tag:FOf/7drAW6gwerD51zxoUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
