---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name litellm
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: litellm
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: litellm-postgres-v18
      namespace: flux-system
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostname: *name
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      litellm:
        containers:
          litellm:
            image:
              repository: ghcr.io/berriai/litellm-non_root
              tag: main-v1.81.12-stable@sha256:24360952e183cf34f53fcc6d207befd9b82bd29cea451355bf6b4e279cd746b7
            env:
              TZ: "${TIMEZONE}"
              REDIS_HOST: litellm-valkey.litellm.svc.cluster.local
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: litellm-basic-auth
                    key: DATABASE_URL
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
              limits:
                memory: 1Gi
    service:
      litellm:
        controller: *name
        ports:
          http:
            port: &port 4000
    ingress:
      litellm:
        enabled: true
        annotations:
          haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
          haproxy.org/ssl-redirect-port: "443"
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "DENY"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        hosts:
          - host: &host "litellm.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: litellm
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
            subPath: cache
          - path: /.npm
            subPath: npm
          - path: /tmp
            subPath: tmp
    networkpolicies:
      litellm:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to:
                - podSelector:
                    matchLabels:
                      cnpg.io/cluster: litellm-postgres-v18
                      cnpg.io/instanceRole: primary
              ports:
                - port: 5432
            - to:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: valkey
                      app.kubernetes.io/instance: litellm-litellm-valkey
                      app.kubernetes.io/name: litellm-litellm-valkey
              ports:
                - port: 6379
            - to: # Something on github
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                  - "${HAPROXY_WHITELIST}"
              ports:
                - port: 443
                  protocol: TCP
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: *port