apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: litellm-secrets
    namespace: litellm
stringData:
    master-key: ENC[AES256_GCM,data:SqVgZrT7Uw==,iv:pMhnpTFnZ4Abfl+5U3DvZTGL6MRWYyavzc0JvkGH8oI=,tag:36Sp8eEeuaJ4C+khPZ0NMg==,type:str]
    salt-key: ENC[AES256_GCM,data:Sc7YPt7eCoTyxcFPcvH1q/5X8Fhbw5W5sw8rriNcQ6idEttLXFLk0QbnTnlU1MZ4Sdi02vPBjW7ZfPAVCWaa4Q==,iv:l+SUl6fVeyM0C+jBHKZqJGa+4jyZ6tQlmP5vCoz/eN0=,tag:9fwGmvQ8piKy50fMfwBdbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4amxHdTRFcEtrdUFRd2ZB
            L2I0bkwxeW9DekJKc256eDdqTk11eDFIckFFCk1RdTlMUXBzL3pvbmRFSWoyVEVU
            bmR1MldtK0w1cVU5MFFISUJTMHdSa1EKLS0tIHg4TFdoODJwWGw4NjFPaXRVZ3lE
            MjdESThta2VIa3Y5VzU0U0FuaHM5Qk0KQrTHdaFY5mBmK8qYCbkMI0bazxC5AAi5
            JZwK3pb7y4wGR3Ng5A67uFXNAK4AtojhitA+tlGYQMVqzLRHEMyo+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:27:19Z"
    mac: ENC[AES256_GCM,data:ZtBTppF9S9ecgk4RCzLHPyyfR7ikO+n2ZsJABUFzbWAkfu0VuGsi1Cacp8HrKrrbyERiYiCDCHMrgxz2Mdyao8b4N5sUWEwfbV2KoAjGVnh8zUzeNqgTlboQ/XBaYmYfnIWxQDjVqq9M9KGYNFGOdiWShtHBwXTAtwb8JygnbYg=,iv:LwCp4Rr8fl+4T3nwgm7mvEP//B5BHG/kqet+S4jRqpQ=,tag:Ykj+M8/1ub3PQn4qWtX+rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
