---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wastebin
  namespace: wastebin
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
