apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hindsight-secrets
    namespace: hindsight
stringData:
    #ENC[AES256_GCM,data:BzqTwMTg+25VWoA3UIb0TG/z22G6u8gloCXTjBe9ReMjDEP0yp/mvPh0gVY/neORRC5vK2/YFcbGXk3LLTM9WJe1,iv:nSZ8N/FS0quOmIAMr/YSAtE9AYdFlw1ZfGZnV4kJyf0=,tag:IEPNO4XkGdbqTA+MIMN5Bg==,type:comment]
    api-key: ENC[AES256_GCM,data:XcHYXaCcosM7FnF0AemNsyo8xCdIZoW3ZTA7V3jJU8U66BO/eCKj+L8+Aqu7RWE=,iv:kxhjmty/DEt0xuRHl19Fy+8ArP/9Bl0ZD42Qq6KFP7c=,tag:Bf4H2qILUQEW+rkRmqrcIg==,type:str]
    #ENC[AES256_GCM,data:PqAtQ6D2c98J5JJ6/N3lBGGYhVBIulGqpFCuGsnJM/X3U+/eaCJesTw45lZFJ3pj+P7Si5SJW5/EVu0OhuB26WBkFw1RHl/x0RwA+oi2fVHZv6sD,iv:K2r1z6nYCY7eYbO4ZqaKb+6boaB7rrT3vXv1yzpsLwI=,tag:hmza3T+ITBZhC3LRtG7/hg==,type:comment]
    postgres-password: ENC[AES256_GCM,data:4FWBedcSbye4YJcDxTsp6HU4ee28SXnz5vuRvOqT8OZsngToFZoxJEwcHpkNPMq2+Lo7El7YO7Tkk7gYZqJZmg==,iv:ocmZv8Ig/TsTPWLgsrJypD9LXFhZwbJK+EXMGgWN0oU=,tag:XzFRo0nqzruRYNTUorJjhg==,type:str]
    #ENC[AES256_GCM,data:Gh/3yJf+OfrtQyDttoe5JJ5DrA6Ho86rfoAP05nWix9e+b/V3iem4b45Va9QfmD7DCNcfEmz+fKbzTo=,iv:m9RbbIjqJpy9uoXg7TYWb6qiAObKlN6It1eZjdxoE74=,tag:aRTyqbv9T31G9LNY+DSkeQ==,type:comment]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:zoO6ktd0YdJgbGT7WQYU6lnkjgi64k/4iA==,iv:UHTP+dSBzkVnpPg55kah5EsaAuK/qLXIuuDUFz5ONIU=,tag:bvxWaXY/zl/2KorZXvA0gA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bTNwdDJjRkQzeURzSEdM
            Q3J4Z0xCQ1dxK1BQcTR0ZUVaV1JkMWVDSEhzCk5aVXkwK1o4aUQ3WDV2WkFTQTBH
            VjRRbWg2VTRFY2hDa21wMUJOREU1MHMKLS0tIDUzNEFLUVIybXVmZWFCY1RUV25n
            RzdNZ080SitIL3VEdGQydGZjc3pZMlUKImM2fs1CucRT4ntiejT4izFMkyWqHeyu
            /lLthjs9rTQjJxm1yBFkyq2nH3Iu2EK8lR2c0VA6whaq7Lbgn/zCXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T07:48:01Z"
    mac: ENC[AES256_GCM,data:ZDKLI9VbhpwNVbMFljGBnkOqf962EeEEGY2F+kle4CuRd/N0WmoxR0mNChj7DfoZ49y8YmZXPx9J1eNu1KLErkk6Hr8prDJ/a+DEh2MjLUG4g2htrtGj9me4ndBq+f53HI47wrhcl7YXZB5O2zL8TvbbvSTyRycvO0SNMlipd6g=,iv:28yxgqkuLY951XrAKxVS/Qoe+Bv1r8ioav9EDHBkBIs=,tag:kTIBTAsUBrP7Y+Z4+XOQag==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hindsight-basic-auth
    namespace: hindsight
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:b5v62Bg3sC83,iv:ojHu5JOkj8U6hWyfoLqXsDDjfu4Oo2CNTT+m/6Dulp8=,tag:SBAD/K8/IjfukuKHbbdJWQ==,type:str]
    password: ENC[AES256_GCM,data:hdrrvew0GShXigBim+sLbSURPbVp0P+baCelz0E6cL3BzBzWwy3Ma9N83MhSlCAjjYf4IO0QWaQfIQm1M2qCAw==,iv:odhsHVpzzftY5EJKsA7wQfWRd7QYOtM9936oNewK1c4=,tag:h1O6EKrDfyOh3WoeC60Pbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bTNwdDJjRkQzeURzSEdM
            Q3J4Z0xCQ1dxK1BQcTR0ZUVaV1JkMWVDSEhzCk5aVXkwK1o4aUQ3WDV2WkFTQTBH
            VjRRbWg2VTRFY2hDa21wMUJOREU1MHMKLS0tIDUzNEFLUVIybXVmZWFCY1RUV25n
            RzdNZ080SitIL3VEdGQydGZjc3pZMlUKImM2fs1CucRT4ntiejT4izFMkyWqHeyu
            /lLthjs9rTQjJxm1yBFkyq2nH3Iu2EK8lR2c0VA6whaq7Lbgn/zCXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T07:48:01Z"
    mac: ENC[AES256_GCM,data:ZDKLI9VbhpwNVbMFljGBnkOqf962EeEEGY2F+kle4CuRd/N0WmoxR0mNChj7DfoZ49y8YmZXPx9J1eNu1KLErkk6Hr8prDJ/a+DEh2MjLUG4g2htrtGj9me4ndBq+f53HI47wrhcl7YXZB5O2zL8TvbbvSTyRycvO0SNMlipd6g=,iv:28yxgqkuLY951XrAKxVS/Qoe+Bv1r8ioav9EDHBkBIs=,tag:kTIBTAsUBrP7Y+Z4+XOQag==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hindsight-postgres-v18
    namespace: hindsight
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:xkfw2403ba08qe5yg+KShjFt+rI5YSm8EVo=,iv:8XDRnKq24/Xu/b6+TzJKKw91KsNPupS8txcB6b5FHIY=,tag:vdL8cz0BM+HN3dEEtZV95Q==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:DKrXkT4o6i3L+iPD+gO2dfC7+zxJPxK1isAgisM68gxpn93sbt2rZeR6pC+DohhlnEzKeUd3HMIxuW89ecFW6A==,iv:FAAOWNs7KwG21NKN9+Up1AY6AWl7N1i2tipBHKsRVxE=,tag:sO5/f5Dy42Xk8FKlTDVGdA==,type:str]
    region: ENC[AES256_GCM,data:imzmK2Cn,iv:Po3jOOnED0OO24tkrrxAzzHS/WmI6p+jWFZbTu/hI64=,tag:zc1TclDeba1htWUjUAXDag==,type:str]
    password: ENC[AES256_GCM,data:Nr+nCbXylchzu0jfijtdu3tvSt9ldkwsAmaRnrn/eCa45avsmn4eX0XEZKJbT9cx+tw912PpPxk488YDVRdwTg==,iv:CbvTfbfaLYvCHZI3h0y780aaPREkxdC76BJd3u+l3yQ=,tag:R78SFjnXEJO16iQBUkL4gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bTNwdDJjRkQzeURzSEdM
            Q3J4Z0xCQ1dxK1BQcTR0ZUVaV1JkMWVDSEhzCk5aVXkwK1o4aUQ3WDV2WkFTQTBH
            VjRRbWg2VTRFY2hDa21wMUJOREU1MHMKLS0tIDUzNEFLUVIybXVmZWFCY1RUV25n
            RzdNZ080SitIL3VEdGQydGZjc3pZMlUKImM2fs1CucRT4ntiejT4izFMkyWqHeyu
            /lLthjs9rTQjJxm1yBFkyq2nH3Iu2EK8lR2c0VA6whaq7Lbgn/zCXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T07:48:01Z"
    mac: ENC[AES256_GCM,data:ZDKLI9VbhpwNVbMFljGBnkOqf962EeEEGY2F+kle4CuRd/N0WmoxR0mNChj7DfoZ49y8YmZXPx9J1eNu1KLErkk6Hr8prDJ/a+DEh2MjLUG4g2htrtGj9me4ndBq+f53HI47wrhcl7YXZB5O2zL8TvbbvSTyRycvO0SNMlipd6g=,iv:28yxgqkuLY951XrAKxVS/Qoe+Bv1r8ioav9EDHBkBIs=,tag:kTIBTAsUBrP7Y+Z4+XOQag==,type:str]
    version: 3.13.1
