---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  interval: 2h
  url: https://haproxy-ingress.github.io/charts
  timeout: 3m
