apiVersion: v1
kind: Secret
metadata:
    name: mail-smarthost
    namespace: mailrelay
data:
    password: ENC[AES256_GCM,data:dX+nOcgV8ebTbfzc56AM3hEBzcRjjKdb,iv:w3Ilq09f7sctX65jferBFA2cd+4F07lYNYRpc8lilQ8=,tag:kNCRJOZmBKZ1kJdVQDnlcg==,type:str]
    smarthost: ENC[AES256_GCM,data:BuGNko9+FQnebU69/ue757NH/vAjuiriU5jenfLWMKinEOUzjHz32g==,iv:XLDBKIxZLJHIaJixJomURIdI01KQHjl4yJnRLWIIrHg=,tag:0o1fRWcoQ/NVpHAP1b9k7w==,type:str]
    username: ENC[AES256_GCM,data:HCJ4rRnHbyLdmen2xR2H/gzy2gw=,iv:znhSa2eDVtpmhOUsFOGfAjH0uOVKXQzXF8bCovB3XYM=,tag:g/BX31ojJUVDT44uERU+Fw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXRyNXFpaDNqa2lWVW4z
            OGJySDFLRHdKYzFlZW5GTWd6NnRHd2pYZ3lNCm9ieGZNZFp2enNSRlZmWVM5Szhn
            TEduMUx6TW0wOHdPZHlSLzFtWWhiZFkKLS0tIFhic1lFbE5WQk9TOVJpOE04K055
            SzFJVCt3ckpwYmhIOXdYaGhKdm05TFEKyx1NauGfLBeUzdM8dYoTd0TkevXAdZxs
            rxsyAxUGmiDr2NA4ffGAhxrh3TXFmTrczMrin34zUvb2eDnOTe+TVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T14:27:12Z"
    mac: ENC[AES256_GCM,data:vdYx1cFoP1FHn4QrDQ2So+iPK8dNQRJTRdxokY6oHSMhhnjIV09HDreEQthq0KuXeytOYack82DG7zcaert6DzkZBigAXlPVHl2k9gv5o28xts65mlm8CNhT5Q/jwssNHar4miXWidrYU9UKQ+j7Z20cr/OmEwvhhqj1qLtFAlI=,iv:MuG4gXoEOPlp089W/Rsj3oLKu9/kg2OVYX3gwC6gGSc=,tag:Dk2RVPuDExLJBXAGK4Tm1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
