---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - helm-release-plugin-barman-cloud.yaml
  - networkpolicy.yaml
  - oci-repository-plugin-barman-cloud.yaml
  - prometheus_rules.yaml