apiVersion: v1
kind: Secret
metadata:
    name: invidious-basic-auth
    namespace: invidious
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:j10xxyY=,iv:9F+3Olh0znp96EdtQza8sp8GBIDfB58EQi/8tCPbGis=,tag:8IzMjh3Lcy7ulCg1uZvhuw==,type:str]
    password: ENC[AES256_GCM,data:uwPP5KDLEAx5072atAMAYlPDSgqwB7V03XMWlom0VgE=,iv:Bu/GDNiB9i9ktyclVdZdrF2b/r8d8T3PAe2mX0Syqf0=,tag:wZmUoneznbL9O81xDd4jFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUENseCt6ZnRoTXU5ek05
            OExhekxaT1JGT3N4b0tMWjVzeCsxN1dEOGhZClliZU1JQzl6b2ZJeTdSZkcwTkZU
            RjgvTW5BeTdtb3VPSnUxdTZ2ME5lVHMKLS0tIDdta0txWkNxSEQxaTN4bXB4NS9s
            dHMzQVdVYU1aRUcxeTh0Mk5Qc2hNSUUKgHizfoevtO1QbvJ/0Sh1TWB2sz0+XZav
            3aib+4ylw6mm+pB20v6+1CCpV3k6k4gz9ns5Tiz4aM5TCarvgRFP0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:uzhuFebzzBXfwqlJox80eQPaO7KPtAQzjd6aOAdemFIcQs8jVWqOpo+Gw3p3Nv7AmRc35KthVoPXJbob7ZPxn8WDwzgVm7zn2eEzwgeVukg/OWLpMtrkF0kySj/p3EOCstsitV8yezCpFrGJ2JkP2kwkz4Xy0V7kYlOybwLAz8s=,iv:3yDAQh0pArcLoogw44dDDLRX889cduiZuIlKo10ZXnk=,tag:BkpmPZPTo+myMIoeJqJtrg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: invidious-postgres-v18
    namespace: invidious
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:b2xXzk0294ThIjMzEbV+LJaKG12a0PvhH1c=,iv:vT9HRqkQPj98pDYuQ1VuDFmDOiXFVzbNP+zG8Za+CVA=,tag:dBUDHrQWfoVfG/hzXVXKFw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:rES1BaDxGEdXWIdMnjJTCWXDLaD2H8+6hcpxfJVvrJaAB2IPzuHjZ4AtJojlxbVmB+MiButXum77IFD13/CAdg==,iv:BcOquQoY7IlbeUiZ8nkAmI26OVeqY1B0V/pmBD78w7c=,tag:b1lE95jMv1ZxSCSy2tKgPg==,type:str]
    password: ENC[AES256_GCM,data:Yf0PY+lR6b3i9w/4/SqVBLPFfxkLY9ykdQuaRMHjaLU=,iv:bbUefJ5+fe/FW1JiCQZimvFwsaQujY6rG5TGr4nCK3U=,tag:3DbLQF1B48cRAOwba3zyAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUENseCt6ZnRoTXU5ek05
            OExhekxaT1JGT3N4b0tMWjVzeCsxN1dEOGhZClliZU1JQzl6b2ZJeTdSZkcwTkZU
            RjgvTW5BeTdtb3VPSnUxdTZ2ME5lVHMKLS0tIDdta0txWkNxSEQxaTN4bXB4NS9s
            dHMzQVdVYU1aRUcxeTh0Mk5Qc2hNSUUKgHizfoevtO1QbvJ/0Sh1TWB2sz0+XZav
            3aib+4ylw6mm+pB20v6+1CCpV3k6k4gz9ns5Tiz4aM5TCarvgRFP0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:uzhuFebzzBXfwqlJox80eQPaO7KPtAQzjd6aOAdemFIcQs8jVWqOpo+Gw3p3Nv7AmRc35KthVoPXJbob7ZPxn8WDwzgVm7zn2eEzwgeVukg/OWLpMtrkF0kySj/p3EOCstsitV8yezCpFrGJ2JkP2kwkz4Xy0V7kYlOybwLAz8s=,iv:3yDAQh0pArcLoogw44dDDLRX889cduiZuIlKo10ZXnk=,tag:BkpmPZPTo+myMIoeJqJtrg==,type:str]
    version: 3.13.3
