apiVersion: v1
kind: Secret
metadata:
    name: invidious-basic-auth
    namespace: invidious
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:lY6mEE8=,iv:rlpPSWN7Y+gYjqSqnDJlm5vHqlxCGQEg9+p0WwbKVlc=,tag:rMEYEQlOwmjpdetKTlLmlw==,type:str]
    password: ENC[AES256_GCM,data:Vlza/2Jj1Hj67GVKICif1PT7X1TUeJz8m8FvHBU1aIo=,iv:j4H5U3oUzSvz5lZS89DLSjoncFz4SYIIFIL4HKvvFDs=,tag:EEFzpTIhti6KbDsCUYbEYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd1dWSTFpem5JODRvd0hH
            cWM3eGNKRzdZaTRZajcySjVHSElMMWdSQWlRCmNjam9DRkNEbW5JbUw3VG05a1JX
            eDNHbUpjZlJWd3lIZUJvUTFORWpyV2cKLS0tIDZFL2Z6dVRFUXJHemhFdVA5ei9q
            MnMrWTVTSEo1Qnp3eWpFTkhWK1FVNlkKpasr5z7nAtfH9e9eAOX8Lra89RKCyg2W
            9R3vgdHynWxHCdvQEYLsCzZLk0xIfOrOMBcquXmxhe4exgA9X/t6Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T18:45:29Z"
    mac: ENC[AES256_GCM,data:VYdi2Vmec5ToSptSOzJs5MbL2sIQw/f73WCzK6ulXerLtrywNZ2F3ROE43WL4HI+kynNjDbdzqr0tuWKf1zcBTCRP5uEo8u1uTlmTK8m/tOnjl3FzcxbomN7APqZkWj1Iuorpj03QMD1aYbKawRbvaGtNZPSN5du615c9G5SSdE=,iv:awUoE9HJjwizTzmssXUJ4WmDH4lis/mFn9bz8jzeOzg=,tag:TN4nNrHsyvTTrJA45Jg0rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: invidious-postgres-v18
    namespace: invidious
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:PxaRF41RP43D6VfH1dElOHoJdJc=,iv:Gw5jaVt7VxIKkNwrEMS6s/oJ84gTXX5Tedf293ENQe0=,tag:/i+rGwOvyYfVveihyJ8/XQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:91o4FEqRGMhTofQLKJHXn8+Twbg4p1i0UyrEhfcpp+YqLvby896fww==,iv:DezsKeTUtEGJjhPBO5eH62LKdbMVe+20spvNRvwLgq4=,tag:4PrY6RT23q59XETGq07a2w==,type:str]
    password: ENC[AES256_GCM,data:PU829CMbDndRX19zHK70VVUQeCvRj2Kpefb83RrMFcY=,iv:ibnq0jc3dB9yuVObEj76o72eS66+ytMJxqfO+aejbMI=,tag:EaIZSYgm5mQ1looSdluSBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd1dWSTFpem5JODRvd0hH
            cWM3eGNKRzdZaTRZajcySjVHSElMMWdSQWlRCmNjam9DRkNEbW5JbUw3VG05a1JX
            eDNHbUpjZlJWd3lIZUJvUTFORWpyV2cKLS0tIDZFL2Z6dVRFUXJHemhFdVA5ei9q
            MnMrWTVTSEo1Qnp3eWpFTkhWK1FVNlkKpasr5z7nAtfH9e9eAOX8Lra89RKCyg2W
            9R3vgdHynWxHCdvQEYLsCzZLk0xIfOrOMBcquXmxhe4exgA9X/t6Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T18:45:29Z"
    mac: ENC[AES256_GCM,data:VYdi2Vmec5ToSptSOzJs5MbL2sIQw/f73WCzK6ulXerLtrywNZ2F3ROE43WL4HI+kynNjDbdzqr0tuWKf1zcBTCRP5uEo8u1uTlmTK8m/tOnjl3FzcxbomN7APqZkWj1Iuorpj03QMD1aYbKawRbvaGtNZPSN5du615c9G5SSdE=,iv:awUoE9HJjwizTzmssXUJ4WmDH4lis/mFn9bz8jzeOzg=,tag:TN4nNrHsyvTTrJA45Jg0rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
