---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - kubernetes_upgrade.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - oci-repository.yaml
  - prometheus_rules.yaml
  - talos_upgrade.yaml