apiVersion: v1
kind: Secret
metadata:
    name: tuppr-gotify
    namespace: talos-system
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:nuFp85+FwqDY8n75REdJh5Faf3MnW4jFhbXwivr5DYnGzkHo1nUCI0trMTKLZzEsb8mwInZmpTe3I9XXbqoTDsR1u0qfLG/53EtR,iv:ViMCnW4yk0sdK/9ohIjpjih6ZEZPQh2u9rX76fuDC34=,tag:pTCt2WRIZcVoNE4PPvo6jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVZWTTlqT21yNFBYOWhE
            cE9PRklHVkJzMCs5VTlJNVg4VDZkcVhPUkNBCkpIN2RhVytVdnh4QjhhQlEweVc2
            RlFxYTBDRDJXQklCZ2JYN0U2TXVFbm8KLS0tIDdaUHprZ2FhTk1HL1BpZm02TXlB
            cFBrZkM5WmRvZTA2Vm11dXEySk9iRjQKuK8LSBVpGd15Sy7ch2McCDjxb/vkfel2
            u5Ci+6k+0NZWMXt1E2i5eN2ZSJ2bStm8qTqxmzjzCoGyN8K57bLtkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T22:02:29Z"
    mac: ENC[AES256_GCM,data:sfkXnUfmBMGsCt1xcG0o3ZUituGSHpGVUUUKoq8/VEYTXbcqrg/kJHj+ixiPbxlLXgkdly6ClRqTtunIzEwkigSnzk1KGFBnubnPhWjNVlOCevPYssF7XxemT/SbIRMvbmXwhITkn2VGeBnd7zBWN0RNCNUQXr3C9IeXL/AtVjI=,iv:wzoMTZBadxxHQJzJV7Bp7zGGpbcUpwxSfscmIUVRGoE=,tag:JOy3eUBrTC/8NGRw+1PoWw==,type:str]
    version: 3.13.3
