apiVersion: v1
kind: Secret
metadata:
    name: dawarich-basic-auth
    namespace: dawarich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tEionfNPuRI=,iv:IDol5AFXQuKiwNI6n8V0v/8DOo+8yBMAwXMjpdIlz2M=,tag:7ki8mozgNNur/nyoEPwZBw==,type:str]
    password: ENC[AES256_GCM,data:zCYVnamkZkntxLSQK6RNlIOI/mHVhDlDEXRBLqGer/E7/NDqaYlL/IdmB3yrdMzjeQ20OJlJqyL059eXNPEAEA==,iv:smZ+yzcnWpXZD59g2J2B0HAxtC+9M2ubTNHy4GSm6ug=,tag:4OnGPbCOLk/buiw7DzZ2/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOXk2OW1YY0ladHFMRkJm
            OUlxYkFkVUhGcjI2NDdROGZiWU8xRk5vZ3djCkR4cGMxN2E0SFRTcVpQcWJqSXlH
            QW1kUzRCa3Z2aXp0WnVkTUJhSzBtM28KLS0tIE1LQ0ZxSGJUdUFHOHkxUDNEai9v
            Zi9RTktveVpjUkVrU0pza0RXVG0zOVUKiMwnWiIXcyEkhqS3CIxsWH11zdw2lI/G
            yfVmshT+NekVZVb46DVFbxkZ1khYnJH1qy2lPfPbpFrO4+YrlaiEXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T10:39:09Z"
    mac: ENC[AES256_GCM,data:Cg4ExnUyKw+ovagm2P05Wr52FqpW/6GWTIzoHejx9hjICpxxKAnAIy/wL69om2japL1iCwTeCxzuIjSQX3+IG62m+0h5HZZZAjXUa8nUl2RW7sE8z4ypqYvpVJkBJaw5ryY6/kIpkSBT6Lc605RZvhZSHPTZwDPzZpjtVdDgw4Q=,iv:M6hKKd7z/Wq3T4FCw3hDAJOKNeM8bWhzW4ftu3PR0AQ=,tag:/x/Z8i+lbg+R8skbVZKm9w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dawarich-postgres-v18
    namespace: dawarich
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:EWYBrot5+pvQUp3YsXXe14NrOT8q+CJTtG0=,iv:ym8Xro5XqhMqKDEkLIn6g1MD0qNlhF/IhQp24wOmVVM=,tag:muJvV7p0twfG0n+5Tvg/xg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:iARh+w1MV1bOXF32h6TZ5sMa1XnJuBkmn/iGTjtN0WESym3Y6yS/gw7FVfsJaAyBq9NPyAzLll9V+zMdgdU+xA==,iv:NI+oQ5EXzbK7LwRZAqdj5gnFNde6mieEt62cj0PWFNo=,tag:jmUfB40L9wyUtRDJZtwjmA==,type:str]
    region: ENC[AES256_GCM,data:SWOSfYFt,iv:FmBb0sb8cbQ/FpM1+bQzDxY/E2SEqmdgCmmk8cbkyWk=,tag:3xY6rrF06eP5xUBRsjrGDA==,type:str]
    password: ENC[AES256_GCM,data:V4hAN5P0nwNynMMAX9Mb7f8CfZihJXsl/4NzkEKk4lNxXLGhXXFGVASCBlkuM/0ZRm4ffItw0FA0ogF/WQCASQ==,iv:QFZqqVdl2BieFtCGYnxbKGlAPQORWRQ/e0kTlDftkfA=,tag:g9mQiYqVQAY5dLO7F+k0vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOXk2OW1YY0ladHFMRkJm
            OUlxYkFkVUhGcjI2NDdROGZiWU8xRk5vZ3djCkR4cGMxN2E0SFRTcVpQcWJqSXlH
            QW1kUzRCa3Z2aXp0WnVkTUJhSzBtM28KLS0tIE1LQ0ZxSGJUdUFHOHkxUDNEai9v
            Zi9RTktveVpjUkVrU0pza0RXVG0zOVUKiMwnWiIXcyEkhqS3CIxsWH11zdw2lI/G
            yfVmshT+NekVZVb46DVFbxkZ1khYnJH1qy2lPfPbpFrO4+YrlaiEXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T10:39:09Z"
    mac: ENC[AES256_GCM,data:Cg4ExnUyKw+ovagm2P05Wr52FqpW/6GWTIzoHejx9hjICpxxKAnAIy/wL69om2japL1iCwTeCxzuIjSQX3+IG62m+0h5HZZZAjXUa8nUl2RW7sE8z4ypqYvpVJkBJaw5ryY6/kIpkSBT6Lc605RZvhZSHPTZwDPzZpjtVdDgw4Q=,iv:M6hKKd7z/Wq3T4FCw3hDAJOKNeM8bWhzW4ftu3PR0AQ=,tag:/x/Z8i+lbg+R8skbVZKm9w==,type:str]
    version: 3.13.1
