apiVersion: v1
kind: Secret
metadata:
    name: dawarich-basic-auth
    namespace: dawarich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8jlQYn2Z7ng=,iv:dIFQaYx/zCbABlBqhFM/buYi2vudZ9DWcb7ChMRGMBY=,tag:mjUOsHM1YQyYFRGMr26IDA==,type:str]
    password: ENC[AES256_GCM,data:/WSDaL9oB0Y522gtaON+TU3qNWB2pxzjq9AXkGvas3WPfMqRcHxh5aL2+BXogiGKMSifz/JPOSfggqerqXxbkg==,iv:pnfGhlo26FaX4PsgmLorkJ9KoGrjBrVgJEwb9NkIEc8=,tag:V7/jWSeVD2WHXIUhxXHyGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3NaVU5SOGRUZzRQVHp5
            K1UwTVhhSjd5bUFpdlhzcHl5ZGJxWGFrYUdNCnRQVm02d1puVzJ4cjgvZWtQNFVy
            Q0orUGsvdno1K3JsejYyZUg5TW5hRmMKLS0tIHZRUjJaWldHQ05HeWdmd0dCTVZ5
            OXV1bDBBRm9TQURFSDEzMDlpVTVKOG8KlzApzywVbwh/NxgvuJVHBFO5PxWqmt4x
            yR6yPqK5/8T5jElB7iiIIQkXLOzgWaQdfWrtY6n4gsYlLmVIR/26jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:Z3bIXM2rXdegHfMYtDO75nydNhkxi8ime/Kq3qe6IVgrpaOozpVXU0HtmWKY9b1g/FZw+AVP6aOarGwqBOPjfBFmD93R2ZiRBwjR70hLwazP01rL7or3udYt3epArMVqRDupEBk/JXvvJlEvQTEN3Y1qsrIY4a9qbSMGVtJr36E=,iv:9eZc3M37OKHPjh7nrpT2v+eOXTiTfdcFYdqCmDptimU=,tag:ofBWLr+6wPZrTp5XqgDTvw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: dawarich-postgres-v18
    namespace: dawarich
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:4l+QIQnSb+24df8vGpoALv695sWephquqRU=,iv:QFUfAKkzxNDqmB3ftrfl0MzyNtf1GPfGiJtLx++FHic=,tag:JRingEJJUjvnnOpInrVV2w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:jYYS+WJqGo/ZvOOmn1Gaz+HkBAWsXz0kbONO5CnXrhHUVKFodEgmAYaSNs1HGt7oJGDn5rF3dJKZkGtMR431sg==,iv:Fe2hyjnGNsXW4Ld3MJReDl4N/79R7R7GLVgMb+oKNyo=,tag:8vA+fzPgKishmefv+hDgMg==,type:str]
    region: ENC[AES256_GCM,data:DIwsMw1d,iv:QAW0Qq3BJozce8peuccRLc8XnN90Sv7eMwKnymGrZHM=,tag:EgfBL69tHhISUXmAon/bmw==,type:str]
    password: ENC[AES256_GCM,data:4k6gTAdamnay3sW3HYLQYnI7FBK69jKNOGBMy/cLTk1OSxABAPN5oGU5hZcAX8s/EPcqN2HDQPL/fjx1i5pfIA==,iv:5rjtw+8D0zGJKN8PBxt8+eDOVdYVGSY8ckEqMbhVetA=,tag:DLiIIuzLG16HL0vaOS6z7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3NaVU5SOGRUZzRQVHp5
            K1UwTVhhSjd5bUFpdlhzcHl5ZGJxWGFrYUdNCnRQVm02d1puVzJ4cjgvZWtQNFVy
            Q0orUGsvdno1K3JsejYyZUg5TW5hRmMKLS0tIHZRUjJaWldHQ05HeWdmd0dCTVZ5
            OXV1bDBBRm9TQURFSDEzMDlpVTVKOG8KlzApzywVbwh/NxgvuJVHBFO5PxWqmt4x
            yR6yPqK5/8T5jElB7iiIIQkXLOzgWaQdfWrtY6n4gsYlLmVIR/26jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:Z3bIXM2rXdegHfMYtDO75nydNhkxi8ime/Kq3qe6IVgrpaOozpVXU0HtmWKY9b1g/FZw+AVP6aOarGwqBOPjfBFmD93R2ZiRBwjR70hLwazP01rL7or3udYt3epArMVqRDupEBk/JXvvJlEvQTEN3Y1qsrIY4a9qbSMGVtJr36E=,iv:9eZc3M37OKHPjh7nrpT2v+eOXTiTfdcFYdqCmDptimU=,tag:ofBWLr+6wPZrTp5XqgDTvw==,type:str]
    version: 3.13.3
