apiVersion: v1
kind: Secret
metadata:
    name: dawarich-config
    namespace: dawarich
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:m6KwCfu4WhFsT8ffiEuPjzFdLYV+eqkn/4GMM8vYojIeeycuA0sMvgOz4h5pUpiw4l7MAsgBp2X25IXQL33L1ywfkURmh6E+kltOLSZkrtwVuA/66mkSPuLGCWVcGQyxxCCMYKhmtbB4pS98uf+0/X1zavI05sF673qAYeRz2hI=,iv:GcWh4DKRRojbVsA3496mMgHpwTe3Q6csb6R1F3g3NGQ=,tag:kWftvtKl4OXekL8xFNA4tA==,type:str]
    OTP_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:IoIrKaHohCDlXYUh50euzF1R96MDy6aJs2qLI5B+jqJoKcku5Osqm03+W/jcPz4ur5HuCBKa9+Qr99u1Qjxcgw==,iv:ybfn0WYn8/KVVauEB7D2fzoRiHnG8CqeOm8ItCu/N/E=,tag:63xayZ7/kOOZ14FhL3QDbg==,type:str]
    OTP_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:yIs9hxNk5kvUUEuGeohFCgrJd1WWCOWJWWX0dsMs+y6lz+2kMlNeGhlct9P6qz3mT4g9u7Zit9c/tARzecQnWw==,iv:ofqYa5cn7wWmNN7l+8AMYM/gAmcDYnoX+J1AlFRGKKY=,tag:CnjBq8yg2c/oApxiW4xthw==,type:str]
    OTP_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:dlrfeh/5GkjDiEhiU6wCZXJkUJ1a6lTscBbec6pnMC3oN6SE/Wu5keX6YlVSIx4pw1Arbzyp+DvtXSHUgyUzzA==,iv:spv1/0LvUjqmlJa+Td4cKf4kQsX8NK/eipNPR5YRfeU=,tag:VETC34cGdIbbXebU1UcRGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bE5PT2x2VGxMbG51cUZ4
            L0RIaGI1WDROQnBxVDdzOEJ1RDNpZGpDM2dFClpGSWMrMHJxVlhrMjF2MVNEZWIx
            WXE4dUttUVQwRGQ0Z3RqN3NNK3dzM0UKLS0tIDA4MjBQaUZlMFkySys2Q1psdWl5
            YTY4SUptUnh5cDU0eklqZTg2dC9MTDQK3HScKYw3g1yjUaFv5BLerZFJd4S9N5Yu
            ifF35O5lvH54ZDKbHHHAdEdeGfzZ/mEPjy5gzuEnuzyFeTlxYDm2Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T10:39:15Z"
    mac: ENC[AES256_GCM,data:4l5VeoMyv9LZHvoRfRFnMrTZK07GQAf7u1BQr9yWJly5YE2Q3pirWWXfD8Bp9k07/Vk+JzdaoRSsA23Rqj5oyduhkBdQisdVaINpXMU7YOJo55eV1/doeiMIAE0s3DN4WJ15PMpi8FrWN5+K7DySgvaVM6eStYwhYtlpEahoWI8=,iv:IkKnxBbBJYU4rQQZnPRncwyL9AHXzuIYlEXnIYS0RYY=,tag:1dNpnGq4GUnJJmm9t24zFg==,type:str]
    version: 3.13.1
