apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-basic-auth
    namespace: paperless-ngx
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8ZhoDC0jMsfpHs9Y/g==,iv:a+chBJmNE6m2eYLdG/pNa3ANMIybaeEiA94WdgxLgSw=,tag:FOZ9ZTPDpl6wyhko+FkILA==,type:str]
    password: ENC[AES256_GCM,data:GyNSikraDvKBeLWjgGSQlF+iN+TyjyP+bFL7ATcBOVpNxkLgmqjEYIvrmnm+G9p15oXTv75XjIHyv061iCCtDg==,iv:sNMBN66Sw/u+iHtHRmTxi2lQRht/uTSR1lhgUEnJunM=,tag:pUlSOhLLEWSYF+pVS7QZSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSm9IUFdTMjd6QVlIckNv
            N2ZnOVZueHZsaHJuejVQdkVGZ24vY1BmYldZCkJvRGMzRmlJOGc4ZHVHU1p4VGpl
            KzVqUWlnTC9Nb3RVWXRmYkVTTlBIbk0KLS0tIHBRRzJoR2o4RGJvckd4d2orb0FH
            Z3J5Z1U0K2dwQW9uUzVxdUl4MVdram8KcNYbXBtChsMULeGg0zlOCYcI1bIkGoQ8
            clqQlnowV0NWUE2bcvnHxlqW3RZabTZNJAGol/7zI8ulO2BCckLlGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:SREOy1ew9vEatYpgoO24jip3AI0hiCPMncT2PEfjfZa5/oodHeWCMoI4Eff3Stux8pe8J0WCmTJrL5fdH0ZvNya3iryenpRdoY63UYDTqwUAd5x0uhsEbfmtz64dgHzLUfaA24HdtNTAbgg6MsT1OtgMIR8PjwMjGKo5cRKYRRY=,iv:N1kjCBD7awmzui011SWUJfN525YaC/+ffA5G/petN4w=,tag:OaZ8DgUv9xsAB7MCx2MrhQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-postgres-v18
    namespace: paperless-ngx
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:GllfBA8tX8yCODMSyNA66ko0U5jgGvgrY5k=,iv:RvDsAIHNpsVSTivyCiTeWuGEZvJCWMSJ4YEiXdW1fcE=,tag:VFSWWXH2vh8oBTUjIVK89w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:O8PPjUgSAwiX2/doK0Nh1jS/v5wpZm9AV2yBubZqfcLQq7dJWPFuc9dFKVUYIY68DyWSEpzw9tqPoKe/jeBgcA==,iv:xijaXGbWrmFHhBmpenMTntzWcnnSenXjr/r6n9obmNM=,tag:vjuwGiqV+jgXD4hdU2ci3A==,type:str]
    region: ENC[AES256_GCM,data:8JQMGv6d,iv:EtCGi4hEQASj3YJKCH4ACIeMLpywbk1BSq/+irIkuCE=,tag:RjXrBH01PrmFOkqakS18vQ==,type:str]
    password: ENC[AES256_GCM,data:VikXt6Tyruve9tywRNd45vO23qhMfmEYBcl9XX4SnbXIMSpSKF6F+2atIURTz0UJQClYiBBElCAToJI7gfdEXg==,iv:MBSfsDJjKwY7xHJ3P/AV4jG8ZWejQJ0LLuitL5QRIu4=,tag:k9RvDKsfSUgFVbU06IMeVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSm9IUFdTMjd6QVlIckNv
            N2ZnOVZueHZsaHJuejVQdkVGZ24vY1BmYldZCkJvRGMzRmlJOGc4ZHVHU1p4VGpl
            KzVqUWlnTC9Nb3RVWXRmYkVTTlBIbk0KLS0tIHBRRzJoR2o4RGJvckd4d2orb0FH
            Z3J5Z1U0K2dwQW9uUzVxdUl4MVdram8KcNYbXBtChsMULeGg0zlOCYcI1bIkGoQ8
            clqQlnowV0NWUE2bcvnHxlqW3RZabTZNJAGol/7zI8ulO2BCckLlGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:SREOy1ew9vEatYpgoO24jip3AI0hiCPMncT2PEfjfZa5/oodHeWCMoI4Eff3Stux8pe8J0WCmTJrL5fdH0ZvNya3iryenpRdoY63UYDTqwUAd5x0uhsEbfmtz64dgHzLUfaA24HdtNTAbgg6MsT1OtgMIR8PjwMjGKo5cRKYRRY=,iv:N1kjCBD7awmzui011SWUJfN525YaC/+ffA5G/petN4w=,tag:OaZ8DgUv9xsAB7MCx2MrhQ==,type:str]
    version: 3.13.3
