---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name paperless-ngx-exporter
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: paperless-ngx
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
      # E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    controllers:
      paperless-ngx-exporter:
        type: cronjob
        cronjob:
          schedule: "05 22 * * *"
        containers:
          exporter:
            image:
              repository: ghcr.io/community-tooling/oci-images/paperless-export
              tag: 1.4.10
            env:
              # paperless-ngx/paperless-ngx/issues/9609
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
              # S6 is just so silly
              S6_READ_ONLY_ROOT: 1
              PAPERLESS_ADMIN_EMAIL:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secrets
                    key: paperless-admin-email
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secrets
                    key: paperless-admin-pw
              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secrets
                    key: paperless-admin-user
              PAPERLESS_TIME_ZONE: "${TIMEZONE}"
              PAPERLESS_REDIS: "redis://valkey-primary"
              # Changing this breaks app-template:
              PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created_month}_{title}"
              PAPERLESS_URL: "https://paperless-ngx.${SECRET_DEFAULT_DOMAIN}"
              PAPERLESS_DBHOST: "paperless-ngx-postgres-v18-rw.paperless-ngx.svc.cluster.local"
              PAPERLESS_DBNAME: "paperless-ngx"
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-basic-auth
                    key: username
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-basic-auth
                    key: password
            securityContext:
              allowPrivilegeEscalation: false
              # E: List directory /var/lib/apt/lists/partial is missing. - Acquire (30: Read-only file system)
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - SETGID
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 300Mi
              limits:
                memory: 4000Mi
    persistence:
      config:
        enabled: true
        existingClaim: paperless-ngx
        advancedMounts:
          paperless-ngx-exporter:
            exporter:
              - path: /usr/src/paperless/data
                subPath: data
              - path: /usr/src/paperless/consume
                subPath: consume
              - path: /usr/src/paperless/media
                subPath: media
      export:
        enabled: true
        existingClaim: paperless-ngx-export
        globalMounts:
          - path: /export
      run:
        type: emptyDir
        advancedMounts:
          paperless-ngx-exporter:
            exporter:
              - path: /run