apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: paperless-secrets
    namespace: paperless-ngx
stringData:
    paperless-admin-user: ENC[AES256_GCM,data:JfxTyQ==,iv:5+vihH/3e96KId3GLw060uuZzuqCOBLEH7jD08nOCLw=,tag:f894eW8ZnA12S3ac+CGCOA==,type:str]
    paperless-admin-email: ENC[AES256_GCM,data:0JKUdxiLKoU83bIJHYgLu6R8htvKsw==,iv:P1H9wLTFG4Zl5RSjwXZ1oZXAAai6xoYpk0v+ljEzuTU=,tag:B226Y24WIViqwHhTddEZ7Q==,type:str]
    paperless-admin-pw: ENC[AES256_GCM,data:5H7yEno040SIqh2tJh44zirGsfrUQauQnrN6NzrY20TeNVxaOlE+9hEAOq4BGT2MB+HLf7lgLbUtYcOw1EYEkDQ2d9L0nZbzIoWRr54REdcxH+UoVpQgyXXIrxlC18xcC98TGGGUmrrY9glODXFZDmHKc/Fe9dFBHMPJsKyekVk=,iv:lgD65eUl8F17i37JSuighl2RFNPah9DtLMxLNzjE2k4=,tag:HHfvhfmKHS4YwbOUCue4WQ==,type:str]
    paperless-api-token: ENC[AES256_GCM,data:iijdjn0ae/R3I7jD8BEt8TQICXrVbCam2fN/DIthnHIeAG7MtaOzLA==,iv:V+i7IhtpD/wP965OS9lf1XugxQ0N1bZrAAJGZeo8K8k=,tag:IhNcxpILHAETsnuZ6cAhzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZTlIRURGb0o5NVhON01o
            TVBGU1FDSjFIZDdMZzNJZVk5VzlZK2ZvMWtFCkRiejY4RTlwTG5TaEpmK0dBOEdS
            NVYzNlVRY01yR3E4NmRrc2VJVXlwcGcKLS0tIFc4SFE2WmJwUkg2S0N1czdpQlkr
            UGp4S04rYWRCL1gyZ2l2N0lrTkxDcDgKSg2MAwtBZ3NYrmdYzrdJ8JQyaNiWj/lC
            hR5+OeifvTUHbJ2iNHbqXQyiaoS5ClO+vUWSU4i2ibfBAcf6pQiPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T08:51:44Z"
    mac: ENC[AES256_GCM,data:LqQe2mAledMLpVPBGipMBEloECAVVhFbttQLv+LIgEJyUt1+xZFgQJ9h00ejXX5UFfAbUzrDenxQRWduZ4bLN8l5LOHot9MBDppfo/j3Gwki7pX8istwnFLMexOik8NaNJQO0ursLlSDDzEYEy2jfGU8M6w7wEFnKRdzZtEoJI8=,iv:mbysJbg8XF4tJkYVaJjk1s+CoubKtNQNBNIpZqfF1n0=,tag:m1nw1SVE7LpN8z4MSN4fsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
