apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: paperless-secrets
    namespace: paperless-ngx
stringData:
    paperless-admin-user: ENC[AES256_GCM,data:T56nEA==,iv:UTIlbdJd7b7JzteefKlv1McX3uqaqkUxVVF7U0KkzPg=,tag:5iYsZt0yClG3FRPITeigsQ==,type:str]
    paperless-admin-email: ENC[AES256_GCM,data:euJKq6YDn2te0TMTGc1eEuN0tXUX6g==,iv:UeXDDuvXAizc5hf69broqXUe/NC+nGBOts647TNtvO0=,tag:QopxksQKCcYYVGbjWKDrNA==,type:str]
    paperless-admin-pw: ENC[AES256_GCM,data:lREYC/FyWQq/xew9EirHv7uMZNbuduteCZpnBooMxi8tcSqKJUYbZmAI3hWiJ/hl7T1Ma4VdHkTQXT1j/Yln3WxOXbLZAj5K1jzTBDdtNECRxqvRWKzA04dCH2+6nKWuAshgmHtMuD5U/CCqF3qrAYV6DfLG8TXvSJujpISN3Xo=,iv:VfDFez5tz2I2hSoAYgXjXFiBiKMGrDtsxEQR2W3t6uE=,tag:7sz3xwPiitUz9Tx0LoqTMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMHJEWjA0ZEtmbzRDaCsx
            ZWlnMTkzYXpzV1pSZ0E2aXRZRm9ydGZGM1dBCmJVOE9YeVM4MmRYTU4vS3pLNHpG
            dldxSnlIdld1ZGt5anVNeHpteGhNbHMKLS0tIDBTVzEvQm4ySHg2cXpOc1llQXJH
            Wkp5d0VZUHBiTHpNL1c4SFNuTmRvZHcKpA5bDBLihqFyaw73uFj7i2BaukP0lw2n
            N90yrwKehXmXfYuveUqnU4YPcGYWgHDVkdI8UhmraNLKyt3LPi9Qsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T06:45:23Z"
    mac: ENC[AES256_GCM,data:88JcFYz2sF5wlQ33WWS3V4cx2Gxw0yAxf8iOCTSZKrSzHWSDAnM8YaIDr8zcGaWgL7CXEJAXMbNnn2ip1QD8jX0VrbBNlSUGF7NcSeci/HaSepuT7B7QSviJTP5XejkS9g5oY3k/fo9qqJ+ZcZwTRKNqKKDNJ6HgKiutDwJ6NXY=,iv:Ipmmn40tU7EF27EojrtncBCmfVKhujAXQspA2fj6UXg=,tag:rZtZ6qrlR+PqqWK6xSO/5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
