apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: paperless-secrets
    namespace: paperless-ngx
stringData:
    paperless-admin-user: ENC[AES256_GCM,data:64WHrg==,iv:4N0bRtJeO5vtGZXMyur0w8a6SNkMoy/bZFwEl5RJHW8=,tag:dUUBWbMDAteObPQHRtTapg==,type:str]
    paperless-admin-email: ENC[AES256_GCM,data:ptIXrxvucq4Qpov2FvdUqn9ix1Fvxg==,iv:gq44YTdJmvtnGm4hjx9WboKRaEYeSTVRweqReQiz/GY=,tag:hbpc16Schk4DXO8adXa4jA==,type:str]
    paperless-admin-pw: ENC[AES256_GCM,data:udfyFAbBIcuqRVMZgt1Zi0UBkMGl2xfuT2wHX09wcSvZQdTcmb/tj07vHJd2NJz5a05cicJWRCZHBbm8ZRe8j7GVVO/deAygjgoOR92n38WyWS4yrNPvAaYpPLH3t/SRIkNvny+AdNtGx7dihfbVkRmc4WVlUfpWNoZTsU/I4Hg=,iv:Le8C4n8ei4jdr+pj3tkeS0schkbS6Zs6LZ7zF7GT51E=,tag:MsfNVJwRlEFTMVZVrQjO1w==,type:str]
    paperless-secret-key: ENC[AES256_GCM,data:DehAYegOgLzZQP7utVwAhJuqVhjguVs2jNPFKHCEjWYx/N2OHYl1EPCRXvJIwYFn41A=,iv:S7VWGH0EfnpENzloe7DKjXL/gq/ji7Erz1Feq+OJQTw=,tag:aTeE20fVKINqfXx+Q0dDAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdDE4emhmMDB4clREdnhi
            RTI1eDc1UFZaZUdmY2EvT1ZBZDJZU0xydGlNCitVOCtTN2xuSHFsc0xQTnAxb0FZ
            WXdwaTRBR2NCRitPVmNSa1FTM0FBd2sKLS0tIDMyenZPR2Vub29kUmNMbWN4WFhv
            NWNKVzZYTTRYRnR0MFZVbE1rMUJ1NEkK6bu6bu+AwAtJzlzXxoNx191yFToRwxLU
            W6HyNgelybRTATBlfk3+9D+o2IbShT57xmcGcBwenIrpWS9h+QuZFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T22:19:35Z"
    mac: ENC[AES256_GCM,data:15rjTVdljGYHnxtf+ga6EJNJQZ2XpIGOCT6eT4mvMIO6M1ZZyGq7kY2VoKDF+XaeHnAwJoS88l6R1wD7uD76egKKsPGxh9K+ltv2+CBFsyOcWcyvxcrOLIp30DNxW/xBo4605oZQnixcqqJThdmr2ANOSRqHxCWjIGiIXsSvSB0=,iv:mqutBqdaQB1w/+l6G+4qKmBzI+tcNB2hOLwkoRXcMh0=,tag:7ipJv08CDHcXigUnw0FO9w==,type:str]
    version: 3.9.1
