---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name omni-gitrepo
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: &namespace flux-system
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    resources:
      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: *name
          namespace: *namespace
        spec:
          interval: 5m
          timeout: 60s
          url: https://github.com/siderolabs/omni
          ref:
            # renovate: datasource=github-releases depName=siderolabs/omni
            tag: v1.7.2
          ignore: |
            # exclude all
            /*
            # include deploy dir
            !/deploy/helm/omni