---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack-crds
    namespace: flux-system
  targetNamespace: kube-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 10
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 10
