---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: prometheus-operator-crds
      version: 29.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 30m
  targetNamespace: kube-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 10
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 10