apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: searxng-config
    namespace: searxng
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:JgTBvxLgqorOwKABProHYbmFyC//cokp6subSaVpqzvZ+0Yt2b8ibMbtvqyzAHN8gqbzXO1z1q3CthIByP1dLQ==,iv:3+nzjUTq3Okwgue4Nf7FlnoPLlf1v0wBCcJ2m0LdkoY=,tag:YVWJwto9R2rV3Xie4ltWJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc29BWkVMb0trYzJLbDRH
            NTNCT1JxNTR0TWY4R29BR0xabnE5TGVhWnpJCmtQMzB1QnhaU29hSTlIYklmZ2VE
            QXFFSUk0MlJJeWQ2YVhmRVNuYlp1ekUKLS0tIFJFOFJRaDFxdGJ4MU05TEF4RU0r
            THlTRUtMR0xEVFNzK1E0c0ZjMkVKcVEKYwK2TBTbvlo0tgK1F5kVDoddRbHbl+Wm
            Y87duEO2UXyp44Q6ad9wJcKJKUXdJuYkuZOC5g7Y+bE+fxKbuopTGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T19:30:23Z"
    mac: ENC[AES256_GCM,data:HhjM+NHlMcKBu4yLdVFfnRbZG411JPKs3cJ93oQYdwbAdxeC4byDsHzrFkSZpOhZweJzLZ35nyk0KL8h3SiNIw4SNUy3Esf3SzRnHHBXX9fcqKOcJ1mmIac3I/vSVNhFx8K6jd8/in7752VaOXYllZGzU7TceWhbjybIE5czLE8=,iv:Zh7QikHpT9GrdvegNNlHj7FSTdizsMxUXLlIqKaaLhg=,tag:PFOnpcJnhgyaJ5whzUkibQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
