apiVersion: v1
kind: Secret
metadata:
    name: seerr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:oLu+r1c=,iv:7p7uY1ZcjErcHX2n9ETe4AokxJ4vrRnTf0/BXFYhq7g=,tag:25dA7idioUVvsIP9PZVjqg==,type:str]
    password: ENC[AES256_GCM,data:3kmUWTLxNXaQVJIoZHFU02WzYyMGGDvm5R6pna3ca0tK4E8rC+2724yF75+MDkeIoawMB8CpIgS11LzW6MXq7g==,iv:NB3KA4HOPZreB+ru7g5YCEda3Y/8IjJo2pQ6rqBQXUM=,tag:+s6PaXbBaRqgTm+i0mPPhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNFpmSjBWbDYyVi8xc2ha
            NlVIM1pTLy81OVRpUXNlRWdrMGlxdnh4a1hFCkZsKzN4RE1QYjJTYkk2ZG95RHNa
            SnQvanpFckJoNTlVUkxpYmRTcXJZSlUKLS0tIHJTbS9HZkJIdWNSZ0hnM1QxTHhi
            L1d6aXkwaUJoR3FUQzkxNFhYWDNXVzgKd7jbMgXAZ11W0u4+y7tApn1jpwT8o73q
            oQ1ZZ3aKtg+lPt46YUBg1wbWGQPjbN2o4BCTxbWLxHZUcJzxTBoPUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:s5ZHbqdE0xk2ay9DOCNZbPW95bDyZn+IyhVNlUV3e0MkJxQcxTYBpCU5WBKRSvLp6dQyNqoXHyVFTh9IsAnY4cxB5M09/dkw75oPh7h2QFshkXCBy82J6GFBG7eFV/I7qBI7ac/dkQCjIvPn32viq8gMszL8AWHxBGxx5jhuV+Y=,iv:n1pCdHgDiIcZF7H9vuy+LAu/KONF90Hfd6xGI8owG38=,tag:ydQG1JNN8yaFLVr9wFxBEg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:G9KHJPx7u0tf/0zeesRUgJ44gSoqcryw3SI=,iv:MKD/Z8K6kuS8ImG2JV26aXb+8PhGKFtoFqb2sfooSik=,tag:G83RiXfCeJClfynJkuzmdA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:W3sNYcxLiJt2/Ki9GqJTR6aTGvir65uwL4jEXpy4QJDNW4/7+sFOyucPprM91iNfT5kMfcnGRKRVTxYvMvZF/Q==,iv:FRpkSV0eYWkzBbRDAC3+BZdXoLQaqDlQ/7zy35/7sxs=,tag:VqO2F8DIDJ5uR93X6SwqqA==,type:str]
    password: ENC[AES256_GCM,data:ED90wf0eGrhwOFeok3YRP9x/tD2cRQfaCe+NmdN/veI5GVTeYDDp+F/TRgoDZNyXImLMw4usFhbuTbnuKCprag==,iv:kNzQw/FNrKhunamG2Vx3HTmjsBPLHNL9uJbDC7ixKJc=,tag:hrFYTh8AG5vZkC7Xb9lU5g==,type:str]
    region: ENC[AES256_GCM,data:ddnDS7lI,iv:8xE6KYB8zhOR+7/1SLImQ4icUbQ633rX/MuiWR65yHQ=,tag:uOxu77jq5rz38OtnTnarvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNFpmSjBWbDYyVi8xc2ha
            NlVIM1pTLy81OVRpUXNlRWdrMGlxdnh4a1hFCkZsKzN4RE1QYjJTYkk2ZG95RHNa
            SnQvanpFckJoNTlVUkxpYmRTcXJZSlUKLS0tIHJTbS9HZkJIdWNSZ0hnM1QxTHhi
            L1d6aXkwaUJoR3FUQzkxNFhYWDNXVzgKd7jbMgXAZ11W0u4+y7tApn1jpwT8o73q
            oQ1ZZ3aKtg+lPt46YUBg1wbWGQPjbN2o4BCTxbWLxHZUcJzxTBoPUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:s5ZHbqdE0xk2ay9DOCNZbPW95bDyZn+IyhVNlUV3e0MkJxQcxTYBpCU5WBKRSvLp6dQyNqoXHyVFTh9IsAnY4cxB5M09/dkw75oPh7h2QFshkXCBy82J6GFBG7eFV/I7qBI7ac/dkQCjIvPn32viq8gMszL8AWHxBGxx5jhuV+Y=,iv:n1pCdHgDiIcZF7H9vuy+LAu/KONF90Hfd6xGI8owG38=,tag:ydQG1JNN8yaFLVr9wFxBEg==,type:str]
    version: 3.13.3
