apiVersion: v1
kind: Secret
metadata:
    name: kubevirt-manager-oauth
    namespace: kubevirt-manager
type: Opaque
stringData:
    oauth2.conf: ENC[AES256_GCM,data:l26Ywd67j3mnmNzQ/EsCpjef1YQ3BTef200hPPP+08JiVBpgnmn9AhybCOljxC9FuJHHRKrZu7Vf7iYuJTo5/HTUfDtA6rrOefay8azSdOk05eLFpdTspmwyClWg78rN0z4GaXl04kRj4LvXiV5sbjMTQ/cq1gXFVtLAbDOoplWh7YZI9CziFHDAAIY+xhUSfZ78nNigx0UDa6VJLsb0lGTKOZ5ryTsYC9TKhpdPLnxugISvR16X/gsuXaBawYiL9lZOiYeAYk8LEtsJyjGo6RikaSJduWCtYbtH/hn664UHpcvQuobNMv0w9Yc+esVdD74YqIshNICx70B73227ySqTErlozDbE9n0WNTrExoK4dYc0JsLsP4VXb5Pf4MMs3D9HnLxJgE6N4qD82ZnGnb5J+O2aLgxNj8b92UCLbWXNKk5W/5yfK+R/OL+qLlbFj/ir0h5foHDqp5jtVTs9ceWY9Wpeiexn9CxuZczQvoqm9dYPwLH/921TO9lPPmz2mbRz4fkitqdh/wuS7G+xT9+FSGsNG3y7Hut1D9ThUxQpoF/P2h7WKJooj6F2T7adZTwoapeU2SokLPiDm3vE6aNH4R4c/tqPScaMtm4FR4KZLlT1kOgaAEJ3V3XO1oC9eO6Ayk09/2/S99F547KJI8tud2eJf2RckhAn/lm4Zsg/rdphLGDBBHCwlcWyVCSqUVl8FX3oREieWnGtPD22WI/GLJO5poSL20MiPemUOWQ4u4YV1418fMnjy3kFKF+ZYSNl9CJ7h7bILyJjr2/wApPOndK0Jf1ZvrmTW12d0BZa75ef8tuSthHu04Wtrq17QV8+WqemYlPye1B9XTQo6z2FGJaEzP+i3d/A6uuEPKkSVw3XlIlwY70CsxPQajj7XCsjBT6paEaicH2Wb8qM2D2HZVjnuBntQeaSH0qjiPicuQlA2tUXxGY6kQZw5TXHtbEcMtNC2Y1Z2lb2edALt/HMjQct7wAq0nlo3uCHAW7O9oLSpN4NQ52/foFiXEnW84L4kMbWtqxxvIYwyxKq3+MpyFEzPWpQo1Y+kQc2iHqpWI8o0mFy6QwHhlA/TzUdQM7ZM815w/edkHbmPw9ke7rupmKTvCZcwOba1uVtb6rcR9gDksFLhlwp9oN8NUuv4qRMNvQvIMgxC6l5usgbDR3Sx2jds7PneDpC+VBMhhHZmtGHuWu0JNkDOgtaJLTNna/p2vgifRfBLuk3ZA3rHvDeqcLixEtnmgcq2yomvnQuCj8fXh7AS3pFwG1/sfaF+V4tSbySX20VJ7oHfqhAYuya6iZncffVW5sJw+h/UAz6CDTOujrTvLpX6u+aztjcX5VuA4o97Z4c/H7zgPjwGefwh0PS9OblFEx8751YnmdvovmjRy9d0Ywc+WOevnU+OhwA70l74esH4A==,iv:fb0JKMkcc7VWfOXe5S3suPLD/TL1Z6xemokKkIQNops=,tag:vdx6qwHuwMg4flPS5vWuOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SVBUSEg2WllqZHVWbFZj
            SW9JTHhxeElnMjQwMGdxQWFRZzlHaVE5TlFjCkIxSGRQajljSTY3S2xiaVRGTlBQ
            UzFhbkh1SjNTZ1cyTUUwc0c2WGRtQXcKLS0tIGxhK24zUlhHZ1FOTlozYXFkTGo0
            bUZjTHBsVkpMV1ZSdnhSWldDcDVVeVkKPYzHgZ1UY7cWEHo6DDW1qk7CJqyc/ZN5
            zB+a9fzKM3UDElectRWC/hSNcr4T0zs3PeWiRr3NKo8PBQpDRFmASw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T10:37:48Z"
    mac: ENC[AES256_GCM,data:KLtDy9jENC7HjJIpp6qrBrZLAulpFqyKeZuXLfiZdpARb0D0iI23mPCSp6x+ZGpd54ltDdISu0w+wK+owbx66s4YqmS8URjh4SzVVJxduxYun1fOuj7bixDaUV7dj8eTA6wkAGz739+9048IZg0MXIxd/rLj7SudPwtZgeUEBFs=,iv:5ldVg+hHOuGZ/KZZM/xBRZsidCGMudfg9BmuASBbz2E=,tag:6HEmoUtkB+6jwlYSwVIm9w==,type:str]
    version: 3.13.3
