---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cloudflareddns
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: cloudflareddns
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      cloudflareddns:
        containers:
          cloudflareddns:
            image:
              repository: docker.io/favonia/cloudflare-ddns
              tag: 1.16.2@sha256:bc53b40b13c8b2a84e9b93c21f65fcd7d574b741014fb93912eb9efd93015aa2
            env:
              DOMAINS: "ip.${SECRET_INTERNAL_DOMAIN},ip.${SECRET_PRIVATE_DOMAIN}"
              IP6_PROVIDER: "none"
              CLOUDFLARE_API_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-api-token-secret
                    key: CLOUDFLARE_API_TOKEN
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 100Mi
    networkpolicies:
      cloudflareddns:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to: # Cloudflare
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                  - "${HAPROXY_WHITELIST}"
              ports:
                - port: 443
                  protocol: TCP
          ingress: []