apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token-secret
    namespace: cloudflareddns
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:NeBp1Q5x+OPVEXWhVD7CAMWKp1t8j0zKPWoTbqeH7Wp2fgbtRUP8DA==,iv:Hrlz2fIFM8hH+TfNQynqzwflrTUofJloKSOYFQjJH/U=,tag:FtfjUWZ2AjhLvFBkWNslEA==,type:str]
    CLOUDFLAREDDNS_HEALTH_CHECK_URL: ENC[AES256_GCM,data:w0tKyk2nRdhkLLKEkFZD0jE/Rs1WqDi+qWpz6ItR/BG73J/+U+044OtPyZvxVp+IuhidurJZQVlyK1QM3D0JnT8wAZPVdA==,iv:x97lqQRsIh6HQVEoGYns4JJFq38A414ZW9jvNLQ62bA=,tag:R9N/qpnUBQCahzyR8m4OzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YmgyeFJSSXcyWTRhQ0tm
            MndOWFZkR0lZelUxSGdIQi9JNnpOR1h4TGswClNKRGNXcVhJd2xXV1RCbW9Ea3VH
            NDBhcFIwZ1poZmVmVXczTGgyOWp6NGcKLS0tIFFWUmdCTFBuYmRhbUNMMEtHOTlL
            SktXWGlhcGozeGdDcGFjY3VWV25HR3cKt/CADtc5aq54Lls6AjV/Dszt143mSjZt
            yA5S7Ydr0KOkQNTKd6y+b/+/zRJn/rv2zvtvef3JT2UzhjNdn3GL+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T08:42:15Z"
    mac: ENC[AES256_GCM,data:jfFAnHe6b7ZHSVpc07YNa9GEWZDOF4AzIIVT8UkaUOWLn4HIwg71qTcmExZDqxxoIdq/7fWgRgAu+jgFZb4rbI7+J6mYekHftjdULBnz7luzLXtw9CbrSbdeUz6VBjW3L0OSRH9GrazXhhztnYTQdFKbnkNCZbG0NBgWkpPOaRo=,iv:/Cuhzt8HO304FXtbIQVvsjoH76KB/mMkbJHpy5cHhwg=,tag:LNTVYzOOVb39uivVg4L63w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
