apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token-secret
    namespace: cloudflareddns
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:W7KKBkmGKKyF3yzdeK93WBhElgEemIlduDqlQfQZ+szo7K+vdXNeXg==,iv:0kBEi/YIOW6VrOiKm2EtFUgOPEOi/hBjfULNadyc27g=,tag:kwiVOM2J5hGxCUWygo4ynw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVHFUUDFDclRCOXVveHZl
            d2lRNm1wUHJrQnBLSU8zNklNQ1pWZzMyVzM0ClpOOGtKOVN2eHNMeGh5R0JNclVB
            akI4TWlHSy9pS2pDVjJ4Q2tjZ2xwUFUKLS0tIG95aFY0TGVhVjhKNENLdlF2TUc5
            WVd4MVRTMVRzd2cxNnlndjhwN2NtdDgKCa1QHFbVUW2UlmgVcDtLqrw4j5AD0kiD
            v1gEwUgV9iS+8pk3pMNxcxoMACK5AW/OwBMC4qKglsClTLQUmKebHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T19:39:18Z"
    mac: ENC[AES256_GCM,data:0TaRuxsCA5joTQ1wvvwc8ZP5HbcKPSM4iH7iA+cz/3XsW5vY0NLC8xyX00VNa5CYg02YbiVoHMpdsfpqPzQHYor0mwo9kUkdk7Bnh28mMzwHjmGa5ol84d0oyp6fFBijL1Sqw/nHtuufWx6zEtIlzCZPFJOW3u0ZuSbhWf9MRUU=,iv:2YChMauNXSYBEpTB4KUl84j6SJg8lqvz/yXEdNSX21k=,tag:eLykOpe1m+0qWCKWjPT67A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
