apiVersion: v1
kind: Secret
metadata:
    name: multiscrobbler-secrets
    namespace: media
stringData:
    LASTFM_API_KEY: ENC[AES256_GCM,data:GL1QH/4JVifKIQgXgCKDupheFUGP1EaXfnOLeLqdib0=,iv:dBdPqNkOYUSlfid62eJ0RTtyORPx0XKoI2gNtfCpfz4=,tag:vX6xCHK+UOKmdqnGgMXtRA==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:/Bas0MizyXDfxjHO7YvuGIl85vT1IuLyFs+sqZqwodo=,iv:+wRhda9EX0fafG0BmMcj7h4ncWqQwDuzWwkouW29xIQ=,tag:ODNl7/NGn08hJYochgTGDQ==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:7j5YIaUfNjGCxkBHYu8HZKEEMraUcBwpOsKAHjSo25Y=,iv:EOtAfiDMfpcyv+4aspGeSApmjxmm3OOtxIknn1ZPrnY=,tag:tOYqMxT0VjRbVxeNf6f1FQ==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:UCpHjvXluxE9BLHU6i4z/uw8nplWXBM11JuFFfNRUTA=,iv:IiD8Wj4iPLLIpRRk3a4SXW7htS9xKCiG1ueqT0+epPo=,tag:LzaAtAGtXOJIDXMr0eb2Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTFRhNUhKOVRtWHJhb04v
            YXNyWmxaU1VIbXNvRGVlL0ZLK3FybTZ1TWhVClJrc3hrZTh1a0JtOE9HczhkODVm
            dnNUQWltUUNQcEhMUnl4bnlueGZzSFkKLS0tIE1XckdtRkJZNzE0d2p3VGdWTlcr
            ODZlcnZYcEE5WVd4TER6ZFZpeVVMUFkKDDcpzJKDQ8s8P6pmNaDRjhTidfXWzTXQ
            7/22bs5z/gil7Lo5UCFqXBPJV+8pH/QSyCBvHkzuois4FXGLALPmEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T14:15:31Z"
    mac: ENC[AES256_GCM,data:Hs33fyB3ncZQOAAOEUFxak9UxpeBZdoIL8KuAf8j7sFRlUAW/zZe0NrbIU6KFvrCsM1sXhaYOvCEzf2Eu0tdmicTCk6s1A6YWskLkEJ59xz83VdDaDiRs55UKvfEWcP0DVTOjQVPDjuBczPT65fE4WYUQ0dUcXPEoRvxmZvbc68=,iv:dL5cF8J99mDXA7EDyXLaTC4PJdtJbPOA08lDoqHWT7U=,tag:7q9VZlg3vMY5YauYZUZ8cQ==,type:str]
    version: 3.13.1
