---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../adguard
  - ../alertmanager-dashboard
  - ../audiomuseai
  - ../awx
  - ../blackbox-exporter
  - ../browserless
  - ../changedetection
  - ../cloudnative-pg
  - ../cyberchef
  - ../dawarich
  - ../descheduler
  - ../endurain
  - ../cloudflareddns
  - ../cloudflared
  - ../epicgames-freegames
  - ../firefox
  - ../forgejo
  - ../freshrss
  - ../gotify
  - ../grafana
  - ../hermes-agent
  - ../hermes-vm
  - ../icloudpd
  - ../intel-device-plugin
  - ../invidious
  - ../it-tools
  - ../karakeep
  - ../kuma
  - ../kyverno
  - ../kubevirt
  - ../librespeed
  - ../litellm
  - ../lubelogger
  - ../mailbackup
  - ../mailrelay
  - ../mealie
  - ../media
  - ../metrics-server
  - ../minecraft
  - ../neuvector
  - ../nextcloud
  - ../node-exporter
  - ../node-feature-discovery
  - ../node-problem-detector
  - ../ollama
  - ../openwebui
  - ../paperless-ngx
  - ../papra
  - ../reloader
  - ../remotebackup
  - ../rssbridge
  - ../searxng
  - ../smartctl-exporter
  - ../speedtest-exporter
  - ../spegel
  - ../syncthing
  - ../tuppr
  - ../unifi
  - ../vaultwarden
  - ../volsync
  - ../wallos
  - ../warrior
  - ../wastebin
