apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4I0VDtr2LBE0,iv:K8k/yBNNEHN0f8HNzTMK+KXINhttvbLItouUqtuo8R0=,tag:oS/OhXam9CwKSZ78XEHFeQ==,type:str]
    password: ENC[AES256_GCM,data:zrsLYCXH80FgUijJDdqTajHTBCpRJXqg/Pogn48A20GXC1cH1NWVOZ3yteXFJ/SV4/l298mLB+l3qF1ovdpKEA==,iv:tWgpOHmvCpQHucpdZnkTvMxt9hsMSjLKyA8FL7wA1lw=,tag:gfzJGBxm+elZaaNbYC1d3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNDA1ajhabnVPL1hUem1H
            d1Zqek1LaEFWQXRnZEVkSGZ5K1BCelQxY1VrClN5RUVpbVdLOHRmZWk0UVpMM08z
            YkZjaFREYURFR240QWRyd2E3ZHRjSkEKLS0tIFFiMG1qOXRBTTJsblJNYVhQenRG
            MnB6T0RwMGppVDJScGlZQS9qUG5xZmMKPoJq2S4FKhwiJI/nn1TeE2PA1OQaBnlY
            y/L50yz/hARDAJMdmDX+Kiplc9t7nK+rsIOJHJUNJPynAwV/uuzTuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T22:06:23Z"
    mac: ENC[AES256_GCM,data:+HPi/AIoJ7+989Q1DhnQMKFU5dgbU3+Xut6hqRWBC/AnRrEeFkxh5yC2XFiPqckHN3pl9sG1Bo0Qb5B+JtsCipQPTkbSZqy5rBYcX8MK1lR9CGRIZVg+oNTzHf/XdW13B9WCxRZjhQAQZ/5jjMRXwFxfg8qDApq0+69cR84hKQI=,iv:KzSfqI+5syGtEV5b+irz0s+dKI3koyNfh6cd9F4lOso=,tag:VAL+NbXP3Aum8tgXSPl7nQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:4g5ZW71pTUabf6VAE/68pAaD/lsiMdklLCw=,iv:aDQXymWolBOuFAzplUpSp7cG+YHVDAu2QuF+yfOLndk=,tag:8d2Ghh7ULbfZkgKIvBmTag==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:h8Ha4FmuJY/+oj/ERofqTOGpaDZLi86kN6kZe0wELGYHzRjEYGWEPfrz+5oJFXS5xFw/XbgtYhB0uMxskV2IhQ==,iv:P4gy83K3tnq167zOryJHQI5yWQuZCnRHxDrR/6XOz8s=,tag:T3IFmDQ0AYz6f7HkbaOTwg==,type:str]
    region: ENC[AES256_GCM,data:gdiCq5QR,iv:dChtmUvhRdn+O71jwc7Bqqjoe+8Rvp3xbCcwh05g8os=,tag:krw3jzvkVAOCsRsxXm0mtA==,type:str]
    password: ENC[AES256_GCM,data:RWAdoez6YB7bpnv+jTLihBCV54WNjbwblz1MZn1bHevJkjwhTxh7AUalVXks8Qsd/jo7cGZsKJImL1wmkuOjKQ==,iv:V3FeZhgtuMQYyflGBtfV3LD9KzgL9IdsVxTsY+QKphc=,tag:2VFw1Fde//2lqhWMBgM5Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNDA1ajhabnVPL1hUem1H
            d1Zqek1LaEFWQXRnZEVkSGZ5K1BCelQxY1VrClN5RUVpbVdLOHRmZWk0UVpMM08z
            YkZjaFREYURFR240QWRyd2E3ZHRjSkEKLS0tIFFiMG1qOXRBTTJsblJNYVhQenRG
            MnB6T0RwMGppVDJScGlZQS9qUG5xZmMKPoJq2S4FKhwiJI/nn1TeE2PA1OQaBnlY
            y/L50yz/hARDAJMdmDX+Kiplc9t7nK+rsIOJHJUNJPynAwV/uuzTuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T22:06:23Z"
    mac: ENC[AES256_GCM,data:+HPi/AIoJ7+989Q1DhnQMKFU5dgbU3+Xut6hqRWBC/AnRrEeFkxh5yC2XFiPqckHN3pl9sG1Bo0Qb5B+JtsCipQPTkbSZqy5rBYcX8MK1lR9CGRIZVg+oNTzHf/XdW13B9WCxRZjhQAQZ/5jjMRXwFxfg8qDApq0+69cR84hKQI=,iv:KzSfqI+5syGtEV5b+irz0s+dKI3koyNfh6cd9F4lOso=,tag:VAL+NbXP3Aum8tgXSPl7nQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secret
    namespace: media
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:vGm4bsXTnbuMd7na/vS1KsSi1/iUMNy+o6cRkWjzOVUyoI6lqVbPXFps9YUs5/uUXc+7uRtnCGXmbbGbe1bz+Q6n0xyo2Lfi5qTXyT2PU33MaCYqK6nqaw==,iv:h0omON94X9BzHpynQhwJWfoviIGdDYnSd6vb1ICwDjM=,tag:VlivHCBMp3I2vwKoHzD1Jg==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:2CZwF1hZFInphoC5ETxhI6zADkWbssd9VhZBY276jmPyFA9Ojf6Wrwx1awBYNbx5A57eEEVehgWBtdeWD4TJMg==,iv:7Jh5efb6uc0pfvhHdIIroP630QlytkhcsmdvpwRpaEE=,tag:L66BmF8q7e3dFMhE4ZIE+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNDA1ajhabnVPL1hUem1H
            d1Zqek1LaEFWQXRnZEVkSGZ5K1BCelQxY1VrClN5RUVpbVdLOHRmZWk0UVpMM08z
            YkZjaFREYURFR240QWRyd2E3ZHRjSkEKLS0tIFFiMG1qOXRBTTJsblJNYVhQenRG
            MnB6T0RwMGppVDJScGlZQS9qUG5xZmMKPoJq2S4FKhwiJI/nn1TeE2PA1OQaBnlY
            y/L50yz/hARDAJMdmDX+Kiplc9t7nK+rsIOJHJUNJPynAwV/uuzTuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T22:06:23Z"
    mac: ENC[AES256_GCM,data:+HPi/AIoJ7+989Q1DhnQMKFU5dgbU3+Xut6hqRWBC/AnRrEeFkxh5yC2XFiPqckHN3pl9sG1Bo0Qb5B+JtsCipQPTkbSZqy5rBYcX8MK1lR9CGRIZVg+oNTzHf/XdW13B9WCxRZjhQAQZ/5jjMRXwFxfg8qDApq0+69cR84hKQI=,iv:KzSfqI+5syGtEV5b+irz0s+dKI3koyNfh6cd9F4lOso=,tag:VAL+NbXP3Aum8tgXSPl7nQ==,type:str]
    version: 3.13.3
