---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name nextcloud-backup-to-jottacloud
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: nextcloud
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    global:
      createDefaultServiceAccount: false
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      backup-to-jottacloud:
        type: cronjob
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - nextcloud-nextcloud
                      - key: app.kubernetes.io/controller
                        operator: In
                        values:
                          - nextcloud
                  topologyKey: kubernetes.io/hostname
        cronjob:
          schedule: "27 05 * * *"
        containers:
          backup-to-jottacloud:
            image:
              repository: ghcr.io/rclone/rclone
              tag: 1.74.4@sha256:c61954aaa32328a5486715dd063a81c7879f5195ad3505cd362deddd509dc4a1
            command: ["/backup.sh"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    configMaps:
      shell:
        enabled: true
        data:
          backup.sh: |
            #!/bin/sh
            /usr/local/bin/rclone sync --check-first --delete-after --stats 1m --stats-one-line --jottacloud-hard-delete --backup-dir "jottacloud-crypt:/nextcloud/$(date -I)" --exclude data/data/nextcloud.log --exclude 'data/data/nextcloud.log.*' --exclude data/data/audit.log --exclude 'data/data/audit.log.*' /nextcloud/ jottacloud-crypt:/nextcloud/current
            #/usr/local/bin/rclone sync --check-first --delete-after --stats 1m --stats-one-line --jottacloud-hard-delete --backup-dir "jottacloud-telia-crypt:/nextcloud/$(date -I)" --exclude data/data/nextcloud.log --exclude 'data/data/nextcloud.log.*' --exclude data/data/audit.log --exclude 'data/data/audit.log.*' /nextcloud/ jottacloud-telia-crypt:/nextcloud/current
            # Deprecated
    persistence:
      nextcloud:
        enabled: true
        existingClaim: nextcloud-rwo
        advancedMounts:
          backup-to-jottacloud:
            backup-to-jottacloud:
              - path: /nextcloud/data
                readOnly: true
      calcardbackup:
        enabled: true
        existingClaim: calcardbackup
        advancedMounts:
          backup-to-jottacloud:
            backup-to-jottacloud:
              - path: /nextcloud/calcardbackup
                readOnly: true
      config:
        enabled: true
        existingClaim: rcloneconfig
      backup-to-jottacloud-shell:
        enabled: true
        type: configMap
        name: nextcloud-backup-to-jottacloud
        defaultMode: 0755
        advancedMounts:
          backup-to-jottacloud:
            backup-to-jottacloud:
              - path: backup.sh
                subPath: backup.sh
                readOnly: true
    networkpolicies:
      backup-to-jottacloud:
        enabled: true
        controller: backup-to-jottacloud
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to: # Jottacloud
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                  - "${HAPROXY_WHITELIST}"
              ports:
                - port: 443
                  protocol: TCP
          ingress: []
