apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minecraft-secrets
    namespace: minecraft
stringData:
    whitelist: ENC[AES256_GCM,data:GcEOlPd9rJDZF/l3Jr+EBEAnJH9ZEIu9kLH4Q3pfxF7ph8rsB8f6pDg2nvKQItRPfWIoPXY6f7mOTEAjG3UstaDI2WmLqbNpmo3zPVqq7E/cPX6JwPk4dE2xez2hFV8Y5b3Z56VrW8gHmGqlYM7Erw==,iv:GWf2bUXe9BfmdJmQjVfcYJEZTEqxsPFn4ZEqdI3M+i4=,tag:tQJBG/me3S9mQBVzNuTOkg==,type:str]
    ops: ENC[AES256_GCM,data:ICoON+7St36qFdNnfirz72Ti/Sf2iqToBibNUhk1b6rZBx/sF2gFZnRw9eOdMZ1NyrdZ+zdXYhgjDidy,iv:TqXoqk5LU/3uQWqyV7f+YKpHvYUuEv3xN9C1kC5nBJ0=,tag:y3/AFPYyfP0riEIPgmlxMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQk5FQVU4Q1AzSXREcnVi
            eW5pYy9MTzhWeE5OMzNPNDhZcGhJT0JoQW1jClZIcGpmenZDZkdUSks1b0dkbWt3
            a2p3RkhPZnUrK2ZQNVVUWVJ3YWJFeXcKLS0tIGZDWGRXaVVMeFhZK04yRnBnSVBI
            RzJJR2FNQVBLY2VWNGlrY2RHK2JqUFEKBMo1HjigI/YvlolC2iIatoSE4f95RnPv
            C0USVT/DulefjYkWrqmUy5Oyb951A9anTd3VQKKYu1V74mObYixJlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T06:43:57Z"
    mac: ENC[AES256_GCM,data:DaVjJBDqDEcQmUt7paJDd1T0AC8qY7/J7pffsy0KWE8vxoE50rkbhhl2ph44js9KoCo6KsYvwOy5w4sadStNLY7eFb2ypM8O5dgx3TDVEHkgRQUh5aSyU5SYuX4uYZICtFskVL7YsVOUM6bVTx5W5/vSw53/1zc+OvijJ2xQvQ4=,iv:3TErdqXm6Gjj/B1gLYFUBh31vb95TdjEkLwzmd1JZw4=,tag:NmS2M1c3Bz2vAOvDiVFEcw==,type:str]
    version: 3.13.1
