apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minecraft-secrets
    namespace: minecraft
stringData:
    whitelist: ENC[AES256_GCM,data:gwBaq2t5unPbELCe6cA9Owt2CcQk8Yib1oSLcvX06ej7xejG5JOMrGVD8PwtyZQysqsA1hIjTCL/P/wkUBQoPpHsR6ySyWOci0AoeBqmC4ogHVAGauKKOSVHG46TPZxLjTkIrDZR,iv:HagJRxhTS5ZXrK6bgrIwBxtBt0uE8cdv/czjwbP8FB0=,tag:FCymfIye76iBpf91CMkasw==,type:str]
    ops: ENC[AES256_GCM,data:mcGS2+tUxw+KlvcNSa7rhSl+AOu/lzTsLxOTUe8WJ0ykl4sZMGa36kykcNCoax35xNVHmfFs,iv:Dp+CYqQUDFYhEJJP1q0TOvam343FWXlSv5plzIFOcpc=,tag:ILSPHTpYkDBxciq1xi7BJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWXNzUVJVUTFwOXE4ajhZ
            NnlSN0JDRGZUTmhmQUp3V0ZGaElZZ1lNUXlNClErUDNtdkF6cXdoa040SDFpVXBH
            QndWNEpVRVgwVW16N0Y2MmxCb0tBWkkKLS0tIDh1amZobEdmcFp4SjU0cjBRM1Jo
            ZUhmRHh6ejFFbWdNMXZ3N0FxY3p1aDgKznJuZxg5TfeZWGYHzHVIkfx8TghrYM42
            wlnBgxEzr7JQJT8DHu+Nl8hw6J0Q4WqHsLoo00sFDJI8Wydia3SS9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T13:38:01Z"
    mac: ENC[AES256_GCM,data:2/qUTutpn8YrAJm+Xlb93EdvsAAn4dqUp1g5uPixytMIWfXVGqURdOgbyOLLYdTwcvm/BjhM6e0EtgXczLrq7upzQO+JpimItP5ND89kfSah8EO490uiMzjQp+ADhpPB9WW+91GsaAKoJ2bvRDqHrwRYBOaVh5UEyhasmEoNq7s=,iv:ZBsyoDjdooBHHCXNCyvfrSarjTgiQcpnbL9sW35Pd04=,tag:pvPEBaY4YbkE2iQvnxjeUA==,type:str]
    version: 3.13.1
