apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: openclaw-secrets
    namespace: openclaw
stringData:
    GATEWAY_TOKEN: ENC[AES256_GCM,data:X7CiTjnqJJH3F2bsrHQoMML/sj7srf6sh8H3o2fsOE/JK6FZjCbEixxyt5xXG1u34hYkBihKmInqmKo916KYLg==,iv:gtLs445mGqQxjZjmcKvRrhO/5tE5cAQ1IxwtYqDdtcs=,tag:NkdZeHxjxsmIUo4f5nGqiA==,type:str]
    GATEWAY_PASSWORD: ENC[AES256_GCM,data:TqgAFyWm6FcOwKFI63vgoyIb1Cdxo045OLA4czra89Yc6X7hT3G2LNUnY8/NOoMjo87DBw+OuxCMzios1L1onw==,iv:Nkpovd+KHkyqBXmMm1NE3HYsB2Mt5e51daPEuC0EsIQ=,tag:f8y7JSl9QAsQQOWtITE9RA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:aaDkFiFmxkuFM+w5fmHjDggthE61tfdZjVWgOzXAVu5iuLV4Q3HcKilSBcbbsw==,iv:VaK7IH8p6X4TYxmzKxvVuOsEVSli0i3jrAGwDSAmB+g=,tag:YHcGceiZeYrSaxFYil+JNw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:P/U9NyPsA265aESa+pgCbpq/vBXE47OHDJ0n+g5kXaJay/ePHH4EfbU2CZvTZdRgOzr/O2AknPXqbr7EKCzg5qjysc/7MjJX4vjPJjt+OglGdL868BmaM0jLOE/X,iv:zTHd09mB2w3SluySI8gUCY6wOdlz/jJNjtxsebOX7wQ=,tag:ePgINw2RgCKi5gWAoTbLtQ==,type:str]
    AWX_PASSWORD: ENC[AES256_GCM,data:OA0FyKwXIYCs6M0l3K7kZaxX4Z0/YSRyCvUe+6O3saMlMinQ+9yZQXGBe1jpq24kyf6/njIDm4d3VYBBVAprRg==,iv:yS4Hir2t3UhcEvJCMBekhem1Eb6fgImY4BS1w9tdXxM=,tag:KtmIYzw4bhKpELq2iB2BKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTXJUMG5ZSjJWbUNkS1l0
            RHBxbjJ3NXF1ME0yc0lZSDlyUnNRVnFHNFUwClFlTEZqVDdKQjZQZWt6dmt0bHZs
            ZzJ1NTdJMTFjTjh1SUFmWFM3TnY0dEEKLS0tIENiV2ZpZWdGYzd6MGR4WEp2VVVh
            YUM0eXgzYWlZZHlVdTRSVzJGeUNNclUKZjjgk2xocjYbH4nv35BokKWYt+tvISs8
            4EvXo/JmvgpKSQjNlW2tx9AYExHQTZqC/LS6SqaO98i59Xq54Fdj5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:55:31Z"
    mac: ENC[AES256_GCM,data:tdSQN/Uc2oe2ZbzFGuf00fs7ZtDSZTi8shySm4HaFw50TcHQuFcpeD1C7G5Ck7BO25nysc8kzmPEAQX3V0MwPuqT3UPkaqeQhMyTWVwR/M6sbbS2ddUE5yvl9PVqdBPsPrEgnmVIbj14Ah0hbfYefHSUBLBtOi1gJMY7xWi3WlA=,iv:FBe8XBoR0RbJ04QqVojmG1BeUdSQEDhWIJUucSo9EfI=,tag:k3LOmRwROBOUgcB0jqbctw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
