apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: openclaw-secrets
    namespace: openclaw
stringData:
    GROQ_API_KEY: ENC[AES256_GCM,data:ZImr8eKEIqUWX7qDH24Lnu5aeKtmvm7iyhlChRHfN9jHdEKiWlqY5EqxjEe0eT6I7qrUZO4hb+s=,iv:+zddRzvUomQJpOn2Fk+WrnZPcIP9DwggE11s7hyYII0=,tag:SMgQtfGCCe59BH9on3IcfQ==,type:str]
    GATEWAY_TOKEN: ENC[AES256_GCM,data:VeRg0slVMDgVbfL97Xd7pCzwq+w88oFuLQVGIvREE7c+Pxmb2JtV+sQVMsVElcoZNCDFezqONd3bBgbhYlM4Gw==,iv:sae+Y1t/3xij5Ac3byMrDnyuvMlaPKcuYuh4jAaNHIE=,tag:TXqPbZqPgukywi5mykyvHw==,type:str]
    GATEWAY_PASSWORD: ENC[AES256_GCM,data:zAtRSq1vifsGnQPgYtd1HqcBVwS4aJTcT3Ef3TH4smQ9bhfIB9rL9WhO6rjogYEpFGAdMq6ukN+sHv+i+iBcvQ==,iv:6JJsDWRGaUOlkQQh8+yxR3qHg0eAPtUMlAG7vrAlUgg=,tag:eOJIuwuWDissN5VdsJ3nwQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:hgHEfQjkc2CiBsXjWhsAk15x9YKxo+pZDvBbnEthjIFu9cL9fXZiTvvQsF8bZNV40r1rXrKNDP64dQdnony8r3xjlbuQFH4ocg==,iv:Ytfzb7MZ/1Da0szv+zMV/+3QM0zcDflNcXF3ZQ1V4PA=,tag:OhXWtMudWcq1h1qebRWF0Q==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:1vXNvRMqBJ5pBac3FQn7O+0NrI+kmhoc6Oe1CeATn3WwsnxW+9W/LfGBbjDEcQ==,iv:uwcEBHuxKHIgzpYn15+0tFyin33N14dlRPNjukZxzQM=,tag:UQuMaRlaYJMIn1naHRcntg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:3UJbGPnDK91d0+flbgWcGED3iK71ICMwnCRfGa0nVF8XwThgve1gnYK2B9nhiy3Y5FLBalYyGDV2p8vzV3+atVEUgiwVJqXp2CLTZ3KZAQsSVVG444CvkyBHNt2z,iv:90BM7uQ84tSbhM1yU50L4LIC3YKXx2VGkIu/Zyu7yTk=,tag:UbJAl/tFhulfRP85jPdUJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbEdULzdtNnB2UXZXbzhu
            VEJDUmI2bW13N2JyVHJ1YU9MY2pWK1QwL3pvCitHN1M5N3k0WEk4MHFaMlFpNUUw
            MUM2OGFWZHhwUUNLM0ROQTRCNHR1cVkKLS0tIHZwdTVGbGxFeEpLU2c5WXEyZFlD
            TmZQSmJkSmx3SEhDY0lwM29ra2R4ajAKRbwsNk8H8GMWgmgrOEXHIVwXz8e0ciOj
            c2X1OKJJ6n+TF0xGPUcZQYGXKuJZrdMe2JdIqOJ1daFBISX0ZAYk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:34:51Z"
    mac: ENC[AES256_GCM,data:eWen8OacrWUe2ObQhgA4QTZCG0tDIf7hQAz4uUlSqo+sLQ1tGPMZaO5lUXP/0111Rp2crXKT6OEVWhNBQ9QWLasAQdzE1L1yUcPh8AjD0b+of7gZf1XFAHQcUtGPWWhQJyvHxf1Sl2X3FE9ZKeb8LvQovAKIrwqp2fLgnlD4gWs=,iv:+UPtsdfiV6hLNl9T2pzCUHD+3+W5+HkAUC4rNH1RkNg=,tag:KpRVh4RZiW+kC0v3u8PvVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
