apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: openclaw-secrets
    namespace: openclaw
stringData:
    GATEWAY_TOKEN: ENC[AES256_GCM,data:Q3cHky+f9E/af864jThqFQN7YBf5xvhDY0VqcyXRF5p+TB0CgiPLMXDgyEA3dy2j60qc9vRNKZHX9mNu5b6E0g==,iv:JaZelmp6mBbOYXS9Rfad2vvb+g5t34vNj02L1SYFleg=,tag:+mrX5XqI0kQVmgqXv3Uulg==,type:str]
    GATEWAY_PASSWORD: ENC[AES256_GCM,data:0lFdn/ZDUagyZ1b+SBr69DcXYe1AJF9JSHF4thrbtHpLdRCu7aautnecPrkAmfBaE8TN2vCgwSwpFirkjHIfuQ==,iv:/IZzZdj54PvDMk+ujUGxgBSLEJQeiH7LEXS4FenAWSc=,tag:gTN8vTbwUqwLEK7hPtB/TA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:HQH/IDqC4UjAZ5wgWUZcXYdxaS1wXPsjMEpIxVgBb1Gml02pPM9NdUYdtCDWStmjMYvpd1P72x1TtuF0Q3F8IGafxRtbYybhAA==,iv:2L0FRvlZaS0DwamrZaRLpLGze3zoR4UnuNyhYGSwW9U=,tag:gIycRpQKTG3z80mkim7i/g==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:pU6ytnIvX9RPqIDZNOGzMSfZyt6jcRtV/8Zhvx3gjTufFbMsGPkVGPxipafYag==,iv:fJF0+sMmVb5A0ZegOJm887IGJnIjup7bktmPUlju0VU=,tag:FWKkZBFWhhIk+9honwXuzw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:wtROX4B+kzA1ihKZvy/uwkrOQnTQDpcVIWbL1CiXT+6SVsvTwuhOswtah7XWh8MnCdIs7BZ42cIggplalhAN5cYFKYR1nnzFVagaq6/8GlilX2rYp/d0L9GbCqem,iv:Xtmhj8bhybZ0RsLHxl/bp4DRSqQmuPHbV+n3iiVTbDk=,tag:t7HVDk9++HPRn7X4Y+jUkw==,type:str]
    AWX_PASSWORD: ENC[AES256_GCM,data:A61v9DCA9GSoPli8MGMAyCyM6cwdwyE1gv2+gsZa8Zt+m6GS/rG01QjEfBv/XgCk6+XNGsTVb8LKi3k9kXqJuw==,iv:DubN7AyPQ0FfzP8b8P6rhQJaFCsaGNvZJX4dhPYTlZ4=,tag:O9a6xgRdkBT/OvJqwNvwHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYW5HZWNZK1JxZCtZWWN0
            MFBSampiTGVycjI5QTJsMWpTenhxVUk2clhvCnY4Tk9meXZxR0JPQjNlM0FKeFY3
            djJMOWJtciszTmUxSkhUL0Q2MWt2cWsKLS0tIFdmZnkrTFJlMVBFRGJtdkw4dk9T
            WEttQkZDaEJHVE1HUWxZQWxZNCtWMG8KNUhHCK+ATZf0JYvpCvkhoegCFLglHauR
            b+O5V2j1q5NZ6HlWtVMpBBLuvw37xHZIi5XKX5DaI/qfphzvMAR98Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T19:03:05Z"
    mac: ENC[AES256_GCM,data:HggjKQVuTn+v7avVq2UOyHx7HGmcluRjAojWfhIXvjCt0BFWMbkf/ljtwrqloSRp39VFt2xZxfxHUPxXGhw7SqAblY9UE9yUTuJI0kPqZ1mIKNP3ChhoDwtCZLVq0NV9fY35J7hZm01D5yjynZ1zlyHDDap9NjBfrF60wKn49p4=,iv:8gBeHcdKX+ERzkUvJHRYwsumDraKFQn01dD1g87dz/c=,tag:TP7HJEevttkNKJIqbt9q4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
