apiVersion: v1
kind: Secret
metadata:
    name: chaptarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:geJMvaX1odo=,iv:2aTEviMRAjUMb3ZfL+uEThZe67n9dlas7OIwPGptvSc=,tag:ec7CrugejR4p3jR2QTh33w==,type:str]
    password: ENC[AES256_GCM,data:qgc7MCNVMN5Xw+kSUvCH5yLXsyZJwa+r4HmheJczafPhVpciHT/fzO+SO9ZBoerPQXhZ44uj+Y/0aMB8/fGiAg==,iv:OMZ51avftq8jLUGbfYm/9Zuur6G5WurG6gv1hDJPgLQ=,tag:dqTYvGqE96U+WoUn5whC9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NG9VcGRZRGFXVTJpNEtX
            cVlSZ0srcXNZd0IwcW1IZzJxd3BkUW45YWpBCjQwUVhYVldnNGtMM0lsOGhsa052
            SDZpTXdFQ0lMRkZqajVHUHpjNGtGUVUKLS0tIHpQZjFZNTVXVzBIRWtxbDMyTFY5
            UEsvNEp2ZlNxT0lNTk5KV1hpNG1lLzQKX498StW0jL3WJ7mw/uJYzOZf8A5m4Qfr
            rnWQTlVXg5cGzhLRJGZH4N8m5f3MqMtaDUjRWcX2mMvHpuFbIbzyKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T19:10:32Z"
    mac: ENC[AES256_GCM,data:u40BIgDTIbMdXNNse8EbYBZlX+p76ldcPRwGD5ADVBRw2IkhvYXHzrrW54khSln+7MY+GY/1ExOliyUR/8JG5b5McdtlZw3I1wSOhheEii8TvWKeigW35opPXEn1gjtngWrwuXZULWCen6MuxKysvdbe5zctniLKXLvbbFzj/u4=,iv:/Z2abkT04mXpgeIK9No4j3hbbG5JWKelPFTPzDnpirM=,tag:IChvrJNlsF9+kssXfb0D6w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: chaptarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:s4+cQdtJwBWjRAgS/vyRwWxTIs3oEiZH2vg=,iv:B2UnJpATsNtGffxYrsp9U3v0NmqweJ45S7ydlyO7/Qw=,tag:peTRHyagY8+TOD42LSjZjg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:jvTP19p/vk8K06qGG2dBfA24PqcMn/9Igk+4q+t+g/AUHr0hcVJNFF3jIxYR21sG6P7bvKE64QO35uXm3OErdg==,iv:/j+T8JVBs6en+u/TPwhPd28/hsn20B2I3cidmR+d53Q=,tag:GX8LlXNVQIh1ufvqEZ/zyA==,type:str]
    region: ENC[AES256_GCM,data:J+a1mVFi,iv:WNTdpmXKNJI83T7z+zsfp1OzI+YY+/p/D43NwpgkqnQ=,tag:Sda0bK+4IL4dfBZaXskJrQ==,type:str]
    password: ENC[AES256_GCM,data:mHASRUFe4sK3G0uBA4spdPNijQFc40CA7Bz0uyOkSt4d5scaHqB0xgL0D5KGhljP7l77Qkw6TEHrGsy0gyWfdg==,iv:hJYamFgGBM3R/jO1DBOX0bhX02ZsQtuvhoQChfYYkJs=,tag:XP3XBxjktz+Km5EOUnxy0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NG9VcGRZRGFXVTJpNEtX
            cVlSZ0srcXNZd0IwcW1IZzJxd3BkUW45YWpBCjQwUVhYVldnNGtMM0lsOGhsa052
            SDZpTXdFQ0lMRkZqajVHUHpjNGtGUVUKLS0tIHpQZjFZNTVXVzBIRWtxbDMyTFY5
            UEsvNEp2ZlNxT0lNTk5KV1hpNG1lLzQKX498StW0jL3WJ7mw/uJYzOZf8A5m4Qfr
            rnWQTlVXg5cGzhLRJGZH4N8m5f3MqMtaDUjRWcX2mMvHpuFbIbzyKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T19:10:32Z"
    mac: ENC[AES256_GCM,data:u40BIgDTIbMdXNNse8EbYBZlX+p76ldcPRwGD5ADVBRw2IkhvYXHzrrW54khSln+7MY+GY/1ExOliyUR/8JG5b5McdtlZw3I1wSOhheEii8TvWKeigW35opPXEn1gjtngWrwuXZULWCen6MuxKysvdbe5zctniLKXLvbbFzj/u4=,iv:/Z2abkT04mXpgeIK9No4j3hbbG5JWKelPFTPzDnpirM=,tag:IChvrJNlsF9+kssXfb0D6w==,type:str]
    version: 3.13.3
