apiVersion: v1
kind: Secret
metadata:
    name: chaptarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:lgaQXeLTrYY=,iv:ToFYhsS6CoVSL3GNVv0vXiT7Bdj72E5kXU9lBqcd73c=,tag:w2gIkNh8093vKhEDzMmeZg==,type:str]
    password: ENC[AES256_GCM,data:UniT+mph02kQ28DNQ2s4iJ+JT27lOKW+qAaJdRQGk5f/SaVbDwcAo9YjtSkNza12kuIv6OzC8SNlAhJCFMLtwg==,iv:ExXCW5gWFhj68YznITW2DovqZjNxX4pJL2az0j1i3UQ=,tag:ABZpmMTyjS5494TtJfWfig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZW5Ed0x1WnVYUlpwY081
            S3hYaThjY3NtaDAvWFNOUnA5Q1d0c1lvOWc0CjhYVEtUa2t2SG82YlhLT0lUMzI4
            VUwrMWtjYnRaVnZENW9PbGlSRGFtdU0KLS0tIHVFaTFXVGhuMVRMU2Y4VSt0bHQw
            aXMwT0JOSGhpcmJNZ1RTMGFUTHVNancKu1rAACYd3E1FeUAqNf6UyT/6U3DEH6qt
            S7UewoDDNSob6KwyHa08UXTuIRyNIbM+K1ahJ6HAkJzjeRwzM3OYpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:Ae4J1XWNTLRf2HDHHYWSbAxEJUXHwmLkpPqz53BJLoM9wL1E3hIHTihrTwGcMQ/SJS/rriEJMu/61dWsXe/HCWtym8gjOPxDA5Sts6R4ueXSDHCkYJElJ/DlwnkYWMO2yki7kDoBTFJvl+Ek1h3DwDYhNeM0VdS004DHbvyjRWc=,iv:afK1gX2t/U5vdPWUZpxqriRcfoL9DsM5Zn16j60PFGQ=,tag:RC+q16mNgW7xgx69jBsAIA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: chaptarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:AaUbeKNEqhrrepEOatrDoqY0fYbJVQzXecQ=,iv:VWrqg5P8p6LdCxZAPTb7kmAHhbUz5MESZWImCX/FSFk=,tag:skNEfLpzXeXtyw6/HVrMPQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:dRTNSuQXVfPaSaEXQmm1jEUcBS1L//mz4Qyy9uJNTQzmiGwAvut9ffYq1Ls3WbilxZjdziN1KhLkTHEyMHlfQQ==,iv:tm+kiaffDEhnvRVfdoNmHJYmR4Ds13xoLf19qmtfFaI=,tag:Hm9GL8kCnwdZ2kXGn5IHkQ==,type:str]
    region: ENC[AES256_GCM,data:JffFzFiQ,iv:1uPEgvrv3GWSU9QggP5jACR6oD+nKSdB3GqxrI/AQJk=,tag:JovbalgPlRYTM/oTx6kDjQ==,type:str]
    password: ENC[AES256_GCM,data:7f7yH5VTrV+gba9jRqwhZddGskyE88Xn8nPhdsrWnuzjaFwt8a1iUmVWLgjefvMUzkI47UHJtMlq4rdlTz8Jtw==,iv:QL6rBYGEuNw219QURdDjZlm25CpUFigy0MyINAFOqT4=,tag:8Wq3es4oGJ6iZx+OJo4Ivg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZW5Ed0x1WnVYUlpwY081
            S3hYaThjY3NtaDAvWFNOUnA5Q1d0c1lvOWc0CjhYVEtUa2t2SG82YlhLT0lUMzI4
            VUwrMWtjYnRaVnZENW9PbGlSRGFtdU0KLS0tIHVFaTFXVGhuMVRMU2Y4VSt0bHQw
            aXMwT0JOSGhpcmJNZ1RTMGFUTHVNancKu1rAACYd3E1FeUAqNf6UyT/6U3DEH6qt
            S7UewoDDNSob6KwyHa08UXTuIRyNIbM+K1ahJ6HAkJzjeRwzM3OYpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:Ae4J1XWNTLRf2HDHHYWSbAxEJUXHwmLkpPqz53BJLoM9wL1E3hIHTihrTwGcMQ/SJS/rriEJMu/61dWsXe/HCWtym8gjOPxDA5Sts6R4ueXSDHCkYJElJ/DlwnkYWMO2yki7kDoBTFJvl+Ek1h3DwDYhNeM0VdS004DHbvyjRWc=,iv:afK1gX2t/U5vdPWUZpxqriRcfoL9DsM5Zn16j60PFGQ=,tag:RC+q16mNgW7xgx69jBsAIA==,type:str]
    version: 3.13.3
