---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name actualbudget
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: actualbudget
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    global:
      createDefaultServiceAccount: false
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      actualbudget:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          actualbudget:
            image:
              repository: ghcr.io/actualbudget/actual
              tag: 26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
            env:
              TZ: "${TIMEZONE}"
              ACTUAL_DATA_DIR: /data
              ACTUAL_PORT: "5006"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    service:
      actualbudget:
        controller: *name
        primary: true
        ports:
          http:
            port: &port 5006
    ingress:
      actualbudget:
        enabled: true
        annotations:
          haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
          haproxy.org/ssl-redirect-port: "443"
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "DENY"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
            Cross-Origin-Opener-Policy "same-origin"
            Cross-Origin-Embedder-Policy "require-corp"
        hosts:
          - host: &host "actualbudget.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: actualbudget
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: actualbudget
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    networkpolicies:
      actualbudget:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to: # Enable Banking
                - ipBlock:
                    cidr: 0.0.0.0/0
                    except:
                    - "${HAPROXY_WHITELIST}"
              ports:
                - port: 443
                  protocol: TCP
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: *port
            - from:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: actual-firi-sync
              ports:
                - port: *port
