apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: actual-firi-sync
    namespace: actualbudget
stringData:
    ACTUAL_PASSWORD: ENC[AES256_GCM,data:cD2PpPo8YdhK5ULvtgAugzCUjr6MPgw6qiTxMe1Hyed0nY4c7y2FXbsKh1hIBk5pxCs93FNlTqil95TibM9unf1cTjPTYoh5hZAqtn0wtODc7Kgi7kQmrAFdqUqlolO0C1LcQYmW6PbYOiMZZK5ooQ+in+E5YGIRWOV7tbut26k=,iv:pHJ5DHEwTV2zR/LMQqM71xbU0LfnX8rE/wjXMjHqtPY=,tag:OJfYOi16qG/b7Lh7eeHluQ==,type:str]
    ACTUAL_SYNC_ID: ENC[AES256_GCM,data:Ce1rrfZDw2Z7qe7LJb2+FdwiPQCqjprOt8aarS8UyItWcB9E,iv:lT8jZAZZbIYG2NjJIKkb1OccBdphkCjgJ2qfese0Dmc=,tag:LiEEB+Bur1+biQpGv3gHww==,type:str]
    FIRI_API_KEY: ENC[AES256_GCM,data:ahS9CnlYXHYI/+ipkh0WYJqKLr70pFCWD/SnxYf17EyZ84n9fB+6yxFGJYnWRiq4RZKR38TU4rrAZmR8SnY5gQ==,iv:CPp15tbsZC4GirJbgXylJLNspK4HpZgVDh/J3aHTAN4=,tag:2H121l6rm+QlLysGyZcrxQ==,type:str]
    FIRI_CLIENT_ID: ENC[AES256_GCM,data:g8CAhRPzul0zx7MgoIz7Pxfk8KXJ7C68OBUQO3fmySiFCS6vYmM1xkYA7yFuodU2zuIpIDKxYh7JZ4aQnPZHWw==,iv:TMouAalx6i65k8bDTvyhezNptg/b5DxaeBZ7IInjgHY=,tag:tJUhL75+AQOXlzqB4yorhw==,type:str]
    FIRI_SECRET_KEY: ENC[AES256_GCM,data:N8mfKJ/sKeGNw/ePvnUqgSdRHIDdy+cfZ8KdA3rTHp2ZBdVMLRegy5xMPQwpzsPhbTXZflSZ8orUVMpyOvlaVA==,iv:hks5YCCT4MhCYFOKv1ovXEiyfgPkQ74oSVtKOGwMQuc=,tag:qc/18RM3WP7sfJ47UaHAUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXam45b3RkM2ZDSzFHajJE
            ZFA4N3JOU0FDOVRrMlJEMzNIZkZ5bmVSbUJFCmszalVYcE1OZWdEZmtBSjM0R21K
            NXNPVWJMczlhbFJRQnVIdFJvUzZzNTAKLS0tIC9ZYm5HK1BUUmxoRjlZN1ZKSFhl
            aUQ5OWI0VUdPUWJuZ09FZjM1ZEJFZjQKJmZ/HuPmXHiLdBCCscC3QLoaoKWG7kDm
            IUYHA6j0pcuJDHuw7bV4tWA7mf0dI0BF+0h3OjtpRanv6/gpskOPPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T21:21:42Z"
    mac: ENC[AES256_GCM,data:O+i3egLiPnI1GckUQVNYb0b6COFWVk+0upTJNeiP5zB8z3OXWTn8LBzcX2UUQYhvGHMwpn5Jx290r60MeLL/i9UtaCDT95fz2jwckRMyRGJXdxLj19eKFHkm+4gXgIPI+ddFYkdhjSmwIvx7/T/kNhU2Hi03CZ2rrQoHI2lA3oc=,iv:nyLxQNqTZ5LqKFDa6Rp8jnDyk+ss5GYrwqW1dlApkks=,tag:p89lN3F4n1//xxgCLZv6cA==,type:str]
    version: 3.13.3
