---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
    namespace: flux-system
  targetNamespace: smartctl-exporter
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: smartctl-exporter
    serviceMonitor:
      enabled: "${MONITORING_PROMETHEUS}"
      relabelings:
        # replaces other node identifiers with hostname
        - sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: instance
          action: replace
    prometheusRules:
      enabled: false # "${MONITORING_PROMETHEUS}" - this keeps nagging me about wear-level, but the disks still work fine
