---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: smartctl-exporter
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartctl-exporter
  namespace: smartctl-exporter
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: smartctl-exporter-smartctl-exporter
      app.kubernetes.io/name: prometheus-smartctl-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - port: 9633
          protocol: TCP
  egress: []
