apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:QkJBay5HzIw=,iv:Ui/yYP1scE9zNEcsgG43FB6wzMJ67j2pq7XHnzATuhc=,tag:IfiTJD/7FTwl3WN/Gsk3tw==,type:str]
    password: ENC[AES256_GCM,data:fb9lXqdAuOVu2hWcyTJ8Ty2NNWP2oX5lUQylTPrqCup4wpS2lnxdSF66QAgwyhXvYUvbiiXyQo95+pDILl09wg==,iv:sVPrH6WOjaqtizi0GlyzvJN3zFyMF9dju/y43VvaGOk=,tag:9TfKlMM0d7zlipcDu1rfXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVU9OZnJUbFlGQzBXZ1dr
            T3lRSzRWV1V5WDdsdHNpZE9iNnArRVA2RHkwCkUzMkxWS2d5VCtZaGhSdUQrYVdZ
            N1pYd2hvN0xpRVhCTkloeEg0bGZUUHMKLS0tIEhHZG5oK2wzTXA4aVlKRXZYa1hv
            WjloWlhqa0RIQXBqY3RJQkRCT2JXTzAK3i0MZ9tGsl2ezBe6jyvdxpNYapAMbLRo
            n+Kw8JARh6VqX8DlU68ZUILoN1MCb+21NucDJaj+fn3hBgKtMoZZOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:iCu1SLgItGXdb7dnnPDAXHh+McZXPlx7Tu4a8e2b2ppSDPd6ufR4Vxv9ufONOXHIiZnyP8cc4YephYMK9b6eWeJCO1wVm+YVlvJBWkD3LhvYAkLA2OMORx1pQhXnaDleQkFLsH5FxNvQPzBiKXDj7rRMhTBwMmvOoEjbeGc29E0=,iv:yjgwMuL/Xj0aGGhh/kFrebhS1lfTkVgj0IHxeespXEA=,tag:5U6RRvTKt1fMpu4nwUZ29g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:EOQS5VgkyAlf5IAnhBy4+AfuXRPlxusMI3Y=,iv:guqmJcYmsRRvJm04AEPAnYBxBKULHwsnGCrA6efZsfw=,tag:r7PV0vSlxs5lZTgGlNI2Qw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:F17ZS7OgNpfVHaIyYyhLiyplEAcS3Cc8yLdSK1xvMsJU9Rf4zAxHTB4Hm2rKCgvqfqzssNHahfJLtQPEo5foXw==,iv:pO2moEC2ZTMidstHb5KypWbsnvteQUo7i9C3qhgNI8s=,tag:46ZCcgfD7dnq9JLfGmiZbg==,type:str]
    region: ENC[AES256_GCM,data:eXisFhwQ,iv:msctX5QoMB269B06K9U9v6A4mh/rPrJBSAslaO/Uu6o=,tag:mqVQlTsSumXJpwAUt9isAA==,type:str]
    password: ENC[AES256_GCM,data:C7LUP+n+bBWg9gvd2zPo9+H23uDy5wTc79835NRhciBAy92T+XaH2BFRD5DPsWAR+aAdU/rgdsFUl0X+sepEjA==,iv:gfz/dML0Wn34rk2qFOr42Gla1s6Z7ansLmgHCg+85dg=,tag:Bz+l8bz+OFe2hCAFPISmuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVU9OZnJUbFlGQzBXZ1dr
            T3lRSzRWV1V5WDdsdHNpZE9iNnArRVA2RHkwCkUzMkxWS2d5VCtZaGhSdUQrYVdZ
            N1pYd2hvN0xpRVhCTkloeEg0bGZUUHMKLS0tIEhHZG5oK2wzTXA4aVlKRXZYa1hv
            WjloWlhqa0RIQXBqY3RJQkRCT2JXTzAK3i0MZ9tGsl2ezBe6jyvdxpNYapAMbLRo
            n+Kw8JARh6VqX8DlU68ZUILoN1MCb+21NucDJaj+fn3hBgKtMoZZOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:iCu1SLgItGXdb7dnnPDAXHh+McZXPlx7Tu4a8e2b2ppSDPd6ufR4Vxv9ufONOXHIiZnyP8cc4YephYMK9b6eWeJCO1wVm+YVlvJBWkD3LhvYAkLA2OMORx1pQhXnaDleQkFLsH5FxNvQPzBiKXDj7rRMhTBwMmvOoEjbeGc29E0=,iv:yjgwMuL/Xj0aGGhh/kFrebhS1lfTkVgj0IHxeespXEA=,tag:5U6RRvTKt1fMpu4nwUZ29g==,type:str]
    version: 3.13.3
