apiVersion: v1
kind: Secret
metadata:
    name: openwebui-basic-auth
    namespace: openwebui
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tnWJxWK1y0xU,iv:AhU17nreZRHOPQwNwkQ5uDSXvPyLqwZXWCutw30WeOI=,tag:6WAjeWnqqFad5FYO0JLxjQ==,type:str]
    password: ENC[AES256_GCM,data:mhDdcnWrSmgOziUlmUHtonqPyRpmqCoBzRQ1RcYITTY=,iv:sZ9ZxxP/sVQ3z+jR4WL+OUAu6k69/LOc0C/iFJbD5e4=,tag:TNa5BSPdfw0wMNKD6bkTcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WUJCUzJ4UXl5U0tlUnB4
            OHBUdmNRT3ZmNkJjR3Urb0lLUmtjNWZQbldVCnk2bkg0U0wyMThFNXVsd1VRbisr
            dU1wa3RGZHdHOExTdWJYdFVleHdGM28KLS0tIGsxc2cwRERHRWxNUFliNDgyNmRh
            VVY2bVRJNk9ndnNwcW1DS01lV0krRncKZr3PaaL+k+4Cdos7FRerf7UHEVQszWde
            J7EDt4d4Er+Am24/wotvq5oDiD7t5PIdFd1zfQmV7doYor/7ByEQqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:eDDXumVFPDsquSxNQXOSFZqW2HrHGinWQ9yfJ98riaw9PC0jGDqcGUGEQW2Y25+Xf1x8eczFJVx0EgEfy/SwHET3yWoJJl+S4P2LVKOVHqEO0EsdpxCPEtae1RD35l7VULUTmynBR/Se6lxLxqARjs4Nab+64IAU4QL7Ft9593s=,iv:hMmO7ZgVjP/sd5/69+8EQdwplRjNHkHRNYpnFQPni0c=,tag:gvfZDlsMG5g0Xul3YUmEMA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-postgres-v18
    namespace: openwebui
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:rRp9DhvoNKQ798wFWn6TxLlriKumr2s+Yh8=,iv:MK+Vialf42h1m6Dk7jIkHgDfLEGNLPhJ2u7/JaQWC0s=,tag:UYAgeyjir+MoLyg5DP/RXg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:DTvjtE5d7fBjjHqCS2zP+jzbCJuLMBs7cEn0BKzX7XRaE/Snel44BLgkTwN/6pa1WcOc2ajCyHFNDaHkYSUDLA==,iv:3DlxGBZa5c6psQABIWvKlgGjvU65mfZv5F+SlkFsE5Q=,tag:h27c22g2sTcs7dhR+TeLVg==,type:str]
    region: ENC[AES256_GCM,data:IdnII76J,iv:6UbjqXap04KGupvbfbe0SIMdInzUAJuIGEwyj8E5Yp8=,tag:PyxUtwoH1e/O04Jzdl6t+Q==,type:str]
    password: ENC[AES256_GCM,data:3VCPZgNgkrZ5gFRIuJR4W77eqyHVMGqCRnKuCqlopDs=,iv:VYLmJklDcsxFdeZEHm6mSOVMQsryssa0Rn59lJul6zg=,tag:wH44od3DvFsBq7AeGMzQhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WUJCUzJ4UXl5U0tlUnB4
            OHBUdmNRT3ZmNkJjR3Urb0lLUmtjNWZQbldVCnk2bkg0U0wyMThFNXVsd1VRbisr
            dU1wa3RGZHdHOExTdWJYdFVleHdGM28KLS0tIGsxc2cwRERHRWxNUFliNDgyNmRh
            VVY2bVRJNk9ndnNwcW1DS01lV0krRncKZr3PaaL+k+4Cdos7FRerf7UHEVQszWde
            J7EDt4d4Er+Am24/wotvq5oDiD7t5PIdFd1zfQmV7doYor/7ByEQqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:eDDXumVFPDsquSxNQXOSFZqW2HrHGinWQ9yfJ98riaw9PC0jGDqcGUGEQW2Y25+Xf1x8eczFJVx0EgEfy/SwHET3yWoJJl+S4P2LVKOVHqEO0EsdpxCPEtae1RD35l7VULUTmynBR/Se6lxLxqARjs4Nab+64IAU4QL7Ft9593s=,iv:hMmO7ZgVjP/sd5/69+8EQdwplRjNHkHRNYpnFQPni0c=,tag:gvfZDlsMG5g0Xul3YUmEMA==,type:str]
    version: 3.13.3
