apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:t5p0xgjx2C8y/TQlm8z0+GsB27/gUdxwu5UrJFE8WnM=,iv:qqCDpmZk5egQxhSqmqDP15OIuqMYAZxw4grmTe5AFbY=,tag:mu/xEHvUmrHw+yg0x5S2xw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:M0Kwvwk1V6KwOSORG2RLOM8CI5dhP4E+QloviYUxvgNDofVnqnZHflKL29RWBbuSfT8Sw8J/3idWHzcltKCj1ViJz+/zhTDs1yZZyFbhoWACRWC4yY5ENw5CdCm2ow==,iv:QuFh5nw6zj2u0icUebD9y6York9QhJ19vt20fuosThA=,tag:Q/dDhwR6G0xUk+3IU61jsA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:L9KkHvyctQmh1iMch9rJ4qPgbzEBbYLLrIjEtAujOcxGs9y2,iv:sbUdmpo3veBfp8fOMXbsCagIMX+c0atrldqJeMLdqpo=,tag:zSu7C8gSk3wW4spztulkeg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:IsJCcgLuhml+LMByM/tYxuqCaDwr8sGwSsjdSzLVL0I=,iv:r4T5kKyseflqEPY/CLABYDvEv8p3MCOOxyX2UjMXqPg=,tag:QF3t5xH3Nt8C6CIld626YA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M0xvT2RlMjBPM0o3M05X
            Q0h2anRFd2tYNXBOcnhDZ1BYV3dUMkZQb2tJCnNOa0FsT0JaclFiOVVWbU4xL2Zs
            dndiWUEyQXY3clZJQkJ1YUJ0T0RBL0EKLS0tIHUzOUpMTnI5cEcrMXJFOExxZEZv
            dHU5VVdiY2dPZFNLMGsyUExIY05veDAKW7R/AS5wy8plO7ufrIGbQ54EoP2dxgE9
            4oXSFAlQqGmHN/x9xva7nPXocaEmDY2zOJLWTZS4hg/WqkeIgO04/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T08:50:10Z"
    mac: ENC[AES256_GCM,data:TfYEWYL5ADjRWzMG5g3j45XJjFn2rsBLXu+wcAjn2ECBZ+tuu/lTGZAvNf2kH6ZSxAlFDUnpyes4uA/9CwN8OM0cb1d1ATtW6WwLOscyTPW99UvZaqMd5wMebop1t9WfuA7aD9/zNSGcymnH4mzVl9orcGtyzKiLHQHEqQLHfvg=,iv:ZtqJgQXuvfe9eB8A6kQ6+b3q3axhBnPrrStIG5rPLrM=,tag:CwaAJ6eG8+s85svBP134DQ==,type:str]
    version: 3.12.2
