apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:t5p0xgjx2C8y/TQlm8z0+GsB27/gUdxwu5UrJFE8WnM=,iv:qqCDpmZk5egQxhSqmqDP15OIuqMYAZxw4grmTe5AFbY=,tag:mu/xEHvUmrHw+yg0x5S2xw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:M0Kwvwk1V6KwOSORG2RLOM8CI5dhP4E+QloviYUxvgNDofVnqnZHflKL29RWBbuSfT8Sw8J/3idWHzcltKCj1ViJz+/zhTDs1yZZyFbhoWACRWC4yY5ENw5CdCm2ow==,iv:QuFh5nw6zj2u0icUebD9y6York9QhJ19vt20fuosThA=,tag:Q/dDhwR6G0xUk+3IU61jsA==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M0xvT2RlMjBPM0o3M05X
            Q0h2anRFd2tYNXBOcnhDZ1BYV3dUMkZQb2tJCnNOa0FsT0JaclFiOVVWbU4xL2Zs
            dndiWUEyQXY3clZJQkJ1YUJ0T0RBL0EKLS0tIHUzOUpMTnI5cEcrMXJFOExxZEZv
            dHU5VVdiY2dPZFNLMGsyUExIY05veDAKW7R/AS5wy8plO7ufrIGbQ54EoP2dxgE9
            4oXSFAlQqGmHN/x9xva7nPXocaEmDY2zOJLWTZS4hg/WqkeIgO04/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T22:54:54Z"
    mac: ENC[AES256_GCM,data:FPNqdwUiH+nFMUuFNauOsGvtp+5ac0AmUu8QGoqwgtHl3miiGGb1zpEisSg/lweF7Xz+0H2ExHYMYb5KkG7UXjsutcFE/qslOI2AhjM64xjKvMJwDgJ8t0fcrPs0nINeJGvQa0upBFy6FZncsjhc/+n1ndhOGNUfw2whGrecAFM=,iv:WuTDoaNUnWpnkWadFkWs4Z0xRphQhgtpkawObs8bXV4=,tag:IrxzvBgWwuB+2y5EoN9guw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
