apiVersion: v1
kind: Secret
metadata:
    name: slskd-secret
    namespace: media
type: Opaque
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:G8nWQotb9OGewriX,iv:qcE9ThhfNPlG97IpKgIqwOGva+mvYI86e47QIEaXZ+M=,tag:U+Qm9HzH1ax4/QGQ+/2x7g==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:oZw6ugLlakRia2DwM//nYyo+k0e/q0k6nRXHYBo5zJ5eoBJzbS6/sJLeJ+vKfNvdXdmwM/uiSsRbZVRRAzrVpQ==,iv:V4EkIi4RlLnmgqlJMb/KYbfab49vx0Ia3Q5eGqDojjY=,tag:0l9+p5wRxnePZD9cnvN9zg==,type:str]
    SLSKD_USERNAME: ENC[AES256_GCM,data:bO42cg==,iv:G8D2l8p3YGtI3+R4OkGHAEW3t+eOHU6qeQzHYKQpJrA=,tag:N5xXdNxfjBgpAPj1yZSuhQ==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:tc1N2xbRZmARkLkM2zbGmXhYUdRgWjTM8QrEafFsU3nGmVH4AzwlsmA0eQ7QjZyZZEY6m0bFB00OmwMxV0PPAg==,iv:9VlcsLBsHUWnjFz/fnE/0gOOw6pjP1L4h5TEOfN/8WU=,tag:CZtOGlW3P527dmy6QQ5RMw==,type:str]
    SLSKD_JWT_KEY: ENC[AES256_GCM,data:8TLlXNW78qeKjDIqsdx7Iu+gbQV8NRAnPA98Q3NuVz4ptnIgu5vk1x3OJYYxVRIIEE1URRWlET+ZUVoy2EumFA==,iv:CfRykrwuqbrJhM/Eei65j7hhZ+VfeeQfg9w+te3Jsl8=,tag:CZ7eDRuiClTtSINu+EQYdQ==,type:str]
    SLSKD_API_KEY: ENC[AES256_GCM,data:uglX+rBv7GRZkMsSnPRXMM1wzy7nK14+dqsw+y7yHee1RRkNGCGjNhiy00qLGgc3lze0E3L/Db1j2wNqQag+gA==,iv:YT/POq/Y8Qtif++qco1kstytbkRiLYuE9g6KIb75UCA=,tag:MOxZMYc+vOx6xjxfk+3Mug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdk92a1lDLytTRGtHbDFh
            YnJYV0tEQ1NYY2VpamxVaEFoMmtmd2FnKzJRCkJPYUdQTTlJRFArVU1lRDFuNDRx
            Rm52Y3ZxN3JySXNoblJQWmRGczBxVnMKLS0tIGlXbzBmc3IvRW1iQ2hLa2dpenc1
            aW9LL2wwaUNTTTlzM0w2T1FIQWp4V2cKSxI5g+Mi0UP6DwIpwlxVKsakDQWL5RwU
            oTtSXB5rgMESNTcDcR35B3rgcQcZMBuWHdt6byI2Fk3lF3LsLbGPPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T11:01:22Z"
    mac: ENC[AES256_GCM,data:l1zr7PZA+QAo5W2y7lGEYsAOTo7pMyaav0pchh0EE/eo2NBt/9ySfBS/rR6bnN2KilM2f2VTt2L3Hsu/FNRd112H0gGwM2Mp1Eq2R84LYIlozOiak/PYKAZKK6AXEtrwETKVaT/GpJadQCpy1B2GbOXiWcGsXpjdVjKeAafIQdc=,iv:TdyTsDN2Y1a13mErD5QqneP6SoT0QX5ql17a/Sa+qAc=,tag:REursle4djk+Y19c7s5QPQ==,type:str]
    version: 3.13.3
