---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name adguard-sync
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: adguard
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: adguard
  values:
    fullnameOverride: *name
    global:
      createDefaultServiceAccount: false
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      adguard-sync:
        containers:
          adguard-sync:
            image:
              repository: ghcr.io/bakito/adguardhome-sync
              tag: v0.9.2@sha256:fb7224aeeab74d68990c3ecf51594a6f92428fcc93c7a162c3bc221e77a49025
            args: ["run"]
            env:
              TZ: "${TIMEZONE}"
              API_PORT: '0'
              CRON: '*/30 * * * *'
              ORIGIN_URL:
                valueFrom:
                  secretKeyRef:
                    name: adguard-sync-secret
                    key: ORIGIN_URL
              ORIGIN_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: adguard-sync-secret
                    key: USERNAME
              ORIGIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: adguard-sync-secret
                    key: PASSWORD
              REPLICA1_URL:
                valueFrom:
                  secretKeyRef:
                    name: adguard-sync-secret
                    key: REPLICA1_URL
              REPLICA1_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: adguard-sync-secret
                    key: USERNAME
              REPLICA1_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: adguard-sync-secret
                    key: PASSWORD
              FEATURES_DHCP_SERVER_CONFIG: "false"
              FEATURES_DHCP_STATIC_LEASES: "false"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 30Mi
              limits:
                memory: 100Mi
    networkpolicies:
      adguard-sync:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: adguard
                      app.kubernetes.io/instance: adguard-adguard
                      app.kubernetes.io/name: adguard-adguard
              ports:
                - port: 80
                  protocol: TCP
            - to:
              - ipBlock:
                  cidr: 10.0.1.1/32
              ports:
                - port: 80
                  protocol: TCP
          ingress: []
