apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: adguard-sync-secret
    namespace: adguard
stringData:
    ORIGIN_URL: ENC[AES256_GCM,data:xK8Lad4XFDVfejhODHX0/SafG60tnwMlNsnueQ+ZkGDCiDuMGY9MzNFn8Q==,iv:Anfd2GiRpxLknRvflykOurVleJKbP9Z9j+0LbA1eDYU=,tag:aUFzEB4QWKLhE2S7oRFjig==,type:str]
    USERNAME: ENC[AES256_GCM,data:/CgNhw==,iv:7tDD92gfPOn6JSLV70NCCYjtgJTpLSKObfq+YAOgNow=,tag:ugbj5VEjlKT3kfVXg9g4fg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:oZqXLQ/SAyk=,iv:g56lBEM2iULr8G5NZ65G8xfjZWylqk7uE7/YIjMsk5I=,tag:7agG2Wn0Trxht+g+wLOzHw==,type:str]
    REPLICA1_URL: ENC[AES256_GCM,data:LKfoXokegO0h40Go6+wv,iv:vPH+F3g9vHv17D7iFnrRTUyxQUk1kcwuyiz9eGxNzDk=,tag:0REG6raU2JWEw+zpwrMEjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ1hBTFpRd1RlZEN1ckQv
            dmpTUktsT25DcjBxUGJmL3pZbWFDNnVMa2pBCjBpWXJGQmpNNldPUVovZFdOSXF2
            TWNrWEtNdzFnR3UzL0I0RlJwdHo0TUUKLS0tIDUyRTFRSU44NDlnK0FoL1o4cGpW
            WVZZNmJvbGxEK0tuNUxndGNkYkNPZGcK22LfZu/J8RVU4kk4Ct2aEfzO7HqCDLCC
            1My8niY263/iYjsorZtuS7p70cj0tdQ/PU8cOZGobmDm4YnWNJq4+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T23:21:40Z"
    mac: ENC[AES256_GCM,data:+BmtPlsZbCXy9SXAcczePDE7+FfjPw3aV9hBeTr9h3wEgIMp7vxvZ7YLHllGLLmeiwuYkfNBg0RtpZtwAcxkV96Gmbs9aDBR+Mlc5EDAPZjGs9BqGDcjQj7YQGA8AuHP7YZxDv3eMsoRm7w9iEcGUjN3AnenTwkVTiqi9Y0Fij0=,iv:OczbtlUFa/BxE2rr8oHOpC0A8UzyzfsY3nYjQSt+3ZI=,tag:qslddlcKR2g59okIXuyj/w==,type:str]
    version: 3.13.2
