apiVersion: v1
kind: Secret
metadata:
    name: radarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:py21hG+6,iv:rQbEE2MfaEoQAi9Hh9y8ROEr3MeTbvfrNveo+17llUY=,tag:lC7kghA73WuGac8NRT+yfQ==,type:str]
    password: ENC[AES256_GCM,data:ksqFMqi3wPE13kyZttDDha4zq0523cacZ0LKJ3Cq2gDSK1KUgmFZWtcY6I3Yz595jZ9NgrExTNHOonLpk0e+Xg==,iv:O40ZYbQ+lJW3oBEwmMts4gs7mJYZE0TKKIbOo1FBs+8=,tag:42MrGC8xEouMmiGubxjZIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTk0zQWFpb0F5VFRFN3JP
            K1htWUdYWmxrd0F4bDNocGJrWThIb0dsaXlJCm5yUEJWMkQ5SDZpUzRMY3l0dmlC
            QnlPSlRXTzBBeVFTaHRZckZzUkxOM1kKLS0tIDNPb2N5RkEvdjNlcHNhODVOTUc4
            VCtxTE1adWtOQlpHTzNaRGRoa3U2K2sKS2pHdWIfzxo+XEL8SRJuIuVZ9DpwLhRL
            pOgwd1eNPZs6sPOAE5/XXVV07zFQkp8DFJJc+VzPo+VM4iOr8866bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:O6JDFLX+aXftW4WySenRRPOtNQG1iXwW/o+oj/Fqijr4GVz3WkKsb0O4Ei5ppFqOBUlxMCLxVCe3KF5VGZIfxseUNk5aass07XOsxDjelIvKR7yBMY/T+vMmzTt1PvzSdnIsU0VGy28hD6nxFNezbwJjWNOwoKQjdkJK8C8clcE=,iv:spIwkGYzEXthKXMqV3tV8Uz+NPXrwoWtJfmqSqP6bGk=,tag:ZX8OzygL8lqhGlBvqO4ULA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:CU9Z0I7IMyspiSGr22ESQrmCM+AsDqM9it0=,iv:Fu5IENAGt4lD/BHpeq9IKB+hBsfrgEI8BsJ7CNv4MCw=,tag:dO0wa+LWl4hhkFsn8k8m3Q==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:/lNlKGFyipVvvwewZ7WlizNGp7Jkn6rxWlofoQks3kVSNdUbQfmYRXA6XORTBdAvIrE133mgBQtjh5T7xgszYg==,iv:CB0WUg9P+FCMpU1umV8+cBG8ueFnmKm9g7di62WA0FU=,tag:0rOgOQVQAxCnV1YSp+aXbA==,type:str]
    region: ENC[AES256_GCM,data:XuUZXi8x,iv:2lBGha3SxlQzk/nABM1sYn1Wn/LS2HjaUPWQzEJ5aS4=,tag:UsYPzgp7FiNni3358CzGOA==,type:str]
    password: ENC[AES256_GCM,data:VTnseqWlMqGYyAewtdIeLwwNizw/JAiMLcYFjaZtybIvybWu0rcLnvv6d4FKN0ZlyRSxytaulAyiqvLmnG88HA==,iv:/snzwXWoO61D4F5S9BuUZloPPfHlT3nRaNFAuWw8Mkg=,tag:5+0AhMHRMkDSh511hPjVmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTk0zQWFpb0F5VFRFN3JP
            K1htWUdYWmxrd0F4bDNocGJrWThIb0dsaXlJCm5yUEJWMkQ5SDZpUzRMY3l0dmlC
            QnlPSlRXTzBBeVFTaHRZckZzUkxOM1kKLS0tIDNPb2N5RkEvdjNlcHNhODVOTUc4
            VCtxTE1adWtOQlpHTzNaRGRoa3U2K2sKS2pHdWIfzxo+XEL8SRJuIuVZ9DpwLhRL
            pOgwd1eNPZs6sPOAE5/XXVV07zFQkp8DFJJc+VzPo+VM4iOr8866bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:O6JDFLX+aXftW4WySenRRPOtNQG1iXwW/o+oj/Fqijr4GVz3WkKsb0O4Ei5ppFqOBUlxMCLxVCe3KF5VGZIfxseUNk5aass07XOsxDjelIvKR7yBMY/T+vMmzTt1PvzSdnIsU0VGy28hD6nxFNezbwJjWNOwoKQjdkJK8C8clcE=,iv:spIwkGYzEXthKXMqV3tV8Uz+NPXrwoWtJfmqSqP6bGk=,tag:ZX8OzygL8lqhGlBvqO4ULA==,type:str]
    version: 3.13.3
