apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-basic-auth
    namespace: sparkyfitness
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:KWwCy7qAem6niuUWrA==,iv:iKEmhRWFus2wUthk3oKFspcg2OgE4ts++AHWRWC0IVY=,tag:1Ehs4tM2Maab4JEHlfxz4A==,type:str]
    password: ENC[AES256_GCM,data:pQHYCych9/WZeQRB5+kX4bUDyYS/x3/ir1khHg==,iv:SL4prmzKNtYYNjmUT/+mgJGpfru5OLGwWlBcjt6v4qo=,tag:toE+AucYXNlI04RayevS3w==,type:str]
    app-password: ENC[AES256_GCM,data:YJLW00r2s8/vKDWXl9Zrk8NmWlWYYF6NMtedSg==,iv:e3H73/jqdMKpJVxYSeUndvDtmS+La/aJf6mDmTTeTOc=,tag:StZwM4yTJb5mhqQPt0j5Dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UzY0MTJIWkNXeEFNTEFp
            SUo3Nmx5VXVaWmozRXI1ZmkvQ29JWmRsQnk0CkY4UUV5TENTYW5kOU9VRlVpWjU5
            RFd6MjZoQjA1M0xyd0J5ZlVvL1JYRzAKLS0tIHowRk5NNGtldy8vSFY0UVZaYTJ0
            aHZ5T3AxSkFRdGFweWViNUxVOFJxYU0KydDifvFIbp4jCwk9MDbwPZz2pyAaS3je
            4sLJxRBqur3OLqgaprfZHcR97w6Qp0x/mbJwkMGohJpBBY+XWctfOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T23:14:07Z"
    mac: ENC[AES256_GCM,data:L0jmXzl4wzFRaDEYbklyzb9GpAd1E8IMQ1rUk8y11mOlVqWBfJJbUzH3Ah3IdG4eyTU2bhpuaRtmKJvxnC1narkZe1sPscjZjbcT2AiD05OyIutO4KhMrtr/ehe3GXII6BQF13dFIyetbjnXhi10SYwW3xVUxXwyGvUbkkxiGQI=,iv:MZ1vT0Hm/0gUYq9k4TpLWrUGFYfsPWcMMDoJs2yIs7s=,tag:I7s4BDXKscWrqOR/Bjomlw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-postgres-v18
    namespace: sparkyfitness
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:pQHYCych9/WZeQRB5+kX4bUDyYS/x3/ir1khHg==,iv:SL4prmzKNtYYNjmUT/+mgJGpfru5OLGwWlBcjt6v4qo=,tag:toE+AucYXNlI04RayevS3w==,type:str]
    s3-access-key: ENC[AES256_GCM,data:glzInJ8lRYtO8pz6nyAhzLQO6w+cqlnWC3g=,iv:yjjCzpJBCiaB9UfntQ15MrsIC6zgh9Jt3okBeeMC5HE=,tag:jDQKHgRbpahCpXlAyEraUQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:+PT+xRdqixZtLm/X6VwssnUCH4EGaypPHzKWksoRJ3sUMbb8I/yY0Qk7lZW8+cGAdc1+2udy47yJ95tSfIBd1g==,iv:9+a/jc3ajZnVVpWbftotRnGSGtU7Uv9AO6M+jd+dQUM=,tag:uPmtoB1ItthJMj0QrPfuaw==,type:str]
    region: ENC[AES256_GCM,data:9WjkpCbg,iv:Na/pT9l/gY3t+Kwsrr67G+mRD0it7d1WmSz4cu3RZxU=,tag:zscus1CFMFPy1lGD6FPS3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UzY0MTJIWkNXeEFNTEFp
            SUo3Nmx5VXVaWmozRXI1ZmkvQ29JWmRsQnk0CkY4UUV5TENTYW5kOU9VRlVpWjU5
            RFd6MjZoQjA1M0xyd0J5ZlVvL1JYRzAKLS0tIHowRk5NNGtldy8vSFY0UVZaYTJ0
            aHZ5T3AxSkFRdGFweWViNUxVOFJxYU0KydDifvFIbp4jCwk9MDbwPZz2pyAaS3je
            4sLJxRBqur3OLqgaprfZHcR97w6Qp0x/mbJwkMGohJpBBY+XWctfOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T23:14:07Z"
    mac: ENC[AES256_GCM,data:L0jmXzl4wzFRaDEYbklyzb9GpAd1E8IMQ1rUk8y11mOlVqWBfJJbUzH3Ah3IdG4eyTU2bhpuaRtmKJvxnC1narkZe1sPscjZjbcT2AiD05OyIutO4KhMrtr/ehe3GXII6BQF13dFIyetbjnXhi10SYwW3xVUxXwyGvUbkkxiGQI=,iv:MZ1vT0Hm/0gUYq9k4TpLWrUGFYfsPWcMMDoJs2yIs7s=,tag:I7s4BDXKscWrqOR/Bjomlw==,type:str]
    version: 3.13.3
