apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secret
    namespace: sparkyfitness
type: Opaque
stringData:
    api-encryption-key: ENC[AES256_GCM,data:EvCHE/nDt0IDOuhF5KssXWIZMj+ue4NMOz2LmjeZ/TmdYmlrtf9NYPFvy+CbUP1seVpF4JWVxWhNcoGmckr7aA==,iv:jacMnh5UXk1JHYiRrBxL32U0UMQa/MxpNNMW61hL6rQ=,tag:oUeVZiqqZ6g4fBD2m7LVNw==,type:str]
    better-auth-secret: ENC[AES256_GCM,data:XF9C7xCl0xXcKVXkULIePZEI06/FD9nBvy39jBd0YAVpa2xo3QzTYHLfF1M=,iv:7Yz+kBQR/OwrGbkkAjrxsn9ySUEEenbma61kYul7ZZw=,tag:bh7ObqsE9GntNtf/X1AHDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkNlUnBiNXNIa1p4bnls
            Z1c0L1JDRU93Nlg2M3Uyakw4K2ZEWXI2dm5zCk5ZSkxvdVZHZlV1b2g2NkE2cFF2
            UmRsTENqTS9ZVlpFY3o4eGlQVnJMQWcKLS0tIFJlaFA0NUIzWnd6Zi9adnVGcnJu
            aENBWGpUYmYraUFNNGJ1Nm1JbmVwMnMKfZ/cz8Yc3QVWRN77x7C5Q7AxPZAK05mB
            m/SzcQLmoWYFkILK18oG2rSdToBff7zNkj4eo/RPrOsPoH+Tnpuzdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T22:13:54Z"
    mac: ENC[AES256_GCM,data:TqZtTqIdg9Bd87arkD29eTrhGnDtqjYZrFt38UxHG0u19Eu/cPfrAfcOtmG50s82gvq60Efl+DrM6GaoTC7nyYbx2EvQfOK1zJ6dbK2et48BFv2dtYWsRzXPJWsOKJMD+5NvEW9xn0ZtArxVlprWJq4NwVbs5yC8rXAxSMl0lho=,iv:BAhYLdyxD9DG08FOPdIu20d2ei5TeA3HbS9ZbsV/i18=,tag:RjigtmkQLgLIF9uXpUfUxQ==,type:str]
    version: 3.13.3
