---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-exporter
  namespace: garmin-exporter
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
