apiVersion: v1
kind: Secret
metadata:
    name: garmin-exporter-secret
    namespace: garmin-exporter
type: Opaque
stringData:
    GARMIN_USERNAME: ENC[AES256_GCM,data:v5/zSOsXrJNnckv3Os1UCg==,iv:K8S4GdiHfhuCtfqvXoFQ/wN/yk5cLRPYtr5KW/bLKPw=,tag:gaLOSeTh6qb+hIPqQDYn9w==,type:str]
    GARMIN_PASSWORD: ENC[AES256_GCM,data:66iUm3tSVk5577nYlgffbT3OyhSQ0bhKorgei0mVO9e7Tsew+77Qb2bbB8OU7cd9JXM=,iv:sKKvz29NwhMDU1JLEuAIg18RqT0P/+BaB6EuI5Eq1Tc=,tag:fuleKL7RltqVFeNtTyQCvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbGg5VGYyS1lQOEVXZ2Vl
            WEk0MHkrbGpZTW00RUhibXJtVEgvR0Q3N21BCjl2RVhzaEN6S2pka09KU05QcWVm
            bzlmVEtRaVNHT3dCUzRyYlR3dDV4NjQKLS0tIGpSRW5LTmN6NWZOaWtpUWkwbVp4
            N3NQMXBxZTNZVGJWOFlLbENWeWVHdG8KMmgneaxRTAa+PCnVPw1Ez2Mofk6CK93C
            UzAsvE37NZvcKIF/1esVtVUfGJRvnQOgnt1FeDeM8J1Tt6rC8mj61Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T09:46:56Z"
    mac: ENC[AES256_GCM,data:5+cm8wA8fWm05yi0Ax8r48ybL8OCHhGi01MhocTS8rGa7HQ62PMTaF7y+EuJg/uTaZj8xmDTNf/0Uq3b1BufRrF9N0BaL1oUBl7+92MHBHqCM9R0cg6TiKTD8N2JWbQ15JxGQ1aLYdmNy3iPJAcMlitYwX5ejUqO7o4uJ9YPO6k=,iv:1XNt1KDOEcKG7RMSZiSP8mypbAJZWbV8FfxFH1iKRTQ=,tag:oHWUq0LhuPhssjFlfjbmzg==,type:str]
    version: 3.13.3
