apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: external-dns-adguard-secret
    namespace: external-dns
stringData:
    ADGUARD_USER: ENC[AES256_GCM,data:U98Kuw==,iv:zINYZg9GDlA+a58+gQkg1cqhAvxaRxMOhI7A50Z1R5E=,tag:4iNgIRjPWgKUO5ezVYEjMw==,type:str]
    ADGUARD_PASSWORD: ENC[AES256_GCM,data:W5tLiRgbuwI=,iv:1I3scaRYZ0vMz9jkz47zEmur1gT7J3cOqIUFQIwS8ZY=,tag:BNZfePUWDQohNWMi/IHWSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dGR1T3BtNGptWklvZUFn
            a1hXZkI5N2lUaVVjTlZDbWhUbDFCOVZiUGlrCi93eHpNMXVCcUJidmozZFBxR21r
            c1Jzb0hPeHNQVTdwQ1Y1a2E3bnNQM3cKLS0tIDA0UWxiUW04MDJqeFVzSjJ5RjNZ
            NUNwUDlGQkd4Wkx1KzZSanBMVmlZR2MKTVmtNfbMAzx7v2p3QLz6OxMux8HJsTNo
            hKFsp0FYS6u550/v9umxGIplLTZ29tUakMgI/Y70aCDkOBDgpJwXeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T06:06:53Z"
    mac: ENC[AES256_GCM,data:wDG8EwGsHSMttvufIddj59TEJnYaaB74JLYAJAAt6jsqw3e/ghUjPlrSXLkNi8nrAP3YljoX/3R5GBhV1B9muGYdd5Ja3ZxWvrQCf1ovUg3b5yy4uzHAUCAu5MA6NrkTHEP0Ch6HrkG0h0XIDuAptWk9DAOZ/MkQT3gAUModW5Y=,iv:91Fi+c5AQTTfJj5YTYySmIoTEQgcBqygJC8tH8Fk6oE=,tag:/d4lq4+LwM9W3hN3OYXATw==,type:str]
    version: 3.13.3
