apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forgejo-oidc
    namespace: forgejo
stringData:
    key: ENC[AES256_GCM,data:bXDPg6bpRG5oYZEhxlVeIv5X+r5/YfhA6Hs8AeO3Ab3PXxO1,iv:DCqaGiP0D9cBlEaMRqsf+vVxrsGyGa/zOeeHRKQfqKM=,tag:VFmlDNzQhvM6NmWFbngyWA==,type:str]
    secret: ENC[AES256_GCM,data:kpEk/fSXm55qgSk46zswQm236FrrYOOKY68q49Kbw7o=,iv:6meOGMiXEwGamr1IsQagzIV5V/OWAWMhz8ufkCzbeKY=,tag:ixEcip5wP/Vjh3OGHUYUKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQW1nYTBwNkkzNGNiUm5O
            cXJzSDRIbXVrSVh6MC9nYW12eFVQTXN6Z2tNClBpb3JlZEgycUI3eEdhOU1QSlVB
            N2M5OStIZXpDSGszTGd3c1Q0dWtqd3MKLS0tIGJ1Vm5KVzhzeFVJamI4WWhkc2Zr
            MEdOc1V6YS91YTE1Y3ltekR3QXFYbncKaXQxEmp5F/4Ezb0jYQYlS4Te5aCFBjcU
            Xij/uvJZFl7n4c5v9VNq2EZtaZD6hNHZv7Fpgm+HXfI3Y5Mpr8EUXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T20:19:16Z"
    mac: ENC[AES256_GCM,data:zKJwo+4ERZPaPBkef7mwOVqzdDepQz88isek6VSiu04OPTMJnZQcUaslw/gnskF1Jwjvheinn8jvMxN0+10r4TldTMxmEiGu5Fzok0jPrLpKKztKagPfZaH4KmmGwH9mN4a56MKSVcD7shMEiQz52X7LP5xh8hTy5BTQlhvQR4I=,iv:I9neVa57SrpRMiYQ+jQ0wsQuSjSQFK9xHSTv1O54hXA=,tag:RsNSJ5DTt1EAw4sIc9ItVw==,type:str]
    version: 3.13.3
