apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forgejo-config
    namespace: forgejo
stringData:
    email: ENC[AES256_GCM,data:DBsabniGtdjiG///M0XZY08=,iv:j1QO0whU3PYNp/YvnEQar+dkb+2Gl/DQgKYBkD3YxYw=,tag:2mnBtf59s6r5fvGScPNEgQ==,type:str]
    username: ENC[AES256_GCM,data:48MKbA==,iv:IN9wx+luLI8eXDdBiN5IMwQE5610RuL4H5qevR/XY/U=,tag:zhRtfURraeXczIt02C3YBA==,type:str]
    password: ENC[AES256_GCM,data:lImFJPQTVsiVSZa6hIwCGPQwDWHDKK8/wxi9uFjMZRILyDMVHw0ZDIL3OH/uv0Cn6azITc79g8Brq2YlA7lVe5LmR7Q07xFzMyG5rGsq0/lnYzvhK4Hy6w==,iv:HlhTlVJCfF26ARnZCz23OUhiqg5pOhNRc5+wni68HdY=,tag:1Ka+SJnTmGGjvPASqfAKdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvODZMbk9VekpCZFcwUU91
            VlhuOGpCczdTNkUrZWFIMndvVWt6OWN6VUFZCmkxemw0Ulg5Vzd0ZWFBeEI0bXdu
            OTM4Ulg2SDdad3VyVUdTUUZIckhpbEEKLS0tIElGL1lmbjJvK2J1OTJxa0dlV3l6
            SEZYNXB3Z3VNcmF5a0JTOXZJUUJERm8KrhTK3JK3qpeIkAq1P2PoA+JwEZkJHDAB
            NXKuVRdVVQbT5irUk0IIruxQvsnLLDqWqlNdS7FwWqJsLzZZiSm47w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T20:04:29Z"
    mac: ENC[AES256_GCM,data:L5nWn2lB1MzRS91guZVQRbGr5ARoR6QQYjFutV7NXkl5dqKiGmzBCuzwTsv+hZ6OgNeZYTzUtRQxqV0t+ReCb+4PQliEn7qT1WvSiQ6G0xm+IcI/TeRvIVG1ihjrQkVx9zSdQAxPEUbFwz53Rc8fTGgwqtuwbqYk31dNEKcAtpU=,iv:A73xX8KY+ZErmU8Ehj6CGDIjfLRPk978CvbuNSxYK78=,tag:TI0JPoz8Z0XCQ1uJiBJxeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
