apiVersion: v1
kind: Secret
metadata:
    name: immich-basic-auth
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+tNE1AkX,iv:PJSpz7MfvqNxaZfaPKd6L9W7vyS/sO2SYWmZ7f9gsho=,tag:j/jLsdnbYHdT7SZU4ls8CQ==,type:str]
    password: ENC[AES256_GCM,data:gWlrPnt+vV57Lo9/y8WlDg1apRUencoluxF+XF8yQ+DUAOlkuHGlXVtGbSU2PSUKg27AxEhUfuXrGatz2uOp+g==,iv:JfixsCQ2GU2vf2gKaeYFKpXSA0qYqKWvZwbxrxP0mxY=,tag:Z0afgS9X3Af+LHBKZZPr+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeExtaVBPNlRWbTJuUzRy
            VjNra3BDUDljSU1pdmRDMVJIK0M4Sm5UMFR3CktlYVQvVkRhR21hY1JSRXFvcC9w
            dUgxYUVaTDgwQTJoLzZld1ozUzZNTUkKLS0tICtzZ21YYktIdEZ3ZDEzR3N2RmJZ
            Q1FuU0h4d2QvZ1RlbkhleXd0WTlnM2cKdvyEPYEwI30wSegMhS8vsTa57zMZpgmt
            WJqyMXbagEbSPM5l7UuDaAu4w1ZNYht+miI6PrLmlvfZLMS7af5TDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:/VRXfYg3u1/XGexs2yCIW8FaYx1bMi8I8vvtJOldDI4ylvEfN199hCYRciy5rjla4ebxiEjGYqlE6VK6K1BPTEL1HM388ujpMZ5sCYdwvpgVs5wbkbLUNjuljQAW9drvkZooaS89hobC9lEYGHTIcUTdP23sADutNplrqvuIZFQ=,iv:H2S2ERfSLaDZzmq6sgGR3tF+AExsGf+iieRMb/om1wo=,tag:0A0hvvm6s74tHhi7IPf7IA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-v18
    namespace: nextcloud
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:k9Rx1cYYJfMZwjwO/n42Ij+C6cKccn4K8Qg=,iv:5Kd2s20CBmFxvkAeg+cqPiG8GVp7zWBmY620fXdMhNg=,tag:tTiJyTPBPrVAwtsbhSd6RQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:SVWIHg1XQD03K05aP+sp7xrVRiKCDbpqboHfLZROZT/1iu8zwMV/HRbvhDYDnCuIt5vcgdMLqVx0FQtCIx6Apg==,iv:gW8RpJN0m6vP65vqN+qYhpiMmrV7CKVrOVQWPwakuYY=,tag:DoyA+DBaEz7Vl/cOeGoXYg==,type:str]
    region: ENC[AES256_GCM,data:YFb5EbI9,iv:CzAnPGURjNLj7O2V4QB+YCsdYCwXdhw6RFHsZ1j+T8g=,tag:xYa8hWqtdA5Lx5TI8o2GLA==,type:str]
    username: ENC[AES256_GCM,data:8w4Q9zH0xLk=,iv:Vf7WrmqlcL+1aavHrBSTfVlQgK6lEuxO7PSgFFEE2ho=,tag:Wy4/OJSwUJpqVgNNRTMbrg==,type:str]
    password: ENC[AES256_GCM,data:pxq0hP0gvRFp9iDs6rVSiAF8Ao3563iphOzRe6jUJKuHFglxqDi8jYzb2FgwfaeyStznRjktSM6pVhdMV+8f4w==,iv:B4wcqVeazs9hfYRllWt5WZweICepMFbA01wU3qmWRo4=,tag:qhl/j1e3Y2CXJZK+TCJz3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeExtaVBPNlRWbTJuUzRy
            VjNra3BDUDljSU1pdmRDMVJIK0M4Sm5UMFR3CktlYVQvVkRhR21hY1JSRXFvcC9w
            dUgxYUVaTDgwQTJoLzZld1ozUzZNTUkKLS0tICtzZ21YYktIdEZ3ZDEzR3N2RmJZ
            Q1FuU0h4d2QvZ1RlbkhleXd0WTlnM2cKdvyEPYEwI30wSegMhS8vsTa57zMZpgmt
            WJqyMXbagEbSPM5l7UuDaAu4w1ZNYht+miI6PrLmlvfZLMS7af5TDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:/VRXfYg3u1/XGexs2yCIW8FaYx1bMi8I8vvtJOldDI4ylvEfN199hCYRciy5rjla4ebxiEjGYqlE6VK6K1BPTEL1HM388ujpMZ5sCYdwvpgVs5wbkbLUNjuljQAW9drvkZooaS89hobC9lEYGHTIcUTdP23sADutNplrqvuIZFQ=,iv:H2S2ERfSLaDZzmq6sgGR3tF+AExsGf+iieRMb/om1wo=,tag:0A0hvvm6s74tHhi7IPf7IA==,type:str]
    version: 3.13.3
