apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-basic-auth
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dfTFF/0iNWCE,iv:0q2lU/j3cK8WUKXakC1ivka40YNswZDpGJvsO6whKwQ=,tag:3bpGCQdTO/8NKgiFD8VU8g==,type:str]
    password: ENC[AES256_GCM,data:BKQiV/FB8dyFhVcgWbkIfBv4OWPM4MVHRIVP4ws/9xw=,iv:IDb03dLs70dfb6DdEp7Zn5rm/cdVh3pnEwpdLV0HUDg=,tag:oOMWxoBoagRLTYN4unfivQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNWJ4QVdhZFlWY0dEdnFR
            SkFjU3BCaG5RbFRBQWpwcTFSSTVnQ1lJN1h3Cml0VjkvSlVXenIzUVJialVZUVhw
            OW5LTjd2T3BaZldweFpObDBPM1VTL28KLS0tIGJRc2lFVm1CdHovU3ozUW1IR2hw
            T2NTVXJwamRJOXNpTDUxSW1yOGI5Wk0K/CeqKm1800PP2qPJ782S0uPxmu1WKFJu
            oVJ1NGnxT+L69/H/oqLeNZCYjoN7Tn7jZYO8+1cdkN5sszYkJKEQtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:+6PVQiEp9NLyWGngg7xISdXGa09W9V8xrOlPGCD7ldY6qkH1JkbKrwcmC6Sv3AI8BKzoe4fReVBHqLFvh0m5nDYTWCQmKNO57OINMmrvEx2t1C4HMFOKwaKnhIryzIn/XhvIOnlFEfFigH/+74A/GZiG61CA+fIWgeLo02DnpLA=,iv:jKZGOCNQZQF3sOT3Xpek4hRHsR3bQ2EwFCz7FJg2ClM=,tag:ofu6E/6OWkat2QgTFpdu1w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-v18
    namespace: nextcloud
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:/2ZAYkL/sp/GhSOQFKt0/cSJrmkfgGvLfVc=,iv:VRuzUFokA80GJ7QPnjJCMj0kwKWNc82anxdnde3Norc=,tag:EX8Kpn7w3je9AWepsikACg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:alWkQOYRkAY0K31iVw1uEdxdCoeysLasHTu5hMa8Q2NP0TzWdMuHah/pNEpS7PGLAwaS+VeHN+WRqa2W6eW52A==,iv:+xwyiqsb9M9TlV3duI2QgcomklOVSnFXM42FafCMRf8=,tag:GQMhjZt1rhW/nf7TfZYWGg==,type:str]
    region: ENC[AES256_GCM,data:rkLMi3kv,iv:ZXWEL2LPUcPg+KFMzv5Cuax5BZdWFZ/kQio0c0l+OxM=,tag:j7LM1E9MqIe0JjSczeM8NA==,type:str]
    password: ENC[AES256_GCM,data:gDJNNUE2z7Wly5L/AIlmvYoACTPBGGjjprbSGXtkPF0Eaa+VVaG87WOrGEkXr4+pWjZSHuQVebpDDDJJiOaJtg==,iv:Thop5snGaMpxUpHpvQz5jBEfcZE0Q7aLiEUgxD0EVSU=,tag:dgvse0APVVOLphMEe6Ez2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNWJ4QVdhZFlWY0dEdnFR
            SkFjU3BCaG5RbFRBQWpwcTFSSTVnQ1lJN1h3Cml0VjkvSlVXenIzUVJialVZUVhw
            OW5LTjd2T3BaZldweFpObDBPM1VTL28KLS0tIGJRc2lFVm1CdHovU3ozUW1IR2hw
            T2NTVXJwamRJOXNpTDUxSW1yOGI5Wk0K/CeqKm1800PP2qPJ782S0uPxmu1WKFJu
            oVJ1NGnxT+L69/H/oqLeNZCYjoN7Tn7jZYO8+1cdkN5sszYkJKEQtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:+6PVQiEp9NLyWGngg7xISdXGa09W9V8xrOlPGCD7ldY6qkH1JkbKrwcmC6Sv3AI8BKzoe4fReVBHqLFvh0m5nDYTWCQmKNO57OINMmrvEx2t1C4HMFOKwaKnhIryzIn/XhvIOnlFEfFigH/+74A/GZiG61CA+fIWgeLo02DnpLA=,iv:jKZGOCNQZQF3sOT3Xpek4hRHsR3bQ2EwFCz7FJg2ClM=,tag:ofu6E/6OWkat2QgTFpdu1w==,type:str]
    version: 3.13.3
