---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name warrior
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: warrior
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    global:
      createDefaultServiceAccount: false
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      warrior:
        containers:
          warrior:
            image:
              repository: atdr.meo.ws/archiveteam/warrior-dockerfile
              tag: latest@sha256:cdacda79bc812672975d34867e0a3d08a7681370b3c64633d413e9e1e7a9ab78
            env:
              TZ: "${TIMEZONE}"
              DOWNLOADER: "davralin"
              SELECTED_PROJECT: "auto"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              # Have not been able to figure out where some tmp/cache-files are placed.
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 5Gi
    service:
      warrior:
        controller: *name
        ports:
          http:
            port: &port 8001
    ingress:
      warrior:
        enabled: true
        annotations:
          haproxy-ingress.github.io/allowlist-source-range: "${HAPROXY_WHITELIST}"
          haproxy-ingress.github.io/ssl-redirect: "true"
          haproxy-ingress.github.io/config-backend: |
            http-response set-header Strict-Transport-Security "max-age=31536000"
            http-response set-header X-Frame-Options DENY
            http-response set-header X-Content-Type-Options nosniff
            http-response set-header Referrer-Policy strict-origin-when-cross-origin
        hosts:
          - host: &host "warrior.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: warrior
                  port: http
        tls:
          - hosts:
              - *host
    networkpolicies:
      warrior:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to: # It contacts everything upstream to archive it
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                  - "${HAPROXY_WHITELIST}"
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: haproxy-ingress
              ports:
                - port: *port