apiVersion: v1
data:
    KARAKEEP_API_TOKEN: ENC[AES256_GCM,data:wtKLWowPP4wJJDd+7DqayujiJV+OhqVYGMfA6jV6IjAFZGU2K2RjcxYCrpN0op/IGjx9A6VBbq5l68ubX4w0JmmpxSHMFeGdO1r35Q==,iv:7GYMEMqHQNv5rbQvLCBP5KZfxppG2Vm09znZQkCFAC4=,tag:9MFPPoue+W+vs5pc5u5mVw==,type:str]
    OPDS_PASSWORD: ENC[AES256_GCM,data:7rfPaNHOqAA=,iv:vn6Xkz3U9ZWxL/Sabosf4uk7zSY8JNA0HoHHcB8bCxw=,tag:l2aldX31Ypk+DTcnpyMXYA==,type:str]
    OPDS_USERNAME: ENC[AES256_GCM,data:ky8VZDTqbBk=,iv:KHF4LdjdvfkLnLyhHZJ6Ze3IWNinIJOyfD4gUFKY2Tw=,tag:cLjzZ163c6FPh4FiKwB0fQ==,type:str]
kind: Secret
metadata:
    name: karakeep-opds-secret
    namespace: karakeep
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVUVleW5oZ1h6d2prRFhy
            dTBGSDRyNjUvNzNKNTFjRGJ3aGZTQTNIMVZrCnBQWjVkNHN4bGdFZjdwTzIxZTVU
            K1pHOWtiTVZTWmd0YjZ4ZStJYVVYUzAKLS0tIGR4MXBucTZVSklZQ2N6U2YyTll6
            b0xubzkrYittMTFLamhuTkdLS3FLTE0KW8LeUo55kmzTF1pvjWUJaRgX/uLXjZXj
            odJFLavNu2rUQ0L8bZwmRve2HPX4g7awI5C5xgRKStCCJboqBUYMmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T11:36:39Z"
    mac: ENC[AES256_GCM,data:UfSX0APv1LCnvSufYCZR2zTu6ZyWO8XihYW9zVyjkWjj9EoP94bkRK0FQ3Hvpo4UhBNP6+KCqeHK/IwPkPhM3AVQoWYrG2LwOvpx7GzLh+mne8IF7ltshLgMxBeFPucFr5Hxov10SMWhBfLLQhcHtAel7Amdu29g491wBuxTB1Y=,iv:UFNWTwrB8iiOK3yxVE62OXXtDcdSbRk1rJkxcbfWAeQ=,tag:Fu2hI1wuteel/nA35nAk+Q==,type:str]
    version: 3.13.3
