apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: karakeep-secret
    namespace: karakeep
stringData:
    meilisearch_master_key: ENC[AES256_GCM,data:JoWqqw4U1pG4KMKwrJvhhlLiHynVMkKP3+F1pAokxpb2pc2wtoT9Vc8GAjoWNtOuqZSKUn9SVypOEbzJo+BlmqG2A1Gz4jrbs3dUhA==,iv:BHcwEZyvVVeokt6Y86C32wdJ8uxpuIqRS6AZcDAB6p8=,tag:rNoSl4VUHpcziThD0rPBRQ==,type:str]
    encryption_key: ENC[AES256_GCM,data:ikjTEgscuqNR9ayKZgc5kjWcjjlhi5Yvfkdo3RyvOrFMeVXmgTMY97uxZ9A96jMsqAFF0qgoRxFCrIJYierSWgAHadZufcVvdFiOcA==,iv:GJVDEwUl3DnPGnOtH2MpQXWgDk9FXoU5X8IAAcYRTJw=,tag:7U2ZDTWbnlpsVN9ZzKkQtw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:D9hSHqHcfL8NsKinxJxvRIlfDKCukqiB2w==,iv:09TUqqWNKh9b4iRvfkuRPZQmlcfEn6n8RlvxAIunyGo=,tag:hXP0O90b8ROZf9UOJJnX3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY1ZNMDNsUC9HMDNKS0lG
            dkJQK1FNMnNUNUdkNW0rUXVLczVCUkxZZ1ZnCkE3T0RmSUdadWpxelJMZC94MnVr
            bldiOGQvY04xeXlVYXV3NFNMZmorZUkKLS0tIFgvZHEyZVZjQ09yOElMelp3QzdY
            aWxMQzVHSGxaL1Z0R2RKd0NXSFBDUm8KWqAqqXkNfsTe7aU9V+vt5Smgs0w0n/fs
            9BRtYwh3MxZJqdW1e8FNeRhj5T31pRTP7oXWJ/yl/GHznQuSLlYKew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:48:01Z"
    mac: ENC[AES256_GCM,data:xI5axAXu13Xxkf7jA9S4eWNUnAdDiRI9HDTTjf/Lf7zoHmXtAyIvZPxrmoT95xAl4wRiLH2zx7DGvjntAlvv+QPnhURjQFrk5XkObIFIUeWwbk04hMMT/2AqoBn4+FraxJ7Wc91NX7UDn5dV26i/fgA8q8zwqRlOZPPnkQS0oLs=,iv:X+uzqRTS3TvMNCLjVEiCzzWqc9uIU/UjbH8OZiHogIc=,tag:LALkmAg/TD3iL7ZrZfuswQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
