apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: karakeep-secret
    namespace: karakeep
stringData:
    meilisearch_master_key: ENC[AES256_GCM,data:2nMFHqOFKoWJuw7ocazL2tsl3Op+hUFfrfNPkNn6x7XeYit4h5i73q8MA/Puty0Gf+hWNQZ9/Eie9K3HOZ8AAc8bWgiYYH+NFLeH9w==,iv:NPDTwUsp/c2nxlL4n7C+rZffFtYDU6P5UGbW9EFX9T4=,tag:W2jNG618aRdLSpR3RSegPA==,type:str]
    encryption_key: ENC[AES256_GCM,data:qnE67PdYlwwTXulhkcSNtIwjB8uiXaWDkjqi56h0gXiDWg2+63ZTscW3PhVn5ZRgF4O0xY/Jj1YRDP65e5tWX4x7Ll7eGyJwR+mTbw==,iv:cJlolXgOfINvnYrCYiqum4bmcIHnekgUD0i7kcivybg=,tag:9tDp+UtPxEvv/BYwfunABg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcXJhQmhiYmtnaG1nZk9S
            dnE0QUZEL2xOWmZwVllHLy90a3o1NlpLMlI4Clk1OCtXY2xURm5OaVJBSm5GWDFu
            UHB5SW84UDU0R1FYNVFaTm1jUlVOZUkKLS0tIFl5VFV0ZG5oT1djemFoNkFGRTJj
            VXJyWURRWE1sMFF0WGp0Q1phNFZDT28KnCKEPosUeb+sF5Ft74BBY+mdrvH0kQEW
            FRtl0X7vA9helXZXuCfu8W+lzBhGkf9dlhi/eS93hAXARYMuMn8olQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T09:41:48Z"
    mac: ENC[AES256_GCM,data:NudbWfFjqyfdVJ9sHvJH8DfWuVJ5ubVvGVY4nWw5+IXEVVsb7jwFiQDcKsS0DFBvI1gNUGwTdJAfjHKo/BiXJUptd+516q3l6EMz093GyT3iUP/Fd6e8QpGeA/86MXZ4RgOfIduBFu8QifeZMD2RpP++S1md7I5He5zKWVHA2vk=,iv:8d7GI+2oJ0WSuwkdZN2IaKkv0Zyp+rnTLMpvf2Av7sk=,tag:5INIVLthyJQC5TbrEJ/PnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
