---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name fetcharr
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    global:
      createDefaultServiceAccount: false
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostname: *name
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      fetcharr:
        containers:
          fetcharr:
            image:
              repository: docker.io/egg82/fetcharr
              tag: 2.2.1@sha256:f3cf8a850b57497c529774f9791590cf799db2173a3ba068f9ac13c6535b8b5b
            env:
              TZ: "${TIMEZONE}"
              DRY_RUN: false
              SEARCH_AMOUNT: 1
              SEARCH_INTERVAL: 1day
              READARR_0_URL: http://chaptarr.media.svc.cluster.local:8789
              READARR_0_API_KEY: "${SECRET_CHAPTARR_API_KEY}"
              RADARR_0_URL: http://radarr.media.svc.cluster.local:7878
              RADARR_0_API_KEY: "${SECRET_RADARR_API_KEY}"
              SONARR_0_URL: http://sonarr.media.svc.cluster.local:8989
              SONARR_0_API_KEY: "${SECRET_SONARR_API_KEY}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 300Mi
    networkpolicies:
      fetcharr:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: chaptarr
                      app.kubernetes.io/instance: media-chaptarr
                      app.kubernetes.io/name: media-chaptarr
              ports:
                - port: 8789
            - to:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: radarr
                      app.kubernetes.io/instance: media-radarr
                      app.kubernetes.io/name: media-radarr
              ports:
                - port: 7878
            - to:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: sonarr
                      app.kubernetes.io/instance: media-sonarr
                      app.kubernetes.io/name: media-sonarr
              ports:
                - port: 8989
          ingress: []
