apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:R+Rj3O7V1SCziFda+n3CMSsEFaDXXcCnGnhhJf3OSJcPCH3w8tDxyGBUpRf9FLGmxrbz3Ii7+YqusTswpIUkGg==,iv:Ez896+XFryAFSyhf/zdvzzZMGOCqmCt6atOydR7tB/o=,tag:Sh43drMs2lQ323xuu8msAA==,type:str]
    relay-password: ENC[AES256_GCM,data:p1Yfo2+0azfObO63zNcFQR3shfRq0wQ9mBvcIB25yU0L/uhkn1zGz6gDPFJgDNo/AUvY9roZ0IWznHIwLYZVbw==,iv:g8Q+/TUJZezS+5oQK0nIv7ZFbjsXPnioJU+XDviHaj4=,tag:znvaR9KNY93/nG2QjeIMmA==,type:str]
    source-password: ENC[AES256_GCM,data:8mo2/yEqLJFH0MzQbZ/m2hTEmsl6R8/kkw7ZE047xqLK82cSBr80++jyHLfqNlmkUE6b8A95xgsjYSfQUeN0cA==,iv:eUVMl5hXdZNnUFYgr0hZo8DMUiGu7iuv6HIeCxxwq64=,tag:IpE0YtV46T67AYag4gvx8w==,type:str]
kind: Secret
metadata:
    name: icecast
    namespace: icecast
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZzNLcWMvbkdLKzRVOHY1
            ajMwenNna2p3MFNNRkxnTnBWVDBLUElpc1hvCm10SmMwcytLQmczK3pCYTJjR05a
            YjBLNXdhSmVzazd3c2owYXdZSFRmbVEKLS0tIFl0V2RtYXozdDRvMWs3WVR5Q3ZM
            NVZiRFVqbTdTYno1cHlTSDJpeXJuM1kKAvg1R5Qafpha3gDu0fDDjziqHn+Ymwfn
            WngtEcAmsXyGOkncQPWJasBaHjuPdpzUTs0JpOLlpsJNzHbMXEF8Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T09:25:42Z"
    mac: ENC[AES256_GCM,data:tv8NP3tlTBXFOCFquNPoTrIbAb4KEf3YAqWXSMlSUWbyfJoQ5t+yM0u/jzeEs4PWngaszhlsL7eGIdmO8c3I2EWvUBzAWNFilxklPo5esKhKuKs6RbFOmyxUWSEAR49lU2Slq+DjKreOFxZe+BbSS+H2ZL2sTotR7QVDjzv48wk=,iv:MGBCwMQk/PtfFALJ8cYt62FRCV/V/r03vMbKdrd95M4=,tag:lZ1DPFHEpf25g3ox6nxbzg==,type:str]
    version: 3.13.3
