apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:R+Rj3O7V1SCziFda+n3CMSsEFaDXXcCnGnhhJf3OSJcPCH3w8tDxyGBUpRf9FLGmxrbz3Ii7+YqusTswpIUkGg==,iv:Ez896+XFryAFSyhf/zdvzzZMGOCqmCt6atOydR7tB/o=,tag:Sh43drMs2lQ323xuu8msAA==,type:str]
    relay-password: ENC[AES256_GCM,data:p1Yfo2+0azfObO63zNcFQR3shfRq0wQ9mBvcIB25yU0L/uhkn1zGz6gDPFJgDNo/AUvY9roZ0IWznHIwLYZVbw==,iv:g8Q+/TUJZezS+5oQK0nIv7ZFbjsXPnioJU+XDviHaj4=,tag:znvaR9KNY93/nG2QjeIMmA==,type:str]
    source-password: ENC[AES256_GCM,data:ZzQn2vlPJxzBpermEzCYDJysKmg1mY5AA//XsqQ/9+INzZZfqfNDB8j+tyiADKQ2DFBbgWjrYATd1XkjVKG17g==,iv:INbqLLKZsfa6uGcBG9bpYqkYeMkKBQvDlvsLK3+pyjM=,tag:359KF0ttAD4dzrYpxjuPNQ==,type:str]
kind: Secret
metadata:
    name: icecast
    namespace: icecast
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZzNLcWMvbkdLKzRVOHY1
            ajMwenNna2p3MFNNRkxnTnBWVDBLUElpc1hvCm10SmMwcytLQmczK3pCYTJjR05a
            YjBLNXdhSmVzazd3c2owYXdZSFRmbVEKLS0tIFl0V2RtYXozdDRvMWs3WVR5Q3ZM
            NVZiRFVqbTdTYno1cHlTSDJpeXJuM1kKAvg1R5Qafpha3gDu0fDDjziqHn+Ymwfn
            WngtEcAmsXyGOkncQPWJasBaHjuPdpzUTs0JpOLlpsJNzHbMXEF8Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T09:10:54Z"
    mac: ENC[AES256_GCM,data:AQb25VotuNPQx9yu3/TqbKRBf0ca5Gv36xEwSYIjBDpowc+x6gt0VMqO8xRR8bydKdqgJ3/9xCQUJTCYw8t/ra5mm1qPKuq/gTV2XYGfwWJ8iG6AC3Bu7hvt2cD15elb1uejYc41rc44NHwxLKqMf3eQcCTf5XIna+S95HAtLM4=,iv:3HNND06fdST7Mj3UAKf3qQmBtpe1A1C9o17mT01mXEQ=,tag:ReTOyaeiHXgE5bPSrShjiQ==,type:str]
    version: 3.13.3
