apiVersion: v1
kind: Secret
metadata:
    name: audiomuseai-basic-auth
    namespace: audiomuseai
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:19U3SOqRkDf8eTk=,iv:zDHxkOCgN+Adm+WddFXjYMn6ZHuQJ4jnDOu3E1gXbwA=,tag:vAZoJsdSzv41nabdAa3n1Q==,type:str]
    password: ENC[AES256_GCM,data:kpFg0BHGU88YEuRh1jnmZgcqHui5XyR5B/5Xtj4BYvK6x933Vjym1x3xNYna1vUS2uMpJeOCeAqnPxL0eL2Rag==,iv:/UWfvTYd7XZ7XIjFuIJpIfu+lxXrHWkZbpyfl/jsyXM=,tag:e7RmgqFCYm5y4mc8XfFcCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TzV5Rmt3NEpLNEp2bGlz
            NS9iMWxocHlsTnNyMjcyWEFyb1EyTFRPekVBClVoTnk2VW5qd0I3YlJ0aHd5a0tv
            ZTdBQ1ZRb3I4Qjg5QWhhL0R5RGJjT1EKLS0tIDhpNVYrT2MxMXpJVXZGck1ob09P
            ZjJvRExHZW1uS1RjU1R3SE1uQ2FXekEKCzNtenLdtAUOy9ij2QW2FZcL9Q11Mqd9
            BMxIQF/DvxkBB4XpvYIfXjVMdhgqUyEqYha8j7CMrDQAYxgu3K3mcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:s9L3kGfL8es2Qyr3e7AlzDr2TJED+AiW90q6S1IMKrT7m1lyFAYCclu7ipOJrN2fbiR9KVaZ1Ftso42qVYpxdQAsQ0vkBuytk6FoMEKzsp83K4IOHE4QpUJPoFJRb9Ev4CzuYJeAloirJCj4xPgSulCY73CgvFS2Ohbf7sNVWQ0=,iv:xH9bKqsKwsfqmXaFLSgIv5S2/HVQzGjxCGRDpO+Vj48=,tag:/L+v/ZKasTxb4Zy9Cfe0tQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: audiomuseai-postgres-v18
    namespace: audiomuseai
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:CApzDnsn8mlqxqBj6xjhGos/oqaHGkd9KZU=,iv:5hP9kFCnqGABiSkMkTyLrqBd5uZNjS4CftJ1z63GK/0=,tag:D9Qn/+IT9zg4WI0jhSVknQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:bowKU7Y3+w0UMllFFfoNACB4qBG4N9ez4ioNdTrA3i6OIDeM2gOn0GjpfIBzL3Mh9dVdW2QMFGI5e30JbbxWjQ==,iv:D8fam/riwifxvEOd5f3O5zgB7R7KCP+8E33kdsNsDfI=,tag:W3SQATsYXk464tFPPar+BA==,type:str]
    region: ENC[AES256_GCM,data:xFlkEdo3,iv:vODleJXcajLKGhHJ/EZaoD7OGiH7uxmuTkINxr0QReg=,tag:DGkH8D8B+gImgcWILcPxTA==,type:str]
    password: ENC[AES256_GCM,data:jO2anaHLhVm29+ESks6GNxqEkKCL3dcvRbcUflJHycO/fCxV2w986zS3ZRSIfX7/i41uJjk3uFL8xoqKI5cPdA==,iv:ZhJL9WFE8TE7UBap8fv4VRfKymrBcM9Dwu93a2r27KQ=,tag:flSd6yC9NjL8fUwBqCTB3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TzV5Rmt3NEpLNEp2bGlz
            NS9iMWxocHlsTnNyMjcyWEFyb1EyTFRPekVBClVoTnk2VW5qd0I3YlJ0aHd5a0tv
            ZTdBQ1ZRb3I4Qjg5QWhhL0R5RGJjT1EKLS0tIDhpNVYrT2MxMXpJVXZGck1ob09P
            ZjJvRExHZW1uS1RjU1R3SE1uQ2FXekEKCzNtenLdtAUOy9ij2QW2FZcL9Q11Mqd9
            BMxIQF/DvxkBB4XpvYIfXjVMdhgqUyEqYha8j7CMrDQAYxgu3K3mcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:s9L3kGfL8es2Qyr3e7AlzDr2TJED+AiW90q6S1IMKrT7m1lyFAYCclu7ipOJrN2fbiR9KVaZ1Ftso42qVYpxdQAsQ0vkBuytk6FoMEKzsp83K4IOHE4QpUJPoFJRb9Ev4CzuYJeAloirJCj4xPgSulCY73CgvFS2Ohbf7sNVWQ0=,iv:xH9bKqsKwsfqmXaFLSgIv5S2/HVQzGjxCGRDpO+Vj48=,tag:/L+v/ZKasTxb4Zy9Cfe0tQ==,type:str]
    version: 3.13.3
