apiVersion: v1
kind: Secret
metadata:
    name: audiomuseai-basic-auth
    namespace: audiomuseai
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:50EQl6vV0B5eCDc=,iv:lhMbs+yYBflLoEqviA8RYK5XoAo7tjlVF2dOoinR6Zw=,tag:RiVEHk9ThdzHgiU24dj70Q==,type:str]
    password: ENC[AES256_GCM,data:d6gJiqJcEzZEvlLpnipq76mstLw7yfanC3uP5sYCTu2/JEdj+ssWVPXDB0XkmQDDmt1HklpKPjMyBnRVsCvDwA==,iv:NPsSWvlN71mxEsIfD2+GM1BaqR28vz3OLa83v0LrqGQ=,tag:A1833sw/XwGUqiSBtoAmmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc0IxRkhHdXFLQ1NjcjBs
            bTJjb1FtVFlYeEF5ckhWSDREV0RQT2EzaXdzCm9HVWNhaHNLeisrdWFpV3RtRzVH
            TmtXaGZpMFdoR2FzWXVSSlF5eXpiSGMKLS0tIGZIbEI4cGFDODVJTTloRDlDeTFM
            a3pHeExQK0d6VlBSTzNnRlFZN1VPcG8Kiy0S5t+x8z3QpMqgCW1WY5A/6cLIXALf
            rps6WWry5ixGmkpWvhPKDXfKI+5M8KsyO0OKjJUcMVJuG3vpBvEnUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:44:13Z"
    mac: ENC[AES256_GCM,data:h/cYkroRVqRt0aNOQ3nje01jTcaxJnlh30KOwu1F+t/fydNm/ig4+EhWHXpVh95PHSPcN4HK1+n1eIgDGdjP8TOMKIu1RJIqdXtjU7kTb6azEx/quUoHwuFbr0iq5JZVpdj11bS/uDEruJ526w9zXelXSnm2Yzp32MMJ+XTSo0w=,iv:I8e7IzxrDZvpbZek8f4vNg+v+MDDstnpketnjdu4mUE=,tag:Di2RVqyxTMoxmADJ6kkXCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: audiomuseai-postgres-v18
    namespace: audiomuseai
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:0F95HaGtsaz/DgBugoAvthV3LAdyMenUi34=,iv:BLeBeYnj4uGzYhxv0rkmDkZfolxuD3et+BIPGuyyTJY=,tag:gxCTFhHkm2C/Bt1FlOixcg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:FB9ZalDkPYhgrvypO6gbf3huUbnIrF2nNGlL1qYJxg7OBI22YM3GKyA4n3MxGixMOn1JgUY7sKjWAVkextK2sg==,iv:I5hRO+bkFnyOBultB9xYmGT0fgNF9du1weHWV5YNxLA=,tag:Ef5tz2wFJgb7i/Wr5VoZig==,type:str]
    region: ENC[AES256_GCM,data:8VTZiIwE,iv:QC5xolMYMv5ql6xzBZXJuPKy78E6fbpTi7HiRHXG+TU=,tag:Pkobk904tw2UdsgZSEShdw==,type:str]
    password: ENC[AES256_GCM,data:G8Y/n/7Zr6OLElepHLMhvYEVv/lwlb6g9tZt+CpXuUSYpgWuRIysfXZeKdLCQX0+CAO80wgN+gUGzdF2yyIz+g==,iv:XzZWpdCjzgeRTh9nHES6V8oG2FNBjDLkQkOg9vUrRuM=,tag:8rug74O6gVTvnqSzhmxTKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc0IxRkhHdXFLQ1NjcjBs
            bTJjb1FtVFlYeEF5ckhWSDREV0RQT2EzaXdzCm9HVWNhaHNLeisrdWFpV3RtRzVH
            TmtXaGZpMFdoR2FzWXVSSlF5eXpiSGMKLS0tIGZIbEI4cGFDODVJTTloRDlDeTFM
            a3pHeExQK0d6VlBSTzNnRlFZN1VPcG8Kiy0S5t+x8z3QpMqgCW1WY5A/6cLIXALf
            rps6WWry5ixGmkpWvhPKDXfKI+5M8KsyO0OKjJUcMVJuG3vpBvEnUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:44:13Z"
    mac: ENC[AES256_GCM,data:h/cYkroRVqRt0aNOQ3nje01jTcaxJnlh30KOwu1F+t/fydNm/ig4+EhWHXpVh95PHSPcN4HK1+n1eIgDGdjP8TOMKIu1RJIqdXtjU7kTb6azEx/quUoHwuFbr0iq5JZVpdj11bS/uDEruJ526w9zXelXSnm2Yzp32MMJ+XTSo0w=,iv:I8e7IzxrDZvpbZek8f4vNg+v+MDDstnpketnjdu4mUE=,tag:Di2RVqyxTMoxmADJ6kkXCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
