---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiomuseai
  namespace: audiomuseai
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi