apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: audiomuseai-config
    namespace: audiomuseai
stringData:
    NAVIDROME_USER: ENC[AES256_GCM,data:wcGmvw==,iv:PIZAha8DKkpv6sP/4gllzaHNLEythGys2cqBRjrCEqo=,tag:1zH2yu6IRjkOxNURtFUp2A==,type:str]
    NAVIDROME_PASSWORD: ENC[AES256_GCM,data:eew15W0igmxsLn48Zq/alaCvb8OIfhkuvBWo5uXVpts=,iv:mN4YjtmcolzJnBkXooh+05gNLjkSPkOf8N6mukhG1Do=,tag:WxcjtNH3uqutcpjvkp+M1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEKytsd0FPei9IT1c5TmRt
            WnR4MU1GWk5LWWtoWTBSVm8raStlVS9xTmdVCkh3QXpDRkRPMHFKNEVydEo5OTFB
            NGVSeHE3L2tkSVZoaVk0MWExOEVQV1kKLS0tIFVIdElENWltaE03Wkl2MXdhM1h4
            S2hMRUczVXJZems3VFBMT2plcCszR3MKjo/bKeExUlh1+jJmSucJI3M+GBFNOQmB
            gUcuKyKQvRIojpEPNtKzn+xZY4zzLiZhIIvrSjaXolIqrE7Y7CVCUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:51:18Z"
    mac: ENC[AES256_GCM,data:A82TOOPyLXTJLCC0dAZ+cXquLmM0VP3g8OZFv5LUGOcwNQpAst7p0ZZF9pqGS1XRyetKRaE1KiigdQ2Bv1riwyF2KstwWbwzxBVcNa+E7Hejh6n6vTg6Z/QbI2g7HPdmTNfjfRFcEM0mIyH/owjrOBTen95KPDIhIgvmok9JYBs=,iv:GIlYKbOHRWQTdPcGWXvSwCmjpj38L4YXIQ0OtAqwVu4=,tag:K8jUjlfj0vTL9POPL3Ldmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
