apiVersion: v1
kind: Secret
metadata:
    name: lidarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qIHlDUZe,iv:q+P0cPx1ivKSJ4k/oeAqXG2wmznQFbcAcKFuozMM7fM=,tag:zCXUR+F/i8kRhXi4Yn6pLA==,type:str]
    password: ENC[AES256_GCM,data:vMQO+/wI+TLa8z7x1JcVfkuzqGke1fB9kQpO4ZmKfBPCKkkuOb1Vfz5riiGV0J4tDhROUnzRWo5GpbVUqscEHA==,iv:ZksACyzRCU9kwYpppmGdK6yIYKb9IuQqXCNZRD1CJ70=,tag:9wKrI3eXVDTHUHd1LhcI0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWGVvTDAxK3paSHlTK045
            Wk4rWEVuTkwxYVBnUlp0VGlDWEErWE9NR2p3CmhxK2tSc0YvYlZuZVNrU05NaHIx
            L3lHb29iMEdmVmUvbVNmR2ZZS3Ewb3MKLS0tIGdHYkVRTTkya1FwTjVOZmx1NEJ6
            dzZsVm5mdWRrd2NpaE91UEJ5T3dLY00KY/mr+bp9b5KlEfzH/M+Ax1AZy2+aGrVs
            JKoMkxC/VpkNI7XUxetQfL7lhx/N9m9w8lKRNkhygfLNjAVdflMHGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:x1YVGVBle2sv/znsl1s7K6C2Wl4Z2GDlzJNuHW5HkTi2s+Pncv2w2UDLGucfIIILJco0sGIc7+ZFwfJ8dzdvmuj2wCrzRAJzwfM5Mjs81smQaX59R7hQkbRH2A10PiUbGVQ9LLG7mMVXskvI6JptEjXkKYJE4ZGrsDsqYnnBrD8=,iv:v3d/APY4M3ql7xWOtfD0UK44/iUuWGspBlVHJNgNhtk=,tag:tdBwaspc/TNGtYJT5Kkbxw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lidarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:8m489vi4S1I6wMs4Nhc8sHCQP+PHvOry0/k=,iv:qwNi9flruwtNgQ8ckZKWxBzLL0V3nOc5x6/HjJ4Nbpg=,tag:JzcsFcWNuZzk7STZNev+Fw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Ns8b7hrG2sTpOIn9HW9PM0aDUdMcNGhoa02B74Q2eaj24h9DmIdjwfrITHHTAw5CtQu/rVi32qHk0byun5913g==,iv:kxODsoqm71Afagn4MbMlwWQBnNKwLOAA1TOAhWb00xM=,tag:cKvm7wZwm0PY9RZFmrb2Bg==,type:str]
    region: ENC[AES256_GCM,data:4tgPHwms,iv:djG27JyXwr+byu09aXymDeWxkqrNY7IDHHorhTD6N1I=,tag:NHPIyyTuG7gsjih01+GbOQ==,type:str]
    password: ENC[AES256_GCM,data:d2DkjehydGE92ChfWIEa/rcM4Gdda4vSHjI/5J017qtnkcVATuOjKk8iOzrZ7oOzOc2UuhHvmWEXC06eaiBxAA==,iv:q1lFov52Nk1fq5y7UkQB55PK91+2CWw3YZpJVNyWXAY=,tag:xdovJBm9cXfqc6bQPSDPeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWGVvTDAxK3paSHlTK045
            Wk4rWEVuTkwxYVBnUlp0VGlDWEErWE9NR2p3CmhxK2tSc0YvYlZuZVNrU05NaHIx
            L3lHb29iMEdmVmUvbVNmR2ZZS3Ewb3MKLS0tIGdHYkVRTTkya1FwTjVOZmx1NEJ6
            dzZsVm5mdWRrd2NpaE91UEJ5T3dLY00KY/mr+bp9b5KlEfzH/M+Ax1AZy2+aGrVs
            JKoMkxC/VpkNI7XUxetQfL7lhx/N9m9w8lKRNkhygfLNjAVdflMHGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:x1YVGVBle2sv/znsl1s7K6C2Wl4Z2GDlzJNuHW5HkTi2s+Pncv2w2UDLGucfIIILJco0sGIc7+ZFwfJ8dzdvmuj2wCrzRAJzwfM5Mjs81smQaX59R7hQkbRH2A10PiUbGVQ9LLG7mMVXskvI6JptEjXkKYJE4ZGrsDsqYnnBrD8=,iv:v3d/APY4M3ql7xWOtfD0UK44/iUuWGspBlVHJNgNhtk=,tag:tdBwaspc/TNGtYJT5Kkbxw==,type:str]
    version: 3.13.3
