---

services:
  uptime-kuma:
    image: ghcr.io/louislam/uptime-kuma:2.2.0@sha256:85d68948704fcadc7438f45c9f2666ef2239b5b84073479e1c5bc4d4d8b6d17c
    ports:
      - "{{ uptime_kuma_compose_web_port }}:3001"
    volumes:
      - "{{ uptime_kuma_compose_config_path }}:/app/data"
    environment:
      TZ: "Europe/Oslo"
    restart: always
  cloudflared:
    image: docker.io/cloudflare/cloudflared:2026.2.0@sha256:404528c1cd63c3eb882c257ae524919e4376115e6fe57befca8d603656a91a4c
    command: tunnel --no-autoupdate run --token "{{ cloudflared_token }}"
    restart: always
    depends_on:
      - uptime-kuma