---

services:
  uptime-kuma:
    image: ghcr.io/louislam/uptime-kuma:2.4.0@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
    ports:
      - "{{ uptime_kuma_compose_web_port }}:3001"
    volumes:
      - "{{ uptime_kuma_compose_config_path }}:/app/data"
    environment:
      TZ: "Europe/Oslo"
    restart: always
  cloudflared:
    image: mirror.gcr.io/cloudflare/cloudflared:2026.6.0@sha256:ba461b8aa9c042156dbd39c38657fe7431bafa063220eab8d5330a523863da9f
    command: tunnel --no-autoupdate run --token "{{ cloudflared_token }}"
    restart: always
    depends_on:
      - uptime-kuma
