---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: free-games-claimer
  namespace: free-games-claimer
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
