apiVersion: v1
data:
    AE_EMAIL: ENC[AES256_GCM,data:depJNfQvbAr5DwYPyl10p9R0KwUPPJM3,iv:9Q2JO7JnkXMZ8bHI4KdFSk45E6zOP07w6+66b+g6RV0=,tag:7Ql7ADV89jkNSjBps3UcIg==,type:str]
    AE_PASSWORD: ENC[AES256_GCM,data:Rl3LUYLgFjdkVXTfEybYnOzaTDd+4SwO4dkAww==,iv:0XPzgxYLZbGJf7ooBwSGY6yo1ucTaYqPsPMlI1ejJBU=,tag:QNq7ZNwXnHb4g1AQ0dOXbQ==,type:str]
    EG_EMAIL: ENC[AES256_GCM,data:4cGiJPtBQBMYWsAo+tGAMrmuER5zchdLrku+5g==,iv:iqI3DfDHvsl8dYP2uFomQtLHwfCJgJCeWc5wLcuUU78=,tag:zvqzHO251yUPWwj++NUHKA==,type:str]
    EG_OTPKEY: ENC[AES256_GCM,data:6CfKT/nXD+5gjTqKl8rgkbM/g4A0KLkhPKl1jwwfLdsQblzFFHNZEu1I8bL2svIIYjhXAoryTywz6dDvxZdy4yi51Ln9gguW,iv:4G+QAjx96RB8GHyC2Hn++lSAIQZqUD793At3TVohUXE=,tag:B4QBHBNptCWJXfODeTSCqQ==,type:str]
    EG_OTP_KEY: ENC[AES256_GCM,data:DwBWNYcYRPF6oo0o1fZHiNl/YlPEaQH99LY1qIeNgVoEUzTa6YKjd6fClpIQa3CH6Bc4cygIwpD6H5DpZ8dYKn2qyRELAs89,iv:dhuFQQXaWJxfiE7Jhr95gK7aMfYv1aTWCujh466Od4M=,tag:UGe7FoE66d5kiljZqQqFfQ==,type:str]
    EG_PASSWORD: ENC[AES256_GCM,data:x7DEjR+qGeBakQf55HMvkEYL+OiBfQgHeLbbr+l5duFY7y5hViIN1guS5+JJMUq3aolcvO1R1iTZF8tTrBxbbq85d+RPKeEtcdGcvIE0M/z3AdiVsHUfbO3tnoi3FIn1tG7Yo+QU9gyZY1jpTniXrTj0AKrkkk4Ek90d59sXQXy2JJfseK9MUZwEOX//8Z4VM1hHnfBGC4c37sbNZsvpcaPpYkKXUSC2ymBbEg==,iv:5ULL5xsW+N8c3THWoTFIYSuXzZu8ZBd87vYkp1NZ4pA=,tag:Z1i9wh6JyVMcEfsEZiJRXg==,type:str]
    GOG_EMAIL: ENC[AES256_GCM,data:csIVrvQYm7JFF5LTX9hT6X12iL4=,iv:yW8aFs0FpIAxbnouQjzHYg8m8ZaIRO0LhGs2uMJ/lxU=,tag:KOmD70vPaFwFZDAJm5va0Q==,type:str]
    GOG_PASSWORD: ENC[AES256_GCM,data:VypyczICJwH3aBx45oVmeTqrrEQG99ADEnifxlqC1Zc=,iv:Az+buYp0JO1Cd2SIySBJ17kMFmSypZSyQASt+kRACHs=,tag:bzcDcLLjmjOOusDVvKCR3w==,type:str]
    NOTIFY: ENC[AES256_GCM,data:SSlyT8NxZOiyacSZ//REa+Ia+02uI+zxrqC6U4aepFNxwXrNFu4dwRwcGR1aXwsMBpcXVynDk8RfEtyHCYJTLgOLe2mVdhEIyn67UBMLbW0fWrpsxefnwPyjCDTCkP5QYqbXid8ldmhxulw95WnJFIODflGp98ZGoG0qMg==,iv:d0sdDWCGlPKFfb8PUiScMt4k9KuUw74xqN/X2iutpNQ=,tag:UB8K+9sXBaP30ashENwnFQ==,type:str]
    STEAM_PASSWORD: ENC[AES256_GCM,data:P+lKs04dG4poeWkrHZMBK3j/DptfyC0EteEy1g==,iv:xWPKsUBVUJC/Hkv4k3TBu4Sazrq4sqL6XW1pTX2IhMs=,tag:oCEBzxG+rdNKsdW4mGc16A==,type:str]
    STEAM_USERNAME: ENC[AES256_GCM,data:lJ6huwKePk9jOuRRi8/SWgHm78ZDvbmA,iv:cjayABw+YPxih0rsLCbwC6jAXoiup/6uJmdztmnAh5Y=,tag:EJh2aXxweVaBnHLDsu3rtg==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:H1i52uALasavfUXw,iv:64EpfdMq8jNrBRLZKizGHdLNPKxI09h8Fpvidkq7xNs=,tag:N8VBMOTEAzh48L0NzRvT8w==,type:str]
kind: Secret
metadata:
    name: free-games-claimer-login
    namespace: free-games-claimer
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcW5VamliVWlXaDc4aGR2
            K0JEVEdWUEZSUGJOMnFOTVNTMXcxYnlpM0dvCjlqN1FnWWgvNmpQNnBnOU1pT0tB
            WlBldklCYXYzRW53M1psN1JWSUtKdkUKLS0tIGladk80SzhGc0lIL2pZMHhHMWtW
            bjdVZVdQdlFvMTMvT3BVSHF2K2ZRNjQK3g9D2U4fbvXjisZYRTEgwTcJlMNdkTQX
            BZpB/SimEEA03wnlzdVhWUdKCs07gm9aV5jcMSfF8cJ0VdA9e2/xfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T23:02:13Z"
    mac: ENC[AES256_GCM,data:BU8OUqHlcoMOwP0DacvF0r7xCtrIIf+/RDrjhatOX9xGMrLiWYzMv5jplYkDz6l0n3KdGwf3HCws0Ygoa26/dScN0zNPBLXbbVjv7is+0MxS+P/94vq5V1Uq9yoqbXF+8eBtZFRQfbbybFbNKaGBa7tPBsRBJkVyCu8trtmv6oY=,iv:UeSo0egZh935DUR57N6nBzkuKrSOX0BmjXbiAYrDRlk=,tag:vCbgXAcwLEdjqWDPVAcj+A==,type:str]
    version: 3.13.3
