apiVersion: v1
data:
    AE_EMAIL: ENC[AES256_GCM,data:B0na/4R6XkwkjuC8QiX6hC1Gxj/uaLJg,iv:NXpYYOL4kYicpJpqFsCc8OUFsXbUD3EqilGG0Bkshzc=,tag:eZW9tNrJMSha4MBsuSVaZQ==,type:str]
    AE_PASSWORD: ENC[AES256_GCM,data:C7HIT9ZIlP5UWAUKY/wIMDjU3yc1w4Z9RIQZSw==,iv:cx4Jl0LT6NEOsmom6J/WGvQ+ET0CwzZEpwC/R50g4Kk=,tag:ZZlNyy2ypBinbMU75blsJw==,type:str]
    EG_EMAIL: ENC[AES256_GCM,data:2fvfhtzOTdzuxYGlABmPwk6nJ4aViNaZrVNrJA==,iv:GtTDYQeWlm++4iQpD0p8nPCogz2yHjY3WdFiOV7ru0E=,tag:DBWGu83sP2qCkPO1J+RVdQ==,type:str]
    EG_OTPKEY: ENC[AES256_GCM,data:kakVxyNUlhqRTEhDxGAdTrMSR73hBNHT9qIam78fs0a+woqBrDi9OM85mN0hENcm/AHq0NMS7jWEAy+FJ3BqdLgLquhj/6Gb,iv:ZtI9zdm7/i56pVTRSM8W74p9iyTEopnf3qmYocPaSak=,tag:wsolucQdSY36MJgloH3Uyw==,type:str]
    EG_OTP_KEY: ENC[AES256_GCM,data:LAbuF6JuEJkbxEy4psEqTASOch4+tbQUURWk5+J/2WZNlOT10Co+qerbcgSUKIYVpgzTypIgfBzYc+HD53r+DiSZz66pGHQh,iv:ZkrNmA+/JAePmJUmhF6/XXIFrisfxEFMA5c6eR9Wqv8=,tag:gN+2zrfkqJeijEmH1Qr4wQ==,type:str]
    EG_PASSWORD: ENC[AES256_GCM,data:REcJXAlHkc3+Yxyhz1k8Mq9+FlWw+WXd/TovEasWsHFjkQ4HsWdM+EI+okWqi+rKHwrZGEKv/VPDMCZT4qKOxDwdxZWbw1h3p5qH9TQSEVKwVzZ7tIqRN1kWcjOGkwKfmLWPy4uaLVGdGgYqcuTYj8raqFtWGNh2CySjHyW37GAqqhRmKZNghQnC6Y+jxnxTyv3DOsAU0FWQT/yYpwgY0+B6Qh/jJXU0UCWBdw==,iv:fA7/UYyr8yqC3+1wiR3BcGZyKsAQjCq96lxLHBAku/s=,tag:GHPGr8cw4UXtyWbYcETxJg==,type:str]
    GOG_EMAIL: ENC[AES256_GCM,data:zNNPx+ljmULJEAxe+Q1IIHN2hUA=,iv:aoQraT9SX4NNPgYBE3sOapHQ9y4FmtNqEC+B7Jr056w=,tag:Gz96dpKYn0Gan8kzyUXgQQ==,type:str]
    GOG_PASSWORD: ENC[AES256_GCM,data:pEXQjXTyeSdaKme3a7HRKFoWoOWgL5qkYzJVSjkO0EY=,iv:byIQ7ytZikgvnBx4QEWQiqF5LtanACjXGfOQH+PvP14=,tag:MjMe2TbAQrAf1Bw3s3oIvg==,type:str]
    NOTIFY: ENC[AES256_GCM,data:A5UkATVnhqRFgnGSUkHwSOuNrwWQcG3cI3I37njboyvdRo12bKMCMYo4+TKLVeKnbarap+yVl5B2Hcz97+Sr5bhjo8ju7tVgIjLDeUcWMkrHUFYFTEuKshN6pj64KjhPUg9Hn8/BDzROtrSezIk+7EPEu43F8qENUOwJcQ==,iv:Tt3mni3z0/IMGNWe7SYIjEnr/DhD+/6T+HMynawYHOQ=,tag:k4HW7MJ7X2Ap8jzvzRb32w==,type:str]
    STEAM_PASSWORD: ENC[AES256_GCM,data:fqCIWnnYPE5Sq+uF7gv/JTzBBmuWbsH0cXTlNg==,iv:5KLrZnFGULqzxO67d7zBfWKktWLrvGo0IvzTe/m5OPc=,tag:b/L7tAV9CIsV5rDHnRM4fg==,type:str]
    STEAM_USERNAME: ENC[AES256_GCM,data:fuS0IA5TmfW6zb57DHZG2LqHARZ7+FMX,iv:Wly2XewenNUJtPF3qtA7L7JDx5w+roetBC0dQ+ipPR4=,tag:4qf86E3hvOtHyIvEXrbLSA==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:a70kyqA465bq6gTK,iv:gEeKBoD2bJKbDyXAbVb1Ld/DY57jz0Sdnxm/bpu8EzM=,tag:MvwDiJUT7rKIINUa8/ztag==,type:str]
kind: Secret
metadata:
    name: free-games-claimer-login
    namespace: free-games-claimer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSjc0MnlsUEM5cWlOZUIy
            MUZFUzVucm1TWDNHcWU4Lzh4aURXMmM1QVcwCmRnVE5TMDhzeFRNL1NaemdnNHZS
            WEM2RjdTaElTSTI3RFU3aXBpOWgxSWcKLS0tIEJici85NHVGbmVxWW1jbVo2a2tJ
            Wi9CNlFWKzBwb2JJekI1RHJ4cVd3c2MK3hUrfxUPvfD6EOtTe6hlc0FDrcTtXGaa
            PJmNv4yk061oO7LfZEVGUHkSujpLxGRSyyyKOPFZO8tGlRP8Ptnj7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T05:56:39Z"
    mac: ENC[AES256_GCM,data:+1Nri0Qtose1ZCJeHEh5pB/Le3yWX0YUf6eSCMouGWda/3sDY9mbx52nD7oztAqG2n2c7dDPSSv6AuxXsznFce66pb1inXjjt60k+Ma9GHVDsenZ2nRMqYpIi+C6MG9aajz9L+LdQGulGozYRFaURKJT2UhuiDKAdyS4/MGwaCY=,iv:/+0axSh0EKbKhpNNwgk490muJmHLPX3+N+hjgKR9rlU=,tag:YtlLoo/HzmgwUNqEY97Unw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
