---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent
  namespace: hermes-agent
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
