apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
    namespace: hermes-agent
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:YbeBKj/aJA6uO3Im1RT6TLezOqWC62qYMw==,iv:EBamDGfewaO2SbyXIATHWmXCqwu/PYq3Kwt+5a9QyRc=,tag:lihhftzNPrssB9f8wVUyfQ==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:zylsrKGotlA3UwxwJSNNo9N86YLksaUG1Uhqzw2jBrTKBUamzjqU8HTua6pUa1mw9bj6xKT3+yCSFJyWppbUWQ==,iv:RL9BkYSkHekkXx4Y09KZQWcMnTenafIyYKec4a6LQ+I=,tag:cG6HVmS4lLabpwQatKIKPg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:yRDj/Ci9nlwywzQ+viOGFQBYy5Tk3JhQx+yiA8VGBzEUhS4sz8aqH9zyJi8drA==,iv:nd3oEB+YHvU2/uzd8Y/burXTzFjTzsFvoEhrxVwHBg8=,tag:0En6ot8ihj8skmgl14GVsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMUwwRjY1VWpUMEE3OVVV
            NktZZCtEOXoya0ZvVGRaTU9qVVN0ZVdTd24wCnNyMFRMclp4YytyTEdMdkNMZGli
            QU8zWmZJQlYrOWMwdXZmQTlDN1hBYUkKLS0tIEtmKzVSVW82MHZVSjFOU1RCMGdw
            Y3Vzd01PeCtscU5jVVBJY3FiRFBOMUUKPqvpENSTCHhaD+k4SLYjdJJ0uF/Goi9o
            XCZBOw6ws1KTExzE8TTr+GyvT7mfQRYmZ97b6hIsCDtlw/6JrgWuZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T22:08:19Z"
    mac: ENC[AES256_GCM,data:7p3WzC99Iac8sHOt266f4WzVjA0NNKko/srNUNfaNaX9WRpoqOOba3+FLWFlojQhJAPPScDl4s3idGNXm91L1+6lK5OucEbCdx/vuqkAxjSJASOX4e2RJJch0mnckv1YHHv/NAQ2dwS0Upcl/q7ysDhTEcMUddvLCHXlF4lTP74=,iv:nNuCaBJrPXE2nQ1ZX19eLh0qWNHO5cISNDevt41JFNk=,tag:s87GMy++7TUTcoVrmZqXBg==,type:str]
    version: 3.13.0
