apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
    namespace: hermes-agent
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:kmfm8WLuC3qqoeoQlxgpLqYg+dpImDMvBQ==,iv:mjvuq0hQJLF2r9J5MT8iF7/mE/ie9bhukfjJIHx+9UI=,tag:JZPI62Dl2MIEvT1/d/mf+w==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:CO5SsmmpMXszeAB05qOZPt+ODRMhaXLowUg1b9y30fBs7OHRYkpgoCuWiG7Ba3aHXMfZaWXLBB3Zb9Lfp26DCA==,iv:qIa+IU69ERT9Qc8/ANxv+c+IYwWb9VuGrGjUgV11kfo=,tag:B+9dkq7I/qsgPw/cgeGB6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHNPamx2Vk5NK2lrbDFO
            TE9vVlJLU01uczRDSVhrWE1YTWUrUXZCaHdjCncxaTljcGZVTmtucDNvclRlQ1Nh
            MXAzMy9NdXM3aHJlNVFSM2U4V0UyTUUKLS0tIHVhRE53bHUvaXViK0hka3dUNTFM
            Zm52aFZ6cDhEaFord2g0ZitnY0N3SDAKe2ipt8IU3+TPBHcyR5PKipm8LgMFGtKW
            jWHMJwj7l3e14suWrVb8br58T7TvKZEtgzVpXh5JXrlksEIfJtaooQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:11:08Z"
    mac: ENC[AES256_GCM,data:MGXixi+IoHfu+Rql/4vfXTve5oMvfnlQGHmKM75yhNdZGSQJIgqZYetvQZ0AT3yieAapcZtQVj/TlYlw1v3+0lG2FtpJJtFMtu9tEeYTvsGYppyHrxGguhS8sDBhtHHAE1vW0oHC6UrjDEQiLtVQjsehW3zv2luJ90AwP/PmAGw=,iv:K0OWDxaxY6NjggJQ88LXPXcAH3vl9NqRskb9sW6dSHs=,tag:GsQoqjepHy8d7YuI3ANAKA==,type:str]
    version: 3.13.0
