apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
    namespace: hermes-agent
stringData:
    LITELLM_API_KEY: ENC[AES256_GCM,data:pHWfsp+QOs8zujXlHe7adXmlscQm66qXpA==,iv:rbI88tU4a8rGxdH1J3Sed4xn8qcxCXBjBBLIC3VllEc=,tag:ByCUxSZHCn7zKcJg0sReTQ==,type:str]
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:c4iTmFCJpjUn9Fc=,iv:R7dBYlZ7qo2k2y5X8w7koXmMMckxVraSdlXBYpXUSc0=,tag:EfxFktW1aqbiollUQ1zo9A==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:uHJrgH+kl1J0S3+ZC37zUEMdjw9JqtaS0dFByy4xgajctPMa745e+PGsQ1NfGSw3yPmaMQTAwebUCoA4Zk2USeAvoJkVNtCUUacotAP/6S8TGxGam41TkNn4Hm3wSfQtSzWeVhHHeBZQXDPr/PddW+h9E58UFrzPzUIqQsSQB6LVnZYQjCsEKPz8SdAB7c7fc2PQt+V4IMCuqrOVRjmOoPWqmEYeeNTf9/tlRdAsZykKUcDMVEsI,iv:P5Kx+SiRKW3h5jVrlHIaqZfjPRDh2ThebLPwYwWhC2o=,tag:etyV0cwmcNybDl5cDwSfZg==,type:str]
    SIGNAL_ALLOWED_USERS: ENC[AES256_GCM,data:3d9LL58Qw8rSIjA=,iv:pr6UwEwfFatjS1VB0I2073fYAPn6u9pZn/UeEPsLp8M=,tag:6oS6JBhe4fzNMKBUkp7QUQ==,type:str]
    FASTMAIL_API_TOKEN: ENC[AES256_GCM,data:/N2C08KfHXV8jC+o4xqNBxq4tMqRl6YdHzLv32Af+EueRbtu4ckLdRxKn28zAwweQnwPK0qufLrTdZF4Y2N1Jf1FaFqACXNC2776xNGkwKQl,iv:yecxwed3RxQbsiHOIYfUxECIal+G6Vpy+ZNA8PrPiNk=,tag:ik8GLMVzD3Nj8K4tO5YgOQ==,type:str]
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:cvefUjyrvVLLTWx8rF+lkwYO7VVY4RrwSmr1p+TpP7YkxV8LakiiZQ==,iv:KNlz0AWP1J2J2El5ZlpaW02yCTxyhcQ/kXeWulAq5ic=,tag:6iGpYcrU6Egdn60ZzESVqA==,type:str]
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:AU2BwM56si0xceeivsOc7pC+Y1qqcem9HsTD5aCd2fdiO5eMOAVcz+fZXaQ2c6xI1A8hNJ3co6E+W31vC+SgpVafHz4Yqm7qfR/TkjX9jjVeBtLNUFwCOehcbaDKwHFk7rqzjDPpcZeWAsM6jrY+6JxvA8UCvUuvxl8U0O608NWkHymHwy8P7T6PB/NFpUOoLEuGDy2U8Qs6eWPSxFJ2BwBW77PgQmot82I8eov+4TNnR6GA8jVQ5+6MyS8iDkmlTd3QgKtJAnngoZ+rSLhrtWuOrt2o1zP4jRRCmX/MKghRyDNZUx/sGiERkgU3lXjjyIPnvYu9bxdlmBipZn9huz0OXaXlDmD8tmjjwy4VJkJEWt9jAuh9z7wSCsYdjBYltIxI8CZFw0Y=,iv:2qzUF80SiqFgwE2iRnr+JPMusI7rjY/NMtj2sauNM10=,tag:+9x9Dh26GTIf03q79E6xoA==,type:str]
    DAWARICH_API_TOKEN: ENC[AES256_GCM,data:0T54IvwvbwBYMVpIlEa038kUj5tR9KBf1x7jQLWc0jVzNQ8WYVv+KlymL5ncoGJ0LeZc/DA+m/bTJhWTNwZ7kQ==,iv:+u6Kn1zbnwgcpkF1bmqMrh75QHFKdsdm36CSVGt7pjU=,tag:8Oo4nxdpO2IXgs/xoHXLsQ==,type:str]
    ADGUARD_NATIVE_URL: ENC[AES256_GCM,data:YvviSrkgoVQjeNrEqyF/,iv:lxovIHJTTTq8/67OS8SBxIzCHah+OayeeEXkyN/3n4E=,tag:BoIjfzeNxtnGMQF4vNI6hw==,type:str]
    ADGUARD_NATIVE_USERNAME: ENC[AES256_GCM,data:1EqnbQ==,iv:gEL4bITPjOtO6TjhmmYGhmXhNjfe3+44wibKh/m9pEc=,tag:7Dj0Fnq/pFy22xDLXTGr4Q==,type:str]
    ADGUARD_NATIVE_PASSWORD: ENC[AES256_GCM,data:eIhubpshNbI=,iv:/mO+CtonkQepnG5i8rFX9K2QoPExVwjGBmcFozKhGi0=,tag:EjOaMNhgZXozDVIplbtn9Q==,type:str]
    ADGUARD_SOURCE_URL: ENC[AES256_GCM,data:98L/WeIKlF8/wXvomM8iETD0UMn+ikPBjQ==,iv:/dFbIwhD660wk3j23oL3FKcHFVqapktbWOVqJd/c0hM=,tag:YxxwlaPthVfS//KRWP209Q==,type:str]
    ADGUARD_SOURCE_USERNAME: ENC[AES256_GCM,data:6m+BWg==,iv:ES6i8BbS2h2t9WBZhh/SHG8oDyrNGnWu314aE593060=,tag:dr0KTemfF8acbTqXb2+6Fw==,type:str]
    ADGUARD_SOURCE_PASSWORD: ENC[AES256_GCM,data:JbfCzKFlznE=,iv:PSS+JaX45SWJVKv7NG1F7TGg+XFJ6fEDCeiBvLatMxg=,tag:YvISignYT5GMoOZaUa2W0A==,type:str]
    SPARKYFITNESS_API_TOKEN: ENC[AES256_GCM,data:ZiJj8a7hn/q5StWXWgt5FB49/y+bdvLNbwF+6/ktQ9XMGYkpRVaOCMlDgbNwDRccKHXTx2aIsCyM7eg25VvFIQ==,iv:flcEfczCbgRz0uKKxsha/Lpjl9mK5pyurliNz5R6das=,tag:ZsnPBU6/cMnNIkOCTT376g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZXFWelV1VkQxWk15RjVh
            c0tDTkNaVUNRdFovQ215QlNTRTVjc3UwQ2wwCjdWbXBvODJsaHRCSWIveVRZbjVX
            M1IxU2NYWmxrU2VGV3ArbmZjNTg2U3cKLS0tIEY0ZVAzM05Ob1FpVDlXT3d1WEVw
            Y3FyeWZnTGJEMjAzanppOUo2N09zM0UKkR3mxdAGggwn9IjbPQNevUyWj17TOvck
            9IUhB+j9UbW5xizVN32KTCBX5H1/Zne+sJUsmoWq+jqJnkLHohGVIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T08:50:15Z"
    mac: ENC[AES256_GCM,data:Rre2Ps8+41RtDPNucRKpfUqE4iyREfWDdURSiUEK8LRaYTcsn7w6OBm/BzSi69cmck+QixTHcDuOvZn00GmVXXmo3m1FXWxnZSm041uJNsp5wZ/tW85uVwPQYJwx+eg25fBlqZ02rgnCded8MhObqENG1tXPARtm3b3m9cbDFbc=,iv:p/ZLkGReiB4M5NIk2F5Fw9nPTRAiW+Et1j5JlclBhPM=,tag:iI5qi/FkFtuqGa8Fquk/HQ==,type:str]
    version: 3.13.3
