apiVersion: v1
kind: Secret
metadata:
    name: sonarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:7pV2tLJZ,iv:ooz1YVtP0z7dDl1U2SJ28NeAmA0SMuEWt51O4K9K8go=,tag:P42D1jhBrwiNFlHOyl+R4w==,type:str]
    password: ENC[AES256_GCM,data:3J9dHTPMLEPJVy725W4eub2YLCMlsnEbylN3gYbrdCoCSHZS6T7DPCDyDUwL5eeLEOyl5AWrqELYtnW8vpDH7Q==,iv:1NtBeSVrE7Bg4BfDsF+3mI2n5GbkJPAdWRr6mtKRois=,tag:MfljKxudFV5orfzPgozPRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSFRzMTdNRGM5RWVvaFRT
            TWh6U0pPOWF3Z1ljUThaVXJ5RzJPbUVpWmtrCjN0eE5KNDg1QitNUHhZbzZhYm4x
            QXBtcktBczFjZmRrVTdPSUlXU3N3YTgKLS0tIEVKU3VhdEN3bGZwRGdubUtCcnV6
            NWhqVnIya2NkS0pzOFhoaitGMWkyb00KU3Zi9xrOY7lb2ta5AQF2DFv8+7qv4kCg
            QNvHmH7GQCfJU/Lt+IaQPp89Qb+LN5y6qNYBo3QnkGDV6lSRfKWXDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:Tf/YT2+bDkOP3PIoMiBTicc9zbhrpLOofvxcQ3y4sjwUdIp2r74ysiItXnJkMLeKgf2/Nlq6aWBA8OBBndwkezSL3NpeyPWFxyh4S/HlGCcqO5UEyncLimmUFVOvMdLAw61Y7NyRlJ9m1LVEhZdiRI/DfOs4kOcAc6tfJxrmmHg=,iv:47VkILpFRDjhdGumEcD1rn9GUpDyJQQdlpTgWOHEaH8=,tag:RRmOGmfOYJOcr6vgkoTMAQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:GacV+RUi1eb4/W5jCbniGWzkA3UAyxj57DE=,iv:z2rACMEn2FsxcavIGmD0eI2QfPCk37e7ZsLWIiWUh9Q=,tag:FMcoljkQuMWfeKtE18AYTQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:mCoXiYjd4aNvIQrL9shACEIeVqpJyswUwtyoGHsWi7Kajowqr3TLEW4WBQh8nsU0+Xy9EGIurBjFQs6xSwGOFw==,iv:cnyJWqtvPRevvY1eKfyKwm+jfw74haPNUH3/8nzA6hM=,tag:T4mRmiJ10jaXv2o/YWRpYw==,type:str]
    region: ENC[AES256_GCM,data:dRSVULoP,iv:kxH6zEWLwEElSBY6Ee1t7yJjkjWZZXXxDNxxtaSZdjM=,tag:v2r8hnwVYQEFXmuLgRVyLg==,type:str]
    password: ENC[AES256_GCM,data:sgps1mZx0pE3c3gXi2lkUPe7ZnD3l3pVgaJRdoLOUa4KuOck9SNYi8I3XKDlcln0q5zRPJ1CQC/EnR+W47STjg==,iv:fbsYgW1Ka3RmJ6E0NduwcOux5tTsg3ERc5dnJdFXQIM=,tag:d44YzUOqucs4lxLYi0R9aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSFRzMTdNRGM5RWVvaFRT
            TWh6U0pPOWF3Z1ljUThaVXJ5RzJPbUVpWmtrCjN0eE5KNDg1QitNUHhZbzZhYm4x
            QXBtcktBczFjZmRrVTdPSUlXU3N3YTgKLS0tIEVKU3VhdEN3bGZwRGdubUtCcnV6
            NWhqVnIya2NkS0pzOFhoaitGMWkyb00KU3Zi9xrOY7lb2ta5AQF2DFv8+7qv4kCg
            QNvHmH7GQCfJU/Lt+IaQPp89Qb+LN5y6qNYBo3QnkGDV6lSRfKWXDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:Tf/YT2+bDkOP3PIoMiBTicc9zbhrpLOofvxcQ3y4sjwUdIp2r74ysiItXnJkMLeKgf2/Nlq6aWBA8OBBndwkezSL3NpeyPWFxyh4S/HlGCcqO5UEyncLimmUFVOvMdLAw61Y7NyRlJ9m1LVEhZdiRI/DfOs4kOcAc6tfJxrmmHg=,iv:47VkILpFRDjhdGumEcD1rn9GUpDyJQQdlpTgWOHEaH8=,tag:RRmOGmfOYJOcr6vgkoTMAQ==,type:str]
    version: 3.13.3
