apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-basic-auth
    namespace: lubelogger
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OzJRhvVN616HSA==,iv:NOUuOCQnKkJQ5F3X9ZUZkqaHWD3I02PjjjdVSkQmluE=,tag:580WIb9ytUpayGexdskr1Q==,type:str]
    password: ENC[AES256_GCM,data:XP3tahzT4ZMHI8v3+JsHq+KWSe1iXrN9cr4PkxtiVZnu/ruUQzgVwgI=,iv:5ldNWv8bDsZUXsSNFMEEbir4uN44KC2EWnVII/rVukE=,tag:TkGvSmQjtCJnFOkxJsJk6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscGFGQkhnLzVZeHlDSW01
            Rlk2Sm5Wa1Jkem9hVnlqc0lickNsTmllV3hjClE2S2N0U0huZ3JIaVpZaW9vb0NC
            S2ZlSzcySTBEeU84Q2F6cDFTTloyZW8KLS0tIG80QlBITUYwYmpPSCtNOFFLT3JY
            MEFqODFyT201azlKa2t0YVlSdHl6NEEKHwWmhGyBifLsOSn085H/ItTdHeDRwMpF
            gyCe0CAHD1LLmMnjKuz2XttCFRHGh3TznntKjlck2nGip8ITbv12kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T20:44:58Z"
    mac: ENC[AES256_GCM,data:EdV+Llh5yvDqDg274ou9gLoOTN2LbVF9ThaG97sBmmMHAdd+NN/tfznZZ2vvbsp0DdT+rJ+WBoj6ACNOpg5a1dpXCDbBObUKYtew6EIYgtrgoJxTRFvWAc21oGmYHRqbTadFREarao1OhLBm6lJHM4RtrcrFM/Ef9n8OGv/rLAo=,iv:aVGDHTv8lYFvEEyNd+JwfjBYUgPonKKL4BN5c/ZQG6Y=,tag:eFa6eS4p1XHDiwPtqd3glg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-postgres-v18
    namespace: lubelogger
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:eoJkHFRqD05P2AvLdOQNwg+XVZvL6nC83oU=,iv:m2nHrvLiBY9z1XdhQQyiLnCpxsPrIlnIPMV4OkeF0+U=,tag:M8bmYiX31GVFe0oYnyMTwg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:sSSqRikyPcco1ZbXpjgVv5IjcvwwE3AZ1ysvLFPKlcgFLio+BsdNp03/6T59TvzBUbuswSnsNIUpn2iKPRJuRQ==,iv:8ZRZX3EmDufaSL7keqHapfEaggcVBEcNnYl/wlBOz/M=,tag:01UmV3+pQu387oxTT2wpFQ==,type:str]
    region: ENC[AES256_GCM,data:++PKR/ED,iv:WFKI3hxKWbBdPLdc68RXYy+9O5xQvc6cVvwM9Id/faI=,tag:jkrFznHWFW7Mkf5z4byy9g==,type:str]
    password: ENC[AES256_GCM,data:mDXkI6dvW8l52qeEv539C4+2yQMQUVM26F10aGV/LRAzS0TZHlsxeas=,iv:ppNlKADkA/V802pMedqFc6N2SFjiwV+Bo2JAuyyJDIY=,tag:w/x45wlaNXvpBOpBEc2Oaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscGFGQkhnLzVZeHlDSW01
            Rlk2Sm5Wa1Jkem9hVnlqc0lickNsTmllV3hjClE2S2N0U0huZ3JIaVpZaW9vb0NC
            S2ZlSzcySTBEeU84Q2F6cDFTTloyZW8KLS0tIG80QlBITUYwYmpPSCtNOFFLT3JY
            MEFqODFyT201azlKa2t0YVlSdHl6NEEKHwWmhGyBifLsOSn085H/ItTdHeDRwMpF
            gyCe0CAHD1LLmMnjKuz2XttCFRHGh3TznntKjlck2nGip8ITbv12kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T20:44:58Z"
    mac: ENC[AES256_GCM,data:EdV+Llh5yvDqDg274ou9gLoOTN2LbVF9ThaG97sBmmMHAdd+NN/tfznZZ2vvbsp0DdT+rJ+WBoj6ACNOpg5a1dpXCDbBObUKYtew6EIYgtrgoJxTRFvWAc21oGmYHRqbTadFREarao1OhLBm6lJHM4RtrcrFM/Ef9n8OGv/rLAo=,iv:aVGDHTv8lYFvEEyNd+JwfjBYUgPonKKL4BN5c/ZQG6Y=,tag:eFa6eS4p1XHDiwPtqd3glg==,type:str]
    version: 3.13.1
