apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-basic-auth
    namespace: lubelogger
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:7lpMJFybKzMtrQ==,iv:KTolzaqMl3MQfPXU5qGZIX624OLEyZmDIF5H43fJtGk=,tag:Dc2iDIYPIQpNlCCLov9QNQ==,type:str]
    password: ENC[AES256_GCM,data:eI440PRxrsDzGAtzkdwOVuh3qi/+DQZfY1R7pz+7rgb0DLyf0f2RLlc=,iv:EK6yHp1PkVr4zeaTKsjUAAkLlhA3bwOqTlMqD3l4DZ0=,tag:ka+7HJh1XxMIqJlzD19aGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZTNLMkZIRjN1RjI2aEZk
            bWQ5YWRRSGp0Z0hRcjlUMTF4V0RrRmZsTHljCi92d0NnNG1EYzBGTlhiV1p4N3k0
            dmRFOGIrS1RVR0hSMUFhaFdoRjY4dzgKLS0tIDRGZFJWczd5a1FvSzhJTEY4MjRj
            cytsMmMwVllqRXhBR0JWOGs4T0Q5SEEKvsyOjcEgcL0xyuIWcGDzmYb6FvSebmgC
            Sk0+EUXQfMbkPekUiqp0FPfe7WhNcOJxetYs33lpwFgeyAIfFxIUbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:qtb2zJcl6yqxfO7q9tyL337LbANw+cBha79oWXYg21ic/qw1CWeC/OxrMCeTtvFEmrqXn0lAgeGkuODXdyagyikbOLmkFEzmlp+Yvd4Twshqfvy9LIApEQdFOSKCYdznJu5KtAcnTUd9UXNKD/Y3CfGj+k1gUogX/4DR1qVhzdI=,iv:CowM0GoZkg4Ze0LI0nCzFZ61/jXYXyB05Bb7/xl4uGQ=,tag:WxvHiyO9PP0iAyd9cfx3hw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-postgres-v18
    namespace: lubelogger
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:3q4cnYZMfObTbEbnzQe9djHRhvXCzeTobPE=,iv:43S0bkN4wBJ5+i5SemOcHIoki6i6UTbBvgC+W0GV4ME=,tag:WmeFME/X4KjVafkeM9PH+w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:5wkQC6WuWCZGb/zYwIPtOqFFzVFqDn85KpIEaCtSGupOb209q3Q5eBDZzH3MPqnJ4NKh6IJiHz5ut/NYIfkXDg==,iv:ULrrEyL9eUnwaF9VqcY6aIpnEAs9h6lse6PiZlTcGzk=,tag:P4hmWsIBglVj2hErtD6FKg==,type:str]
    region: ENC[AES256_GCM,data:5pzhQ8aF,iv:5GOzYtd+KRUdxJYgdQv3toD2rN3Pf073C4Cxu5fUnDY=,tag:868YoqpAfx9eHS6iDnUI1A==,type:str]
    password: ENC[AES256_GCM,data:hzZ8SMM84UiJQ7FE2Ou6ovxMrIeJXjPfKysSTmlRKc7qPlF8S6MQkbo=,iv:0RksOJklzuOj5lYuG36dNdVcmech1dCI4SIeqSS7mQ8=,tag:a/EpyLbcuaKy525B/c+s6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZTNLMkZIRjN1RjI2aEZk
            bWQ5YWRRSGp0Z0hRcjlUMTF4V0RrRmZsTHljCi92d0NnNG1EYzBGTlhiV1p4N3k0
            dmRFOGIrS1RVR0hSMUFhaFdoRjY4dzgKLS0tIDRGZFJWczd5a1FvSzhJTEY4MjRj
            cytsMmMwVllqRXhBR0JWOGs4T0Q5SEEKvsyOjcEgcL0xyuIWcGDzmYb6FvSebmgC
            Sk0+EUXQfMbkPekUiqp0FPfe7WhNcOJxetYs33lpwFgeyAIfFxIUbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:28Z"
    mac: ENC[AES256_GCM,data:qtb2zJcl6yqxfO7q9tyL337LbANw+cBha79oWXYg21ic/qw1CWeC/OxrMCeTtvFEmrqXn0lAgeGkuODXdyagyikbOLmkFEzmlp+Yvd4Twshqfvy9LIApEQdFOSKCYdznJu5KtAcnTUd9UXNKD/Y3CfGj+k1gUogX/4DR1qVhzdI=,iv:CowM0GoZkg4Ze0LI0nCzFZ61/jXYXyB05Bb7/xl4uGQ=,tag:WxvHiyO9PP0iAyd9cfx3hw==,type:str]
    version: 3.13.3
