---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger
  namespace: lubelogger
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
