apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-secrets
    namespace: lubelogger
type: Opaque
stringData:
    POSTGRES_CONNECTION: ENC[AES256_GCM,data:Ws6Q4XMAvYgdWR79DDQAseNIlWiAkRIo4GICHTwyq/EgAvAT1LmpoYpUmLPo4ypvfzB95fSBG+vxnS1ioItrdVOuqrUsASkRw/s09HmAXCJiKkkrHJXJQc6aXh/SorwIOjwwFhdx+X9i9eOsqPosdWw9/NpYAIUIrLYMkyHaPbTo7sWrOy3riwwqv9l8WSkedqRHfXF4g34flGT4,iv:vn7bCc8ccNzXjeXsm4wZC29FWLdHCvuRLL7EWPIS+pA=,tag:jgU30l52kgqgJNFTdQuFvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaklKb0Z4SFF0dTJOa3Z6
            ejBHb05EbHQ4TTV5MkhOSWhwalN3UWhnbjJZCi9FKzl0SS9sRTg1M1dnL3IwdnRB
            aHNJNndBK2NYVlZCRi9aeWZlQ0txRFUKLS0tIFhKb0E5VlFmSEZFQkFpYzZLZ1Z5
            SHZLNG5CL0xYWkprd0drS0FuNVR3aWMKf3CtGF4QNsW0Nwah4l+ZHJffI1CNK+wq
            D+xm+MGbtdwU4HfoeJHYa3uBmhwT/RWp3ruq8Acz7XAn77woqn95Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T20:44:58Z"
    mac: ENC[AES256_GCM,data:Spghv6Yn8SEQVg8Ap/oNvm1I+ZpNbr4n4aLXMTl9tBTr5w+hY+l6BB8zRNZklioEdqg6xT8KN28r/ra/njVllJ/75X4kwYXDoOOTpC4rcXOZZVn4WqHfA54YRH4uRYOMWzxSa4zYCs6hJSRhGaxCzjnesaeybYidGXm6HVvLHeg=,iv:5+/PeLnh7gYuo1AVgw4RKBItKy+PtRLPHegSlK98WqY=,tag:H5oc1QRNj8hgbA8YrpOZRg==,type:str]
    version: 3.13.1
