---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cloudflared
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: cloudflared
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      cloudflared:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          cloudflared:
            image:
              repository: mirror.gcr.io/cloudflare/cloudflared
              tag: 2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
            args:
              - tunnel
              - run
            env:
              NO_AUTOUPDATE: true
              TUNNEL_METRICS: 0.0.0.0:80
              TUNNEL_TRANSPORT_PROTOCOL: http2
              TUNNEL_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cloudflared-secret
                    key: TUNNEL_TOKEN
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ready
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 50M
              limits:
                memory: 128M
    service:
      cloudflared:
        controller: *name
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    networkpolicies:
      cloudflared:
        enabled: true
        controller: *name
        policyTypes:
          - Ingress
          - Egress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to: # Cloudflare
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                  - "${HAPROXY_WHITELIST}"
              ports:
                - port: 443
                  protocol: TCP
          ingress: []