apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:sX3MNioGoCAIuIuKys1Z8aWAYlIcEMnbGhslEguMIdZpUhq44UbhoT863TH8RUQgDdgYc+ujPpnptlcCMPhTVbKiKIR4YJktsUwxPqrwe0VQkAGdAaqTXRCkgBQzSQZKBtoAA2l5WXBz5QrRwrCs8CksjqOdnweS9USBwDm/PUK9dNegypb9ErgWIn10qwaoCV8l4Bu3BAUQTDkkBlKI+NNsNZH2jh8puPIy6dVyk52/YRGoF1KcUA==,iv:itqqvoHelflssCJfk+ogmWsxwbwR3P5TzGiqMW5yzzA=,tag:wakew8fVFRzdB1dDJINPXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb29EL0hEZHp3RW50aXdC
            NTNzR2p1eGhCMDI0ZDZPa3IrNXMydVMwU2hBCmtpZ3h0dFBCVXF0aG11ZGhVbnRJ
            M1JBL2xDVEhiNE5VdExPWTdLUE14RzgKLS0tIFhZbGp1VGhaK1Z1OTY2VWlvL1Qx
            R21OajVMR1pWV0g0VEpxZ1d6cjVZOGcKnPMXt1RdMVEZcUh+/0RZ0VfvO4Jh6jhk
            FBh2u2ibXWj8nvzoUzMJgYM95CGo+FtE0JA0U398dOl0iN3YDmKNbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T20:27:10Z"
    mac: ENC[AES256_GCM,data:tC6aT5TqmUBnYmuTNmya93Ptt4kXCfNCEwtYSXJSChuQqw26LQwdI5LpNwZAeT772BsEOTJUFanmh0WEC1l1uXHg6q2Bc24ntfieRddjK9GeA5XnB7Sf1dwhdBtKFqGi7Ujgc+G8jyQGOV2hc0Y8D2HwqpyWbRNIET80KskbVfs=,iv:6Sp6+n8cTTMof8J1I2aHF+ag9KMM+4fqoBVgyW0jJd4=,tag:5/71IuKI1wkyBOITJqVwxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
