apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:gTCrk/Pp3yoDRVv/BzvbZCiDIib0I8H67gWC6Uls9q0SLXsvjh9HMmAq8We+6efTUgQDPE+CIHV/YjbaJxf6t68dnd30nvhfPH9dfwhPzIHc8FvK9ftsHv7hwrsdtgt4ZAC1iBLTCO7D4Jil43CIlxpy/NtZdaykrDQOEpT+jIi6MqHZbtTmKl3+JLMMhYYNL+mA1SbfadKC57OfNdKwybMd3e5fry1Rsxwu9AjWO6zqita9hiTBVM83+cEUY+25AA+/8iOheuHJgZX4p7OEe2n28o7GgGEENilNVqc1qcvhPy3AJLrnr9JxNE76fh2c+FDyDVWeJtM=,iv:6fB6af7A0KxEilf+F0xj2BNz+GjGEHQltawNzo4h+Nc=,tag:BneroHQuSJOzRVjy75NRLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TWd3SDQza0dQOUJ2bVMx
            bS9VbGs1WlJaUTNKZGc5TTBQTEtvbmdkRDJBCmt4SDdZK1ErRDFRdVNKZzF0T2ZZ
            d1lqOHJsQ2JDWkN0WWtjdjdBTGNLbmcKLS0tIGtaVGFjeW5XM3hGRk9RanViUDNo
            RXQ5U21oeXd3ZFJuM1A5UnU5czNaMEUKxtlqxhHZpafSMrMrD26swH65YWyylpbB
            5rjbE0iFQl+I5wCfIimvB/rJTYcfSvfEdrB2VFyG2P9Ihfv96cMN7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T20:43:32Z"
    mac: ENC[AES256_GCM,data:9xZ5ehabhG9P56TwS8OLnQeDZy1ludzOZeN8E+jjf17X5WlXrzEOwfHG3SjnPach3L0j+Q912NGmkmIT72tDcINvW9GeQE9roUWE/7zx8XrhQc7Xmy/9aQ9v3CDMcihrWRRMFUzBcyzNp8tm7p3F3AZYNfCIF9uF5betTek8Wbw=,iv:bO2z3P63Ggvxd3P3rZ9+nEbYnRa4RBWp+UwHF5NJUxI=,tag:GDl6idCWhmEg7PPY9VMkfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
