apiVersion: v1
kind: Secret
metadata:
    name: spotisub
    namespace: media
stringData:
    SPOTIPY_CLIENT_ID: ENC[AES256_GCM,data:l1o0RWXmbpPtGbPCXU3Bp45Ud+UT8n/FP+lWkzIoteo=,iv:lZFB3wtzE54f/Tm5J6AABbA9c+mIIJmPHaDk39MPaOc=,tag:hQWTVWrzinI8pD0SQp0VVQ==,type:str]
    SPOTIPY_CLIENT_SECRET: ENC[AES256_GCM,data:m7exge8uztS+pDGdD+rNpF470bI58iRC+n7cZPuwHuQ=,iv:geYoyDAcvx37wBxeQphyoQ5R9jqMKqNGc04LepQFc8k=,tag:l/G1ag9dh5NXVZgZ3fx/Uw==,type:str]
    SUBSONIC_API_USER: ENC[AES256_GCM,data:DYQAPg==,iv:S55SX/LMEtcVWOW6vKwzSkh1c0MMt5yvqYqEBenddus=,tag:05Oqv4xcG/BEIpCYkX0sJg==,type:str]
    SUBSONIC_API_PASS: ENC[AES256_GCM,data:XsisySYHHXgjOUQP7xIQcm1CI904HpW/I+KXx47u4TM=,iv:6ktrUvtmxZiFU2yHU8butoy1Jd/rYONchTz5N458B4M=,tag:XA6MUQvm1zTLVSCmUZBjgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNmxiZGFMcFUxM2ZOMW80
            YWlEb1VFNjljMVZsNE40NUlTMFNxQnQzc1FvClRQc2dLWUJFQjFKRWZMM1JueHdE
            Q29TSkFVa0FpR1BhdFFGQnBWa0tsZG8KLS0tIGVrVC9zZ05ncEJMdTBYVUNnK01Z
            dVhiM1E0b0t2ZHV2UUUzTUFOejBCakUKQG4FoSJagR8P8QuDygMm7UL1DRLgEApX
            JCKN5Ndh6nB9lEW/6BvJ2M7ukhnTjrC2hokT6jftSc7X69qBjdvk6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T19:50:27Z"
    mac: ENC[AES256_GCM,data:tFWGmhjXdYrbLR0772adY31Pcvmpi2EaOvBVGQ4E3WOZd/Q4jguOxYsKG9SOlPRZTaZ3IDjGyAVJ2hg3aNfv474yWsUbLZ92HCt9b0rMnS3Orz887hvu1jYtCIBkxpvDj3WHR3N3tr46fIaYc5mXudKU30hZf18WOXT2vivSA8Y=,iv:vub6hIshgqzg9D/rjGg5zP2Dy11WdITNhKjUpNOwf3c=,tag:xS+cFxvAmbTbNdBCHr9UNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
