---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name kubescape
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubescape-operator
      version: 1.40.4
      sourceRef:
        kind: HelmRepository
        name: kubescape-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: kubescape
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    clusterName: "${CLUSTER_NAME}"
    capabilities:
      relevancy: disable
      kubescapeOffline: enable
      nodeSbomGeneration: disable
      runtimeObservability: disable
      networkPolicyService: disable
      admissionController: disable
      seccompProfileService: disable
      riskAcceptance: enable
      prometheusExporter: enable
    global:
      networkPolicy:
        enabled: false
    excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease"
    kubescape:
      serviceMonitor:
        # Enabling this triggers new Kubescape scans on each probe
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 4Gi
    prometheusExporter:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      serviceMonitor:
        enabled: true
