---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-cli
  namespace: signal-cli
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
