apiVersion: v1
kind: Secret
metadata:
    name: signal-cli-secret
    namespace: signal-cli
stringData:
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:3FbnNe7xLIKtxdY=,iv:EZpUaj9TOh2Bc6+7/3s2fnuN1YfNg1MAzpI2mz62O0Q=,tag:ueTdFGv5QkKVfLFA+E5b1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNjN5WklmY3IxOXVjeUs4
            empUNWxoeTZ3ellGUThGWXNDeXBZRDVwMUdnClRza1NaVExyRWtBZXpxdllXRmJp
            TWt5VGZ5ZHFtUXNlUnJSMFgzQWFxMFEKLS0tIHJ3M2xrRFZwc21pQWxYVWp6a1Fh
            c3FZWHhXZ09WOUFwQUhrbHZLVndjeUUKDr72def9AyXWPZgVzLHHz53KMmBjY0Lv
            VlB4EzV2Cd3sX45BNIpC6DkH6meFQPyurT3ud/hjz4xBfmTKOKYQjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T00:13:04Z"
    mac: ENC[AES256_GCM,data:3Nx8cDkzlGrMQPgFTponBcjUobA9FlZicpCSoV+Sgojc4dEEiPM9Oif0AsVCnfZBGWr6ggtQDVBoBGpO9Ah8yIqKG8bDlBBvT634fcLw0kwRf7xs2X+gjmnIFHIZHZ7B9L/pIl52WcNZHAxJOSCqDcBQrrlcyVocaTcZRZ9XMtk=,iv:hgxSBCkLwbnd1lpznujtROvmbjGvBtPG5pt1PcaB/4s=,tag:rbeJbmemUkbJKJ2TDLUS+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
