---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name spotisub
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostname: *name
      securityContext:
        # groupmod: Permission denied.
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    controllers:
      spotisub:
        containers:
          spotisub:
            image:
              repository: docker.io/blastbeng/spotisub
              tag: v0.3.6@sha256:a560b7a42eb2411903cc7da6ff7c3e946b1b4fd5043a53dfdc8787bea9ddb765
            env:
              TZ: "${TIMEZONE}"
              SPOTIPY_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: spotisub
                    key: SPOTIPY_CLIENT_ID
              SPOTIPY_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: spotisub
                    key: SPOTIPY_CLIENT_SECRET
              SPOTIPY_REDIRECT_URI: "https://spotisub.${SECRET_DEFAULT_DOMAIN}/callback"
              SUBSONIC_API_HOST: http://navidrome.media.svc.cluster.local
              SUBSONIC_API_PORT: 4533
              SUBSONIC_API_USER:
                valueFrom:
                  secretKeyRef:
                    name: spotisub
                    key: SUBSONIC_API_USER
              SUBSONIC_API_PASS:
                valueFrom:
                  secretKeyRef:
                    name: spotisub
                    key: SUBSONIC_API_PASS
              ITEMS_PER_PLAYLIST: 10
              NUM_USER_PLAYLISTS: 0
              ARTIST_GEN_SCHED: 1
              RECOMEND_GEN_SCHED: 1
              PLAYLIST_GEN_SCHED: 1
              PLAYLIST_PREFIX: "Imported - "
              SAVED_GEN_SCHED: 1
              SPOTDL_ENABLED: 0
              SPOTDL_OUT_FORMAT: "/music/{list-name}/{artist} - {title}.{output-ext}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              # groupmod: cannot lock /etc/group; try again later.
              readOnlyRootFilesystem: false
              #capabilities:
              #  add:
              #   - CHOWN # chown: changing ownership of '/home/user/spotisub/cache/lost+found': Operation not permitted
              #   - SETUID # error: failed switching to 'user': operation not permitted
              #   - SETGID
              #  drop:
              #    - ALL
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 600Mi
    service:
      spotisub:
        controller: *name
        ports:
          http:
            port: &port 5183
    ingress:
      spotisub:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Spotisub"
          gethomepage.dev/group: "Media - Tools"
          gethomepage.dev/icon: "spotify.png"
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=media-spotisub"
          haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
          haproxy.org/ssl-redirect-port: "443"
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "DENY"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        hosts:
          - host: &host "spotisub.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: spotisub
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: spotisub
        globalMounts:
          - path: /home/user/spotisub/cache
      spotdl:
        existingClaim: media
        globalMounts:
          - path: /music/
            subPath: audio/rip/
    networkpolicies:
      spotisub:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to: # Needs to talk to spotify
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                  - "${HAPROXY_WHITELIST}"
              ports:
                - port: 443
                  protocol: TCP
            - to:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: navidrome
                      app.kubernetes.io/instance: media-navidrome
                      app.kubernetes.io/name: media-navidrome
              ports:
                - port: 4533
                  protocol: TCP
          ingress:
            - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: *port