apiVersion: v1
kind: Secret
metadata:
    name: gig-scout
    namespace: media
stringData:
    NAVIDROME_USER: ENC[AES256_GCM,data:lwHSXg==,iv:K6BdjPlhjoEPwVXkBJItYIheVGgkLk5B4sKA7Issnaw=,tag:OfFpNdeT+PGTpZ0MHmcX4Q==,type:str]
    NAVIDROME_PASS: ENC[AES256_GCM,data:SIU+ncrIsDB1MCJlGKHZd3BEQGzc36VM2kUWyCifk+M=,iv:on2dm5dld8IIy7G/22PppZRvzZDKWm3d4lZyVs3C2vs=,tag:y6bEABhDxqccEa7iyAl3mA==,type:str]
    GEO_LAT: ENC[AES256_GCM,data:EALuvArDwA==,iv:cDBT3vQ9t7aQh+otBcTsCvKVGkBK472Pc4CGLQskGyw=,tag:bOWj4ONaWnf2taWn03ge9A==,type:str]
    GEO_LONG: ENC[AES256_GCM,data:XzQQjnaYLQ==,iv:Nudp4zffcmGd7MWPql8V3rxxurkYipc0YBeq7a+k+y0=,tag:Wx6EioRGLZySevl6dg9kew==,type:str]
    TICKETMASTER_API_KEY: ENC[AES256_GCM,data:vBIxYW1BLwgb/YWy1PMmp8xTzyHIqdGkg61mu+VrY8I=,iv:jT9NeFKwHyXrecmJKg4QCMEfDNcp3fNk2GvI/RXNU+U=,tag:th67jtSsi2lVBMPda4JvFA==,type:str]
    APPRISE_URLS: ENC[AES256_GCM,data:JAmaV8aeMESsM3nS6lKtftlHBZLsuDBsM1osiB9aN4F95cBGheId5LEaomeUTgIWTyiWa/l04YA=,iv:MdpvPYH/Ry+bVfvGCbRFH5N1UhX/DPx22/S/Uc9AF5I=,tag:FXg92jJOE7gFJRPDhv6JLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UnFxYUNCQ0owZHZVT2hs
            cWpTZ0hzODh4R3BjdWZxMTVXN3lKT0NacWtVClA5VUdpWk5PQWRNeUtodExtaXpo
            NXNLQUk1aVlKR3Fmc0FmclU0RFJVK0EKLS0tIFg4Mm0xOXBUaHpJT0JsakJDb3E1
            SXdnWjRFMTg4MmRPQi9aRHFDU3RLOW8KKTkrU801RD3V6d3TfF5ZU+iXn99fxZFk
            puoU775Ilqk3B6jy9tEniiAes/WbTWbCdW/FL2hSsMXADcUP9gCEhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T21:25:12Z"
    mac: ENC[AES256_GCM,data:RvVAWM6YsFkCPiCWDuGcLGBueM4IWdkjd7EHh1kp9r+Zpn1H5fJOthzEp1LtxGziRXr1dNsvTLaGjtGDKkggfoN0XwbJmpOjVoz1gj6N14JFOzAxDN1naRLxvxuBftT+lsz4aWrGoVFR9Cf8uSHq1JTPDm06pLCfGFCrc9LqYWQ=,iv:XrOrKBDJ1QS4uRTG0u250jk7i52hO44Sn+mMHZJ+Xsk=,tag:us8F26ALnGOZ5+mDHheV8w==,type:str]
    version: 3.13.3
