apiVersion: v1
kind: Secret
metadata:
    name: navidrome
    namespace: media
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:C/ITHiipti5JCcE30d12XFHLg/6s1pFsVVlDZoQC+B4=,iv:qd3ETOFRFT+d/uJc+lvIRaS7QYxH4g/bCBWscteTn3c=,tag:SDloirZJuG9CJUu242azKw==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:p5gt0RttlkNbOrXzagO8i3ONN/6MdKMYN/RmObyKjqI=,iv:cdTCxrtrxmqUe1xN+O7gGjUJQEEVYFSa3MOXxerTfc0=,tag:Lpph4pUl5CAmL9zSSqbJFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WFVmeUViZGhKWTUrSzZF
            VFJ5K0hNUGZGR3JsZ0lPNmQ4dVNKZGZ0aDFRCjM4NWFmNDFxd2YyL2FuNDE1dnNS
            Rjl5ejRCN0tQRmN1V0R5d0VjU3ZITlEKLS0tIC9YRWMwSDVxZ3VUNnQrV2FINlBC
            TzhVWFdhc3NKNUhhZ3FIMWdlZjFwZWMKJsCGj9+MVRoYR5nnGkWpQFOWaPDB0TDe
            xrIi9+tndNAIKeOmMbHPOncLhHl5YnQnIGssjR41Pj44OGHLQvN4uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T19:46:19Z"
    mac: ENC[AES256_GCM,data:PSSYqn2LSuPz6rPylGJlNNPRa7gleUVblUUq4mPi+eB30PyYK9zPqfTsXk0YeP1IIeTARgl9v4HNDpEAEjswRQV/f0w55Uf6yPJqu8+/tPO+k+Vw8Lo0CiQa243stYJIiHTLFWQQktcLKR3McU6souxtG/g5Nixyyp6f828a6Hg=,iv:AleS+ddImpj4J0iAjwUFJL24xdzq+/Cccxw+6cN6qAs=,tag:D4eIm83ntlT1aHvz0LKnOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
