apiVersion: v1
kind: Secret
metadata:
    name: spotisub
    namespace: media
stringData:
    SPOTIPY_CLIENT_ID: ENC[AES256_GCM,data:hc8dLaVo7/R/uXG2Lc0EtkZ2yJz0O6hoj7bYIaMVGeQ=,iv:e0kuLzTe92nSijXeWDFRJ0OXFpzwhCXpFzWlfr/pCEE=,tag:z7sJLoZW2MJFesTaiXTf8w==,type:str]
    SPOTIPY_CLIENT_SECRET: ENC[AES256_GCM,data:kvaXLyAYyS7WDuIqnQEtccwsU0ZlKV4TaiGNN4u7z/I=,iv:1a/mdO1eHL5G+aRH7uOWQc7laR1+u57fnkIEcr2TJGk=,tag:K0OF6uCqnJFE89lr6uj/+Q==,type:str]
    SUBSONIC_API_USER: ENC[AES256_GCM,data:0tL1ZQ==,iv:o8Hs0jG3ao67mxINn3bBLfN3MYsxmai1gr2cux+z15U=,tag:8q9F9V/r6RTASlT67dfWVA==,type:str]
    SUBSONIC_API_PASS: ENC[AES256_GCM,data:dwMwOLnd79MFyUeQi2AA1L/W2bGEsMQbTIdaC+xyJ80=,iv:LWQv0kh4jy/d1mVKLQFfGBA0rGE66NQ4RUsYP7v7n9E=,tag:RcPuFvVCTay2jZBPdayToQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwczBZSzY0M2t3bHlpc3hm
            NytENWcrbzFkZndTUEc3QU1lYndHaVliY2pNCng4SzBxYkE4TTVNNWprVVdicDVX
            cFJXTkZCaWo5RDd6eTBOdXgzRmxRRkkKLS0tIDM0R0pjY1FTcUtMazM0V1drYXM5
            ZldOZkVkUTFDRHBOdEt6ZWlUMTlYY00KH2xErnquIrYHWLCzW/K7Bnuy6XZS5Sor
            YAegZmGt18dEYhYVyx69GCAbFXb1F1zlK7VNdnUjZAbNupRNdczIBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T21:36:52Z"
    mac: ENC[AES256_GCM,data:lmnUQy3LTSHEASevMCUdAhHB0VSPRRvHR2rsGLzyLZ7VS5lbG7p9c0m4jq8h58LmQaBX9lFCw//IU7xisJ4iPhMZ5WaKGd2EwCoacPnZBeQFO/2Nz2QgD5Tjpl4hnvmqVO2KW3H0kt82j6PodX+3brdTmSTvrqUDjVUeq6sDRlI=,iv:82X2jmt9vcb5zy2iLtkPeBvkKjR8L1Yuf8CnDnVda94=,tag:THzVZryIrCPUytaP/cZsYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
