apiVersion: v1
kind: Secret
metadata:
    name: spotisub
    namespace: media
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:mRn5M1qj2mUwYBjBcKPEK++1+S49fEUnd1foJuViphs=,iv:cr145JmNjVBNmkwafHu+aUdSQs2HVP2Pl3anMjn77+o=,tag:Z62ONIsGLXJA1n6sPYig6Q==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:KPZrt0TQkVnTjpB4Mzf+cSws7N72T6wqJOJewzaTG2c=,iv:yoOENI6XvH6a/h1Sbf7U8zE7Z3jaUmt0xwHnEMBpKHk=,tag:h9pfYaLwQJHIYazydbtbXA==,type:str]
    SPOTIPY_CLIENT_ID: ENC[AES256_GCM,data:4wcPf7ZXqponqHL/BFJSPcP2JiaceFv4jAgfaw00uzY=,iv:PHMiXkE4zbfpZXFJMfa79SJLSSLiFecPVrLEb7jeRyI=,tag:1AWyoUfGmAJ8mw9+F4uQig==,type:str]
    SPOTIPY_CLIENT_SECRET: ENC[AES256_GCM,data:Io/x9+SgvVDgr02zsvLa7JD88/MUlYWONoZUmrhC1tE=,iv:QFJ8M+9B4QVVnNYItEiENshOCTcR8p8ylb/QHcm+Zt0=,tag:7H4ND8s7URuYlpdu518g2A==,type:str]
    SUBSONIC_API_USER: ENC[AES256_GCM,data:fG5abA==,iv:0cr5rPr+9ROBoD2dO+McpylXWWmYNQ2d0OZSIRf41pU=,tag:yj0c8gB14GPhA1Wj0Rv5og==,type:str]
    SUBSONIC_API_PASS: ENC[AES256_GCM,data:FpkuXBFhJnY89b5uzQ3mhp+od40jiB3XflOF4jy7UVM=,iv:vRED7Osc9ZpuhCUqY/V1zGro1fiHeidu8j/nCWWmSP0=,tag:Lexu2uDM/S5fN7crtzP+EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMlYwL2pvVXg3UFpuN0wx
            MVh1UTlWQ0MyS25yYlVvZTVQMXpNMmFabnpFCi93dDM4TFJTdW92ZlNiQUdSYlp4
            ZUVyV2N6SGxKb0V6Z0RRdURLTURaaG8KLS0tIEpyb2tmeTgxbjIrWng0eFk1SzJT
            NVdpTWZsTURSUmIwWFpoS3c5Zkc1NEEKk/Sn3ZI1ufVUmuU/pxD60lork/sNuvgH
            8dhrDYyD/f9VkcY7QgS4hJkDAa5CS9BFwhlZEHIuluMUJi14RXoxkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T16:29:15Z"
    mac: ENC[AES256_GCM,data:xjubywFtuystrbJLjvb8RW0I3AfdoNlEB6GNX2TC2FwHl8G9fw5g0YLT2OxRwn7L+PB3P7OKsiH0NFoHkaKCEu07M2+Mwr/3gb+q5Pn7B/vxqKl96DW3bVmStZapq916UZuqP4VkB5vvnbQUjACrWpNesB/y2OSM+2SBXSc3eQ0=,iv:PryR9+ZIXU1uX7SZh/pjEkq39wTh9Zt8Ovw+H+Z5Suw=,tag:ALTMII0KmMmG7Lc8u32FMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
