apiVersion: v1
kind: Secret
metadata:
    name: n8n-basic-auth
    namespace: n8n
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:WJiB,iv:rDEfe6oZxQs4XolYq7trMswX9isrAR43CWYnW+t3Zos=,tag:Vct7/Ifa4MMGB3tujZEi2A==,type:str]
    password: ENC[AES256_GCM,data:eTVWhP2De2KhkQE19d+qI7V8zDCNAK5NIO5+j5866GA87I7bh+aJslcxj2WiRQpY20fwarCsK/Gn3VzHn6wfPQ==,iv:DIotbxhDNBJwarhH+aWJ62JSIbFVI1f1PHB3LQ70Xgw=,tag:tv7s666nNsY3IEAKgVYfnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TENTYjNLNEVQeUVBbEtO
            VklTcE5UaEhRYXlGUkZtb0JSenhNSkhqM3dVCk1ZWWlmdGtIbXcxU3BMY3pzMEM1
            TE9tU0dnRWcrSXBBNS9uMFpIbUxjUEkKLS0tIFhTU0NEZ1M3Qys2UWcxSDB4QWxQ
            TmtlUjVhd3l5U1lwQ2QydS9lN1plWGsKALnKeO8I5KjrA989LMY99HxDuwhyKLQF
            cYZMc5Vmgopl8yTIwtTiQM138tNlTTeHEWZdpmEtVi21SdA2IX7Tbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T09:35:25Z"
    mac: ENC[AES256_GCM,data:6K4pib98+W7NV5RwteazMUsN+wiVs8uLwLy2kTWWRp/gJwsMbPoH7AmD/Dfss0SR2YG5Kbz+uLC2Wo/bOnAyJRkeWmKy0ppxqI7ljWZxCjiXsU+RVagko+j0yP3KavqHOb8lYWQasyW5aBG6urJmxOJhU9CCouR/ibcJNWMeshk=,iv:2vDpmDIG5eK9azp9PTnrVbOpBRpc5HcwyQqQ2D3fUl0=,tag:3OelUGqIl6PgQqZf/Y9wNw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-postgres-v18
    namespace: n8n
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:pCWlDm1QCETMlxiLv5s+so5+fjrVSWsWTm8=,iv:ffojdzFqzMqjbIo/pG3Mvpu2/xijl+4HJlDRSCZh1Qs=,tag:Evn87rtqqRRNfgCs3St5uw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:0eMoL89hYpwITKRLGSWz8VpjJ97OWiLdfJ78jLCVJb2YQwAkROBiId2qhOavtqhaP2IAGwDvxjPhcd+yaw04VA==,iv:3+0CQADvTxqs1/8zt0ff/hNkf6TlCAGYoFtzowghsKM=,tag:dEGSPFdh/K7grCZ55RKMCg==,type:str]
    region: ENC[AES256_GCM,data:zECIZGxy,iv:R4AP5gOTWnHgFIBQFqxyZMB62BGd6yjeXqx/t6jXsO4=,tag:VbRXe51dlbYEc8ifwUhLcQ==,type:str]
    password: ENC[AES256_GCM,data:a69wGz5QP7cvzI23NbolkYYbHqQIEpLX0cFnC5V2LprvetLfccPF2SFIXt1VeZxfIFP6nTjxnQqxkEkYs/2ztVl93ClfTb6PQj6W9Gw8DzWbbi017DTLFR5M1ct0eL+XZ9XW0khoWA7KoFxzBNRsL+D7YxeuBctwXI3zx+7JiuY0,iv:5+ykywvP+n1sv/Hun1X6hxUedUqVQh/UuHNjW9dIFrc=,tag:N7OPitgxnDji7jrw1sLizA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TENTYjNLNEVQeUVBbEtO
            VklTcE5UaEhRYXlGUkZtb0JSenhNSkhqM3dVCk1ZWWlmdGtIbXcxU3BMY3pzMEM1
            TE9tU0dnRWcrSXBBNS9uMFpIbUxjUEkKLS0tIFhTU0NEZ1M3Qys2UWcxSDB4QWxQ
            TmtlUjVhd3l5U1lwQ2QydS9lN1plWGsKALnKeO8I5KjrA989LMY99HxDuwhyKLQF
            cYZMc5Vmgopl8yTIwtTiQM138tNlTTeHEWZdpmEtVi21SdA2IX7Tbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T09:35:25Z"
    mac: ENC[AES256_GCM,data:6K4pib98+W7NV5RwteazMUsN+wiVs8uLwLy2kTWWRp/gJwsMbPoH7AmD/Dfss0SR2YG5Kbz+uLC2Wo/bOnAyJRkeWmKy0ppxqI7ljWZxCjiXsU+RVagko+j0yP3KavqHOb8lYWQasyW5aBG6urJmxOJhU9CCouR/ibcJNWMeshk=,iv:2vDpmDIG5eK9azp9PTnrVbOpBRpc5HcwyQqQ2D3fUl0=,tag:3OelUGqIl6PgQqZf/Y9wNw==,type:str]
    version: 3.13.3
