---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  namespace: n8n
spec:
  storageClassName: "${STORAGE_READWRITEONCE}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
