apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:RkuRhcS2LHk7lNuQCcJ06iyFqPoMLfz2XMjOLHGW3LP7SSyB1/D9FulrSn2CbldBDghmZ3tdA0IxbBumW+1qhg==,iv:0F7IljfG4Yf7ZetIvIWN1gAROeqHDNOJmCbd3QqRczo=,tag:/ktEbcIsZojnLmaBOGxaWA==,type:str]
    N8N_HOST: ENC[AES256_GCM,data:wkiUEQ77Dme8svfNKbgIjWWqvdb0NZ86ARkFxA==,iv:yBBOE+Ihkq8I58Ge4IFKurG+3Ulh+SB/4CdVFylXhcM=,tag:h31imTC0sU6RlQ6SYnmNTg==,type:str]
    N8N_PORT: ENC[AES256_GCM,data:C6B+BA==,iv:giOnSZF+5WJRuiz3JbJe2H+MUVPdQSr5afstTjaHVhc=,tag:4EGvP2Ty8UVpFEBa7Z0SMw==,type:str]
    N8N_PROTOCOL: ENC[AES256_GCM,data:AjmFZro=,iv:WnCRWGHFv70Ysau7AJU2BvReGNfrUSOcTXOGUqddR/g=,tag:QkEJcC2/XTC0lnfozPTfAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTEZ3QWpvS1FlaWpiZWdD
            M0o5MU9CVW9PdkhIMWNHcEY3MUM4T1RxWG5vCmR2dGx4c0xjbEVSMC9LR1lWbElo
            eXRnb0lHa2Z5bDBSdElPWURRRkhUcVEKLS0tIENDSTlqNjIvcnBiUWFrUEtzdnNG
            bmNaWW1iQkQ5blYrZ1hWSlJ2L0N2MWMKd6OatBq8URfMcMhvPqCEjVkVl6xI/LJJ
            96o3xSNeaeh1hT5Hu82LGR2eN7Cc3AlGUkSbhgcb8D9EDFTQbp+fKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T09:35:25Z"
    mac: ENC[AES256_GCM,data:+IGpbyh9mL3rANIqFGwnzc4UUqdNeaQBMPFx1arHeQKIGqc4X4rgc6/WjLWRLujX8WqI/ChI/RtqLZGXG7SCtr2DvzhmV+pW5MmsT4IVnTpga518sX/w+l/boaeo8euSfvFbcOwrgy6MkM8y9XfVmgOKDwISjxmssxbmIY9I+JM=,iv:UZX/z0TU0gyXJF7yE0NtCyLL13Inj+wJ7GoLpaZu+7M=,tag:3vR2+MxZ2+vBtPec93ClwQ==,type:str]
    version: 3.13.3
