---
apiVersion: v1
kind: Secret
metadata:
  name: infiscal-basic-auth
  namespace: infiscal
type: kubernetes.io/basic-auth
stringData:
  username: infiscal
  password: b0d52f2d6da5f1ef187ca1cd308a9c5e4f58d0805b49caf992b96cdf7a7d5c6d
---
apiVersion: v1
kind: Secret
metadata:
  name: infiscal-postgres-v18
  namespace: infiscal
type: Opaque
stringData:
  s3-access-key: GKfdfb472edd1c02e684926fc9
  s3-secret-key: f49f406c363c917c17c10f45e3a3f3add76d78d0d51a77ca4c785b22c4d5cb8d
  region: garage
  password: 6ae727da5973fee8cd3abe90b5784e0496c44071801a4211cc740c0b79b746a6
  DATABASE_URL: postgresql://infiscal:b0d52f2d6da5f1ef187ca1cd308a9c5e4f58d0805b49caf992b96cdf7a7d5c6d@infiscal-postgres-v18-rw.infiscal.svc.cluster.local:5432/infiscal
