apiVersion: v1
kind: Secret
metadata:
    name: infiscal-basic-auth
    namespace: infiscal
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:BjVDI7KAk7k=,iv:yMKdqPxi50A5YJgUPauwjBSIi97PQCRApqsnVbadfOU=,tag:C4C9xuNSYVvQxIR+V19cDQ==,type:str]
    password: ENC[AES256_GCM,data:JZW9gyArMN2Qx54RzS9+Jh3jVoahBbqMcf35oTZJNz2DNrgePyHc2Mkn0laPiSKumEe1VyzmbTTGtYVPHq5QKA==,iv:NCkrk/Gtw9g6LkGPhd28F75u23lvfgdMZReG1o53XtE=,tag:0RTCyui9NN+1/xtG3/vLZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldlBBRjVBVE1pRk0vS1Vm
            M1J3Y0VuRmFNcUk5K2xmSVFTMmdOQlUxekFRCm9wR1BjR0ZreUNQZ1NRUHk0WFd2
            Vkk3eldqTXQzb1ZKUXZzYitQaXRob3MKLS0tIHJmWm5uMEUzWEcyTUJMU0M3MGdm
            NUdNbCtIN2hjRCtwSENCMCtya2pTT3MKXi+Irrp45NYRyi8PsiHZxQ6MN3nnO3BR
            zly4PZ1+vVNHVY/f7abW0ucMJ+9RIb+WTNzwCwXnv0lIDQbcBcbyFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T18:54:42Z"
    mac: ENC[AES256_GCM,data:hIc3j6mwJIP5ivuyJBQR0634+WSLHR3xrT3bh75ztO9qaDVDNn8lkoFpskyYRj1CkDUECp+E8wNEwEAjyjva6bkOYLz8jhbWFTprT9m4nPmdWOh0z9UhC5//B4R7FfEg2I7TuK6U84e3fr28RelVNmhtc8RZNdds/9OJ9JfLwEc=,iv:F/5GHfKULY4vRsUtdzSyCiBknfEu+K66pBratt3fmo0=,tag:7QLx0pZmLnM+XAJ7QGmmow==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: infiscal-postgres-v18
    namespace: infiscal
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:X55gDE3Umxwywx+3ZgEkTroSAmmHudZe2m0=,iv:PeYTTunjv/fayO/4dvIGE3yTPFAGpEdXN7SqWn6Myzo=,tag:7Y/RUmdZjrUbQbBfcs09wg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:LPkzVTuF09+l3HxrXBowhmqN7+UdKbsZ1a6yFvRpnSIOZBWVpl6h1kAEY/eNZ6NHhsawJG7c6LvLqyTJ/Uu8Lw==,iv:zf4xCnuEyKdfwRLan+q7pCAcLIR+yTxpcFDy05ZS6Ng=,tag:fZ5j5xUDrQ0BBbMrOoYsCQ==,type:str]
    region: ENC[AES256_GCM,data:jnl0wnlV,iv:fkRTSVHIdg9V9eOK7TmigI6pTgrF/KihS3aGW9L7nNk=,tag:IBeBJHoNKN44yItKd0Y+KQ==,type:str]
    password: ENC[AES256_GCM,data:5uTUF+etJgt88WMZVOJwJsR1E0soIrPkp4c8nw30F9P8sp6By6W4kvyGtDdl8bFpCZcNxTA10MJCj7B9hkQ/PA==,iv:wyPvf5WxI1uBIJRk9S12Tfj1soSh1rtjjE8GEoK2pLc=,tag:8s+TpqAAubljSv7rUHNpdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldlBBRjVBVE1pRk0vS1Vm
            M1J3Y0VuRmFNcUk5K2xmSVFTMmdOQlUxekFRCm9wR1BjR0ZreUNQZ1NRUHk0WFd2
            Vkk3eldqTXQzb1ZKUXZzYitQaXRob3MKLS0tIHJmWm5uMEUzWEcyTUJMU0M3MGdm
            NUdNbCtIN2hjRCtwSENCMCtya2pTT3MKXi+Irrp45NYRyi8PsiHZxQ6MN3nnO3BR
            zly4PZ1+vVNHVY/f7abW0ucMJ+9RIb+WTNzwCwXnv0lIDQbcBcbyFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T18:54:42Z"
    mac: ENC[AES256_GCM,data:hIc3j6mwJIP5ivuyJBQR0634+WSLHR3xrT3bh75ztO9qaDVDNn8lkoFpskyYRj1CkDUECp+E8wNEwEAjyjva6bkOYLz8jhbWFTprT9m4nPmdWOh0z9UhC5//B4R7FfEg2I7TuK6U84e3fr28RelVNmhtc8RZNdds/9OJ9JfLwEc=,iv:F/5GHfKULY4vRsUtdzSyCiBknfEu+K66pBratt3fmo0=,tag:7QLx0pZmLnM+XAJ7QGmmow==,type:str]
    version: 3.13.1
