---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: infiscal
  namespace: flux-system
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.8.0
  url: oci://helm.oci.cloudsmith.io/infisical/helm-charts/infisical-standalone
