apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infiscal
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:/6PIOVW4q6xIFea1C6CzCGzqpKmRYoPtuEMwElvFlDs3nvr0CysMuucNeBc=,iv:xtj0EB4dHCxt+zXLWEuY9X2yM+saz6IQzSImw3tHtbg=,tag:iFsErThx6MUPqwwcwfZXhg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:6Uw25IwWLBLAK5+HKJIQn3eSsyiKB6fBGxF2/PdKHZE=,iv:sZbkIUGAs7Rhn0g8jWIIJ5fD+Do763QFcxV9CAJeBPk=,tag:yFgCWav3I/dVb1StmSxwEw==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:zDEUO7PvVHrdoQutDTPLRsTCNNkVoStLRUboUHqqAUWJLBDfAfKXJ0OBdUJBoHvhciLeuJagReu0b8Jjsl1kv1bvVCTp7ZRn8qkSd1eih3kI1rukYXa5D+XNSDY8LMdASc3UzkWqmerFMKH26mi6tw4DKqMVuxw/xOYCBS46C0aQgXLvcBq5lC44K8XsL8CQfM3++dYNJaA=,iv:+4mzlMKRCBk031GG0xzTQQ4Iug8AmK4uSj1QRj25xz4=,tag:jL9P32gPH7mLphVTlrGBCw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Nx+JESv0aWJ879gXOkOuacobGDnRZbUc0pwaiCuctp5pKf+0ca54yTrOXISPWOe1RgpFPDigiQ==,iv:UXnJo3m59PM7osq1vpAIQ2y0AhdSQkRYqC18o4OsiyY=,tag:KTI3P/h3Xy85/QryloINKg==,type:str]
    SITE_URL: ENC[AES256_GCM,data:Dpr2imxjlYF3DhJ1WkGOoB9f1RwSiav8ndM=,iv:p+5XeXu8ilKI5z5H3tXTp9+J71R2LdwUNLevrBUQHGU=,tag:0BzDCWzNbczGTptcIbdCSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q0pIandJY2tTTmwzeVhG
            dVZUWWgwYkI5YXBZWUh5RndpK0pwSXRWZUMwCnJ2UHl6TDhOdk4zeU0yV3MxTkh2
            SXUzY0ZWVlFHZUNITTRjQVhyWldXa28KLS0tIDJXOTRsMVVMWHdURERENHhZL1cv
            d2NPalhIaldMQklNOFZYdlhEZVRyN2cKTZACVRWdBAYAVePwNFkOQsmSovzJRjWg
            PLOWgmx4oE24Thdy1196lf+mtBCLKL7P/dg9bP4go8fJPO0pZQDnuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T19:04:39Z"
    mac: ENC[AES256_GCM,data:R2CWQQNN5GccHvHTfIiIMquvVguFeg8zO3sF77M2qrRaKxA399EA7s3Vp5J1nIKI7mn8wOAg+bs0beQFShmXWY/XeLkvp2fDI4Mof2Q1pdv1AH3TRJJI0p5MG4kf5Z0FZ4kafDy/ol9EdI2NhDuc82Y//dN8R84qaB56vWLKdtk=,iv:rr5lRx+p5UfTaf4VHd/+QFTuCzVcXlo4QZqkBDHSa5I=,tag:Atr5E7q9ouXlYL2Ng7csHQ==,type:str]
    version: 3.13.1
