apiVersion: v1
kind: Secret
metadata:
    name: manifest-basic-auth
    namespace: manifest
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:alyCjzbtU4c=,iv:ULg4DveUs/k7JqsRpPRTFRWCA6S4xVTSjhQdKeVPKDo=,tag:4HExvYemBkzCL2fd0+p4Xg==,type:str]
    password: ENC[AES256_GCM,data:J+GNgDedrCIcnHWEKGHCyte/MNl32x59aRN7ovFAskg=,iv:BMTcMOJlFm3D6ERE4o5VS5umVWj+5vuGpNOCOkmvbTk=,tag:+X6faDYzJO9K+n4Vxdp9SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b05INGZYRTBmOERadUtB
            UTZML2lCMU55anVreWN3em9DeXN1LzVDMERrCmdtZVNHU01MR2tMYldqanBwMWg1
            QjB5aVlCc2t1a1ltQjVOQ3p6a1psNDQKLS0tIDRETVFscEROdE9POTBQVkluYXBa
            RmpFTGlNd0p4eDk1ZEN3cnkxVUp2bjAKr2v9jDGLgXyAquoeFO8r/r8RqvudFr1a
            mY+96vbWX+x0J9PbCb4xZgmPS5FRviq1Ln9VEc/ky8bKtxJ4XOCXwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T09:15:03Z"
    mac: ENC[AES256_GCM,data:00bLPCY9EF2/1ilaONqdcc/j9S4ugfLNIBG4wqkn93WRSR9uymBZ8rr52jijn6g6LkcdeHWm9ixSZ2DDucUREWIF5PygZiBilJ3gf61WFB6rC1iNlCdQ+0CMO05K0bbiY9GOe9LgRpP5LYtk/nis7dnbNnm5CqE22ELyt30nwco=,iv:IrMlXRGwo9tgTKzRxS1j6Xp/SLUX4ej01Ur/ldt5olw=,tag:mzmiuUj2ujfYsOE5BLQShQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: manifest-postgres-v18
    namespace: manifest
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:PU41GVodNg3HUHq9X5Qk8ShWX4RYiLQIUTs=,iv:26SIiw3QAW81j9a432SH48Es/QCLySEkDBrJTe3CmC0=,tag:vzLKKZ83VWVyzRdZliVt/Q==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:y73VXR2IozD66fYx3tFskb4MoXKiSyZAQL6htHMvzhCpUbnVNtq7atINJp6WayLCRm/VZk0B/4RMrfBj/rTi0g==,iv:cq3s0U/5u8+1Q9bSAwObQiSuYx7+KBgRxwJbGc6mGc4=,tag:JalZx8NF2+vQHzE+3UDnFg==,type:str]
    region: ENC[AES256_GCM,data:em9m0sWJ,iv:xceavAptzWrQNP4PmmHjX8OtS3RDAWBJTQ7McocPzJ0=,tag:V7HqN/No5wFcwDpPK4lUrg==,type:str]
    password: ENC[AES256_GCM,data:SvjZ10I7TEiAs/E7XN9KEuX1pFfrL9wog0QxtTWnafo=,iv:u/Zbh815+ycR9D9TXlI0rb5FRAKrakZBrTe5uqqUseI=,tag:seH5deave71hW6qw8T7IGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b05INGZYRTBmOERadUtB
            UTZML2lCMU55anVreWN3em9DeXN1LzVDMERrCmdtZVNHU01MR2tMYldqanBwMWg1
            QjB5aVlCc2t1a1ltQjVOQ3p6a1psNDQKLS0tIDRETVFscEROdE9POTBQVkluYXBa
            RmpFTGlNd0p4eDk1ZEN3cnkxVUp2bjAKr2v9jDGLgXyAquoeFO8r/r8RqvudFr1a
            mY+96vbWX+x0J9PbCb4xZgmPS5FRviq1Ln9VEc/ky8bKtxJ4XOCXwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T09:15:03Z"
    mac: ENC[AES256_GCM,data:00bLPCY9EF2/1ilaONqdcc/j9S4ugfLNIBG4wqkn93WRSR9uymBZ8rr52jijn6g6LkcdeHWm9ixSZ2DDucUREWIF5PygZiBilJ3gf61WFB6rC1iNlCdQ+0CMO05K0bbiY9GOe9LgRpP5LYtk/nis7dnbNnm5CqE22ELyt30nwco=,iv:IrMlXRGwo9tgTKzRxS1j6Xp/SLUX4ej01Ur/ldt5olw=,tag:mzmiuUj2ujfYsOE5BLQShQ==,type:str]
    version: 3.13.1
