apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: manifest-secrets
    namespace: manifest
stringData:
    better-auth-secret: ENC[AES256_GCM,data:I8kn3hORGYkms5GDtbz9+3PpxjzWahBDGBhXJC7bjUvaf1bBvQ6BBaMG/sSP1giUq9Sn/BSPYmSj4rVJJuSHEA==,iv:fJJFiWIQi61UWIqnyf7Ha0G7F2hcfn8qIAM/xWS6Rjw=,tag:+d8YeOSB0W97kXOMtMfSaQ==,type:str]
    database-url: ENC[AES256_GCM,data:RkbOFpFlsjRfVgMfT7lbF2hbJ2rWpeHtm8mq65weijXJcdApamcaAc6y2AV9K0SInLbPB3PpJtiPIuu7auBcvLMUoVoHy5TVaLZXnBBvSRYeGNNT7BVyfUGqQDE8T6I087KK42pIPfoHF+Ou5lAzWAUJvZ9y1I/7,iv:Ht/ceR4HI9j7oDBun9ohKrmGQQa6gLm/xCdpQ+Vx5fg=,tag:o/cJn1BY7D4IahJvt6pqtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc1E3Tnorc2doQUppL0Rj
            U0ppcC8vSWNYdDIzSEVzemVKN01McWIwR21jCjhVU2hYdmYwVkdUR2M5TFFzNmI3
            WngweUhlVjZDSnkraUFOQVM2K0RyMlUKLS0tIGpza3NFenJ6Tk9CcXk2VFM5SEZw
            a0ZqNEIreS9SSzVzWEUrVVJoTmN5ZEEKjDMowamrl+CvE84viZqCRlfcj+L/5CUG
            QlmWzGEq+T/ezEZEJ5VUfsOPbSOOpNEESOV6T77mKYPU6tOZGU8Wmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T09:15:04Z"
    mac: ENC[AES256_GCM,data:kIlmuzcMvAT4O2YpU5n8cngF8pFZK5ZuwcPwCxSJcXQ4qD1cGuxElwV5dd2nK8rLgZ5QuUVwjClNzjfGEVlVmNCWPidhPKJId8aMLxDfenwgpAPUmYy2ZbhaZXJZQjnZELeQJjLslpIpQJD4yKP1DF/m8UqpA5LjwJmODhizQgk=,iv:/EQ0WhTISJZvmU+dQK00ggdmQbAuyYmQdjLjPVES+tk=,tag:vti2KpHoY9+xR95+xHz6Zg==,type:str]
    version: 3.13.1
