apiVersion: v1
kind: Secret
metadata:
    name: tracearr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tKma+I0Cxtg=,iv:pCUTq2e0HkCiC9n3sEvweiti2N2fufNWAR9syWiuGYc=,tag:nyh6K5rWt+bo3TTYZQzLVQ==,type:str]
    password: ENC[AES256_GCM,data:vXA4pjj+4FcV67bJno0hVoCIV+5nQP/RGPsMdm9Y2v6SJ8MF1us2ldylmQ==,iv:esjqAcchWbUHorHgepV95uSp4RoSUtvGoI1MKBHuSBM=,tag:0rAMmAit81uKKU5+ZrrFYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaC9vcThyV2ZvUFNyVEtp
            WnJkT0svSWFDTVhWTHNzdXpWMnhKT0ZMM3pNCmhyeUtLTmFLZER2ZjRndiszSXQx
            MTdQUEYyNi80ZVJQbStGd3B3M2VsYmcKLS0tIHQvWW9oRjJWZUpkaTdzZEw3b1hW
            aVhuT1pqWllKVTJkSDFOWEFYV3Q5cTAKGOCnwKDEYitqCJwLAYL53hdx/kzOQ9Ml
            1YB8L+RCKMlNfHDnyOyLezj4IPpxbjwqUTwP4bRw4EYxLv1p1RmbCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T13:50:59Z"
    mac: ENC[AES256_GCM,data:Cum0+24GObE2Op5OLTI9o8n2adCWtERMYBLfBMVFu7P3jNvYUlGpSvSRSFQevEM/i+hOwMKgcW/UxP4xtH7SCtgerE4/DxL0Uwk0h7guvKGcqa+G/sIec8ioLGiYzgSRcPT+VXWMM0EUd3gvxr1rsgEpJnsFUHqqWXQSYIHgY0s=,iv:hnosduCVB93KNMvil5HTSYXgcVnJew9+ljoDD5CzM4g=,tag:c93onF138fio3JX7FTn5rg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: tracearr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:7rQue9meBY7Z+N3EtiGKI4GrK1Vtm2aXGfA=,iv:HRFFJr0WdDz2l+2m9O2efbpye1GUbDn9aoFw/PZUt4A=,tag:fKYQIlqjkvgfC3Qk1dTQ3w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:mrBAf382cfZ2mDzKc4pUn8WM8Si7mUwSEAcAhWt0K9gazZtCZFggl/0xOEJucwwObSxEtBIDl0B5MtYlrNbu6A==,iv:uS50h2bIexr9ebGnRqwWp2nkBiqNr75Ht4oKO0SPhdU=,tag:PZV++TQOcCVsWv8zOmojfQ==,type:str]
    region: ENC[AES256_GCM,data:EU6QqS1V,iv:5nVHUD0erYLc4JzeoAXlh9/x+BefvS8q0UpFJdeH0Y4=,tag:u9SjTBJ2ojHEaOi8XGt6pg==,type:str]
    password: ENC[AES256_GCM,data:YA9Ae0dGtxN+XWyQC8ttnBxIEnvRYpbAGlL2IeID0cudKPvcBCbbB2BMXasTigGJ8dAbi6nggT2dC8D5uf12Wg==,iv:PxcyPgygaVwR4uXKFvFWp6d6PU69XIogA9/9wD/h9r8=,tag:B8VAMdlWydKD5GkzKXO2WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaC9vcThyV2ZvUFNyVEtp
            WnJkT0svSWFDTVhWTHNzdXpWMnhKT0ZMM3pNCmhyeUtLTmFLZER2ZjRndiszSXQx
            MTdQUEYyNi80ZVJQbStGd3B3M2VsYmcKLS0tIHQvWW9oRjJWZUpkaTdzZEw3b1hW
            aVhuT1pqWllKVTJkSDFOWEFYV3Q5cTAKGOCnwKDEYitqCJwLAYL53hdx/kzOQ9Ml
            1YB8L+RCKMlNfHDnyOyLezj4IPpxbjwqUTwP4bRw4EYxLv1p1RmbCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T13:50:59Z"
    mac: ENC[AES256_GCM,data:Cum0+24GObE2Op5OLTI9o8n2adCWtERMYBLfBMVFu7P3jNvYUlGpSvSRSFQevEM/i+hOwMKgcW/UxP4xtH7SCtgerE4/DxL0Uwk0h7guvKGcqa+G/sIec8ioLGiYzgSRcPT+VXWMM0EUd3gvxr1rsgEpJnsFUHqqWXQSYIHgY0s=,iv:hnosduCVB93KNMvil5HTSYXgcVnJew9+ljoDD5CzM4g=,tag:c93onF138fio3JX7FTn5rg==,type:str]
    version: 3.13.3
