apiVersion: v1
kind: Secret
metadata:
    name: tracearr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:j4gnG4tAFQU=,iv:xxbBnHm15SmLRCEwWXgP7XooXhtq55I0PDnZmxrLSDQ=,tag:vL3JZ9hjBY0Yip5CZfZLgQ==,type:str]
    password: ENC[AES256_GCM,data:x6iur6KYJMnU2Vmw5t1qDrNNcjOyOIlbzdIxpkgVrRlhMIrVpkQqopkyyg==,iv:DZbBw4ZDq+swfXsKjTKjZpNiZ5uXs0yb1IhTS3n0eWQ=,tag:0q6nZb47vcKaNQxSbzRy2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVm1Uem0zZWEwaitqZmdF
            MVlNcWVpWDY2aUpiNG5rTC82VzNSeE1jbDFzCmFDdnBIMkRrVHEvVnEzbTczbDd0
            cFovM1FNdVM1amVjVXZLVFd2NXcwbjAKLS0tIDIyNDBqSFF3YlVOMmxOU200MmEy
            YmxWUVlzangrbGRGdFhacWdtcE1BR1UKtKKd6dXBkzKFhV14UcKsOcNZydLaUUHC
            JD4ODxfNGNmnuYpcNvHyu+KLfMDkOEMqT5elMqXueUVFGLWiC74p+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:RRrfeS92zTI9zzwu1UL83yf3Vf47Ev5duKlr7lJF50scO1G29NarOhW3v2PIwhjIRSWhkELLJDOlXlex/jM0XTlx5+77MioXq2zOja5s7oLg0KVbzA5dxn8d6sZtatyVPMwdDhrJZtkhB8OgM3mU3qUHTMll623MkumuSONLTW8=,iv:zhLhpvbLOFnc+NopuQlpFDyqXUz0wTRw+sFS05d+/7I=,tag:lFufgIUYfIRqqxumUiUQIg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: tracearr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:OWnud2k6pUJFullUUpDpzKWPI0MQJ3+QXgA=,iv:qeTmbIusTF/aUIP1JxaqMvI5KIZDtVPw2uG44XAq9/s=,tag:JwSlpXzYrLgp+W+joj/qXA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:CjVRPuimMjAF9/XQoN+4NyTJpet3oKURxMNYkkkHZMrkkgV7EYrFhKM4+4uNsnNVkh1WbawEA50tUdA+YZatjw==,iv:hHBVoiefzX2jJlDz8fynZ/9LPxwrsWd69i6DN2e4Xdg=,tag:zL9HIegFWLGIVWIq870bhA==,type:str]
    region: ENC[AES256_GCM,data:xe3voX1Y,iv:qWcGv7tWavzGSuem6V/JExHPj+gKfrgBzxiFHkxg36U=,tag:gd1dNwPCkYL4k6TOuFKqbQ==,type:str]
    password: ENC[AES256_GCM,data:hP7Nb4p0NgzEEYXHK1GNt2Qp16mZQ/Me3r58RbqmvgiuqcruofCfPu/MvCRvZSTwI4E1utz3OzX+9K1tNPT9eA==,iv:T32jPVywbNtmE42uzWUMNbhm5P2qzxB9QycPffvdgcc=,tag:YNHpaBa8YzmMaWeSEnNdxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVm1Uem0zZWEwaitqZmdF
            MVlNcWVpWDY2aUpiNG5rTC82VzNSeE1jbDFzCmFDdnBIMkRrVHEvVnEzbTczbDd0
            cFovM1FNdVM1amVjVXZLVFd2NXcwbjAKLS0tIDIyNDBqSFF3YlVOMmxOU200MmEy
            YmxWUVlzangrbGRGdFhacWdtcE1BR1UKtKKd6dXBkzKFhV14UcKsOcNZydLaUUHC
            JD4ODxfNGNmnuYpcNvHyu+KLfMDkOEMqT5elMqXueUVFGLWiC74p+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:RRrfeS92zTI9zzwu1UL83yf3Vf47Ev5duKlr7lJF50scO1G29NarOhW3v2PIwhjIRSWhkELLJDOlXlex/jM0XTlx5+77MioXq2zOja5s7oLg0KVbzA5dxn8d6sZtatyVPMwdDhrJZtkhB8OgM3mU3qUHTMll623MkumuSONLTW8=,iv:zhLhpvbLOFnc+NopuQlpFDyqXUz0wTRw+sFS05d+/7I=,tag:lFufgIUYfIRqqxumUiUQIg==,type:str]
    version: 3.13.3
