apiVersion: v1
kind: Secret
metadata:
    name: tracearr-config
    namespace: media
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:XLOGSJmXQNr47zNy8ifmCnihOdkOeQYCEltHIhCyUhWpEHmtrxZahbpNEXeIEP9kLuVQlMHeY7Ou6FWe7YIwQ69NugkWPtbfVjC9fYy4rSS81f1xo9WzNz2Vr/HbUyOzKyLR3tOj,iv:xZGFstGs/ahe/4JEmDrKhWw6ebFDsmT2dufqzxKf98Q=,tag:cr4FDeAvce/OgJlMvmUcNA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:AgpK2hkI8c6OUbrpCXmG3h7a5QzwyXrM9kD78TSVMOoj1L6eiyWl5MKsiNlr2Rf2QKglARPWQNDKJoAq44MfLQ==,iv:VkbEBHeJ4f9EgyFQutY886Cr8WWX6MZSWzgNeb+VSV8=,tag:exQxhIMoLZooWZraouW0xw==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:tQVhG7hc7uC70n7YTMROADilWCdTrhlI4b5GXNHe5/AZzS5CE/9pgG7jmiyY8/HEwC7uz1O7uOjYmwskXlei1Q==,iv:LHmcRPfQXmszwf2R+dzLVtFBBhRfgpeYIrHkpKQuqTU=,tag:U+Ho3cpUGmKhIDMwQMxPog==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:wl6nJ0fPfPrCZ782ylpkAhmC/Vf7QUs9baxB36wH4svk9sYm9VoIY9htqHXLIgehoP6wM/kG1a7Ahp0beim1gg==,iv:MumvYstwRSv7q9WuQrCizzqm/AIGAcPFCbm7mGBHfZs=,tag:pWi2rRY9mJJdfZtvH4nF2A==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:TUk7t5E3++vdpq/R3ZJ7RLHftj2yc6XZZYaivadtDHss60ZEDg+mAXqZk/1R2kK1XcHKWRIFknDuiCl88oyFyA==,iv:er/YjS44/Rpdm1PE/JRz3twISY3ZgfwC3XNnbQDP/nE=,tag:Gq4boQBpmPDZVbZ7iJ3nVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RXZtVE1hbGtaRU9Pc2M3
            RmhTTzBjSUZRTzF2ejJ2V3VSa05KU0NVU0FNClRvd2NJVHVJYW9EdzU0Q2IyMC9Y
            MDlIUDhPbGxjeGZGOUdpOGVTdnhqTGMKLS0tIGN3TU5CS0NWSmtnV1VnbGYyRy9q
            eVhJQTRDV0MxMkEwSnNDYVpjbXFXU1UKd8yBbq774fNbjXFK+efMSFgSB+g7YJk5
            TdPcA8SOeommbYkHSuC4c4knovuLVik2li4o3b2vWKXGpkN/fGyz8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T13:50:59Z"
    mac: ENC[AES256_GCM,data:fRNCUgODMazyIyPd9fA+asfAqVH3nbJLDGFO3HZ8MtQDQXsf/TBkLWiNQpgU4VfYNNs1Np/XWjC1OnkcxFL/OovvCFnVNHd+ARYeK5eKe65Or12qJXyqkV1o13FA3ydbLgOcSUWxS4oB6ewmkI87Pz6hgqpf2ih8N6NFTt81da4=,iv:DK6yii2zBx9EXix57MjeB69wzqP7efmRAJlwAzTMMEY=,tag:bk5IpW0bdu4rWjWzoXHu6w==,type:str]
    version: 3.13.3
