---
- name: Get arch-information
  ansible.builtin.command: "dpkg --print-architecture"
  changed_when: false
  register: host_architecture

- name: Installing dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - fuse

- name: Temp download debfile
  ansible.builtin.get_url:
    url: "{{ rclone_deb_url }}"
    dest: "/tmp/{{ rclone_filename }}"
    checksum: sha256:{{ rclone_sha256sum_url }}
    mode: '0755'
  become: true
  ignore_errors: true

- name: Installing package
  ansible.builtin.apt:
    deb: "/tmp/{{ rclone_filename }}"
    state: present
  become: true
  ignore_errors: true

- name: Remove temp-file
  ansible.builtin.file:
    path: "/tmp/{{ rclone_filename }}"
    state: absent
  become: true
  ignore_errors: true
