apiVersion: v1
kind: ConfigMap
metadata:
    name: spotify-navidrome-sync
    namespace: media
data:
    config.yaml: ENC[AES256_GCM,data:TBdR7310qhNbQgfnT+ahZLvMYFFEGZeima24kBjyAI9+qq/8EhDqMdGSEowG3RfJtdS2OPPHmrkX8lxfPrR2BW9Sr2Q5yTOIpHOMsWIjgFWQ6UhoC4JeQKx8Cj4mELKM3v7Of2rSIs5WGQpiT2tnwHZJ8i0TKf7yimPhx2VLoRs3St++sKLCuJ9VjzOw/aMS51lIdE9xNlGTW6O74SZMhLvo6TbKsT7Ld2JDLg+fNO/vfe8wXN1oG80Cb9yFGNRoemIaKPsuiW2OHqb1e2CG5eHax5qy6MEz3kASqleCmrm26hFotGausxSX/t3EV5/Wevf5Y3Kqdfa5yiItSChF3R7GUATLS9eUb+dd8p4OGiztCLxAG5ekQZixIl1HWfjI+UtS2/DVP9dt0DjdU1to6v36u463FrrrT+5m6WtbK+3V7T/SprihtMQ89zw42Z02eDElFjZ6tiJMTH4gBiXcMMwLRSm6zTQ4fzpBg64vVtNiFLM8YqfkmhbDPVzExtnh6InEfwJ83ZR05qCbKE1g8mYS3TF6Lv3lX7nHiK7vQHHAfWZ9ZFctGZ2SOYrvVN+WV4rBa9gAxZsbcM7RXeW9mJTLUJ9QZRKjprQ4RnNTmqwMmIfR2mMXdlEYlyBDwSP+p+BMQb2IcoWcOFySvQDgFdVPK5CXsG6HyjtQ+7WgRKIL5GcHwOuho94vvyC1YpwaCOlqxBptnf9557/VWCSA904Uz9mN1NL3KQjjlsEr4ZLQpk/p+vlWzq4zXNiHJGG+CgVWvyn8+2WjMRWs8fDAlnSjVdTQbWyfm8gxMnANymvsTSDUW84j63LNRQZsLEfmwssEafSayzibw1unRBAjsdM8y9+JnvGqtPjeeuJaI52CTsbehJP7BcdfYhYMj1EcHEg+W+6+TTfsKjyGeR9edAgS5g015ZcW/EH1wnFz0iijDTw+zwA0/65iOfc3gKnQ6X00x6Fzaq3jf8kdbckIk3zQSCgSoYSulS9aWDTmcQ3+dCKeCRJyh8ah78rzmNh09dLfRejEvMo/U+L2K/99plMvZ+agLq/bZF6L+xeLocSye6zJEdODU8QsKq0lN+sS1jE0nDqBH2MSXReScK/UKA==,iv:QYL5X2fVE1+N3ZcmeOZqfBzW+aufkCex38gifCqPhho=,tag:Z2Nw01uL+SdiRQpnX4CGmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTzcrYTRleW9PQzlzOWxz
            emVnUWwxU3BObFhtZzNrRm9TU0JlYVRzbFQwCi9TczFNcHBCZ2dMTTM4R3g2Szd2
            bDVobDRVZGdzWmYzQXN5Ly9MemFZZFUKLS0tIDRFYkJoZGtBTmZONW83bDlpZm5N
            TlR4U2pnYU1yZUpUNjBsR0Q2c1pDVmcK91iqBi3NITKyPqMfOZkKUhCPi+ap5jN7
            ZNzBh+B3ZVHzxl2xQoELRihhQedVSoSzNAl/OcM/u5Qd515kLNjvAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T20:29:45Z"
    mac: ENC[AES256_GCM,data:kgZ/Y9g6A8cTUii5RBuFLlirLhFN60unCDE6hXK352nEbVSxBJFBkEGIt8DJJPuJfbnyVZWZT7vN1cN8e1QIHMx1sBM5Du/sUTO27kioCt6lP1dVfDMQvMfZTdjLcSt03IEgkzOmcDYLW0CYq8DuB8pdZcyvQQjHq6E7AxIDB+k=,iv:oYomvRro1Qk2RiCvmmMKojXkRGRjzCYf8o0a1mloGKQ=,tag:mrNaGEa+yZFbiIS/qfW2/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
