apiVersion: v1
kind: ConfigMap
metadata:
    name: spotify-navidrome-sync
    namespace: media
data:
    config.yaml: ENC[AES256_GCM,data:84yxqyPWdGsWXCzjhyTJkUZV39m7K+bEvXkpsJJWe1b2wOMLPQR3BDYh2B8ehEoqf2YCSJvErCOJ2OaJJWk7zoO2wHlQVxFB3OHG0Q7iH5Cf/4RB15vUOt6LEiKFcLH0cJEELjQ1uor9X0eYQj5JwhAESaDwKqBefr0uEOrZG5RTWYdB0zd1W7zulj93A/qyIBLqeKUueDWFM9gzWM2O6qM5tVd+rGp5bPbFHbtI3qlx098xydQKtyCLII49ZoeZq/Fh6UQ0RlfnxM8QrPBm0Y3hxPuFEVSMbf8H3cRXFl9DoqtKdKC2v3uW7zFwUNE7V2/SC/IY3g3CVJ89CDhV181aAdOTZJceJqSKvOFVAoO/QnXGtxOBbMZQkzKpaCrlJS1CQ5K1QR5ONjncBFiJvZ0iKQKKjnynhAZvPPka0ogjjkfZ7tVjCcfp/rRVD18oJ63uqmNCjoK454rfr53518svEG4R7KRWLWuT6vYA2NzspsBoHNHSI8mrlNNGqNaPzTRzRyU6q1sk2XTSnta/o7zuLdXGAEcmmQt8Ve7AiXaGS25BsMeQo2nQH6id8994umSS/OMDR407qYtF5P+xNwtrL3sAfbrNLdc/YQa5E6fq7F8Ayn567Z4UkodJXae3CdlHm3K3rd6ws2xnlhJtLyOh3b/ENK1gsc12Wn3zXk2Xk4G/KnEVicEBhBv7efqi46osip7Ek+kQVnZC9WBJmioxn+ojfYqFcsgG0PsacqcmCZIWSjCxeUXO/aYAJaWDKwm2vLcvAgf+Hgr28V+3Aw59N7LE5JcvwzclsXM6PMmzhuvQjxDC4txQAHlXU3gXo2YReQERpAXMKGzoR7xSNKCr6NjZVKRu1wiAime15vouRGxESOoonEu4xnvjGsmc0i4fsnQgWY6XC4bJSURciRvRKvVooYpWBMCpTBcGM5czgx6c5CGrJiT2Z4+hA/qChTDDj3Nxiiu+wEFCUaKGSHKUJgU04xLx8HwDSsGcX5QtLM/WO3SLyjgQKs+A3suB29mNOQg1L5CxN+5qckd2aqKHNEJ0brLYDkMhyyUmtwucp5JYXlrXkWYR13lTqOYUMx7GPIbo24/iUSp0jRgD4MwiyOgCjRvC02VmXU6CcZLjELY/6FlicbBxtbo6lF+G3DnAXRZQ9HyGkjnmbK19RKSuk51zfSnOUWLRvs1gGuT7Rj892pp957VwL/9gEJZYYRqvHvGHysiXaTJYV9GtTk+hg5Lphxg=,iv:DzPVM+jzmRNxywWHSAX6tNdWrGh62FvlmezjE6qEWNM=,tag:XRb2N+CvAVlXw4QgpipV6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMVY2YnVWVEtDcUt3ZnRU
            Rjh1VnowMzNVaEM1RllvV2hVSkRnRzNISUNBCm9TWUtDaVJieGhUYWUyanpxVWg4
            Rm5FZEVJYzNvUmYrTzlxeXQ5RWk3ZjQKLS0tIERUemZtQ3lJYlE0cWtHcGVpZCtI
            YmtKVVFqQ3UzcnFrQllsd1N6dWNaVEUKPXbwfOBzJBswmeBb47wM+CqoAMtuipxq
            dvdCpYNMepM87J59sZPN+tCgMNokSs17314RaXPExnXjt3yuri+csg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T11:16:13Z"
    mac: ENC[AES256_GCM,data:TFs7ka3fEFTA2vYHwQqGU5XuWmFu1caRSv+PxTBFBHYdvQnkX5DtzGVM3OCoBjEdSmkphpY63iOHAZrB6NeKZi0Cd63GTeD4ht477ffIqxTNm0SkFgEGX2CE2Lk6nWrO4MIXtaKBA7XAib2uLm2JQ2E/fnOXBb10AefdaRJ6pNs=,iv:eNwkIqU5pJf3Vizd2uaKOD5xUmf8E4tcCDKnyv08lMU=,tag:LqxwDQXpY1ylajLwFhF5TQ==,type:str]
    version: 3.13.3
