apiVersion: v1
kind: Secret
metadata:
    name: spotify-navidrome-sync
    namespace: media
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:BBWiQAxAkJZt12wB8A9c/QDjEXessTJKuX3QirV/B+Q=,iv:jmZJpgk6uEkbIQ2Ort9d86olFjs8irAN3RJEksvzVp4=,tag:dMOekAsz/hUafULz1dooaA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:kbriq0OE8bfMFlvmPXTDbzvzXAgxJWSSWuERWMyl3c4=,iv:ejBZyj3KKvOtkATp+pcGKooGLEkSx8V1/hOpmDdxddQ=,tag:T4Ks1LCVo6P9JNwBhECHMw==,type:str]
    SUBSONIC_API_USER: ENC[AES256_GCM,data:HkAY8Q==,iv:exxYOcCP6YijRji2SX6FN3wIMwJodEAzPJP2v8rYpHg=,tag:SS0FVjGbW5za8Caq5xMXJg==,type:str]
    SUBSONIC_API_PASS: ENC[AES256_GCM,data:qFVUiyUwJyHBrrFB0peGzVEZNGBdyVPrPpin8ThZUdM=,iv:mMy8daH3ScdO1IutSMI27XXERi2BxCy9OJ6bxDTx5Fg=,tag:VFo+8lpueEkJJUlCyj13gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZUtlcE94ditrSnN6b2NO
            Z0wzYVJYVlRXUDBVQWIzY1k2RXE1MU5zRUdjCjhSTmtpdlZ0WktNTHR3TzAwQ05o
            K2RDQzVKNXQremVreWNlR0tCbUVnVlEKLS0tIEZnK3JSQVdrNStDa3B2MFd4REx1
            SUhjOFVYaTF4cWRBWHg0c1hKak9PKzQKtDI1nLrgBj9dY/ZdftSKDDZyPItrR4MK
            f3xIUjosvoOxfrB6AyILLWCSfOUP7vaDcBJ+/zonUUPbq7Fe2zxUcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T08:31:38Z"
    mac: ENC[AES256_GCM,data:tPTNzOFCBV3RqxUN6WqwHFv0ROhXMxbFQEjL+qScwLB+Y2W1HYe9deIG88o9seZZ+E6wUEDU7ufm8h4xh2Wc5Nnxwz63ntdLWX513IpuuxGhmj2l6iuEcH6lVyc7BnlrfBF6uOhMCLNsFIZVSA6TuNXBPy1M/P8pSt9pf8c3vTE=,iv:JQ4cWrDWFxw+VCzCTieM+BThgksN56wxnIRn68ocSa0=,tag:AA2mdaTwtCcsfUksJVbtNg==,type:str]
    version: 3.13.3
