apiVersion: v1
kind: Secret
metadata:
    name: endurain-basic-auth
    namespace: endurain
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:GFrbBnSIOaw=,iv:N3L4TDrhvBKHMLGnIM5X9IG+3KcrEdnojHkKGH2YQDY=,tag:uruQ8noXHi0/IGD/3JWJ3w==,type:str]
    password: ENC[AES256_GCM,data:DECh6nGhrrhdEUrKxhsIN3/YWrns/RN+1UsHmcKzzziQlIFrOBMJM4plSb05sXZDS2llhQgtogamPRESSAwTvw==,iv:IFeqAPSHjfdvrimz5W40ILe/bFSf9qJdIN/RMKi/FpY=,tag:itUQwMwWKJrn99sIgmcC6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabG1wcFpNVG80d2F0c2Y2
            WFFIVm9LRmpvd28vYS9jM2NCdjI3WWsrb0JvCm1ORm5qbHN6WENNUDk2c0Zjb1ZD
            ZEVVQzJralhvNWs0dG05NVRuVGdSWGcKLS0tIG5SallQNGFDUHBOaXJSRWFRM0VG
            ejNuYU9Kck5aWEJpK2VGcUM5Y2xxVVEKtDb04R2C1KfiOgss90UXBfrL1ODGU+Yt
            TiCrsFYjQfS8T2Z9dw1pTwyiA78A2cKsCXk9beA9T54oKa/ufCijow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:QrtRYnf9q1ryX0Eztchl58JpTYbMdL7kpMNkwM31VHFZL3ZOc94/aXZeiyCX53DboQp1zc986HaxcbqxlgJ+he1h+/24qiF1isBpFfVULHZsqVQfegp8qmt36eVBNUzStoK6Jij0VpW7WQpDelOkc3p1kNI1EENhSOwppxItJN8=,iv:mPZ26t6PdxPkPWEzCucAGJANBlFTmFPjto2pTooVbXk=,tag:UabHRP6AsspfDuDabFVBeA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: endurain-postgres-v18
    namespace: endurain
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:rf3AQHjuwO2dMlXIwn5wuRlXPv9y0rgIsfA=,iv:2v4jneIHctww1h3DhsD6jJZcjoeRzxzdkCb59wBOaUY=,tag:Jbu1owdNmmg7HXYTFw14lA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:W1UbOtaip0P2zmqn3IO32BY1dCuiEaxa9z1EJRgEg45alLlTTKGTQiIXtOPnTTcJU/v6tpHut9sXT7zqJE76Ow==,iv:LJQU4EbN6fmb7xIGgWxD8ZGMRbPh4/L+WOUSbf8LG8U=,tag:AV5CAFWYVeP8l1nNzhDxGQ==,type:str]
    region: ENC[AES256_GCM,data:q2LoN/WG,iv:5TcSUMrxtUjuzkVXqoT8mdPiK5smpTkG1Mh5sgRQlEA=,tag:ObWGqQvB8cRQ71s4f+/vnw==,type:str]
    password: ENC[AES256_GCM,data:K9CLMldvg+n2e+Tq7BoX12AxxvjSiABnJ2vcsglHa6wlLyrKgY8MTqrBkdCFSL2JPo8gj0h4boNjY6mSiXOUlg==,iv:1J5YAnPSRjaQilfnJ7CZf4n/IKK4rVOxsquX3CnP2pY=,tag:f4mp+EtvJwIws9szR27RXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabG1wcFpNVG80d2F0c2Y2
            WFFIVm9LRmpvd28vYS9jM2NCdjI3WWsrb0JvCm1ORm5qbHN6WENNUDk2c0Zjb1ZD
            ZEVVQzJralhvNWs0dG05NVRuVGdSWGcKLS0tIG5SallQNGFDUHBOaXJSRWFRM0VG
            ejNuYU9Kck5aWEJpK2VGcUM5Y2xxVVEKtDb04R2C1KfiOgss90UXBfrL1ODGU+Yt
            TiCrsFYjQfS8T2Z9dw1pTwyiA78A2cKsCXk9beA9T54oKa/ufCijow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:52:29Z"
    mac: ENC[AES256_GCM,data:QrtRYnf9q1ryX0Eztchl58JpTYbMdL7kpMNkwM31VHFZL3ZOc94/aXZeiyCX53DboQp1zc986HaxcbqxlgJ+he1h+/24qiF1isBpFfVULHZsqVQfegp8qmt36eVBNUzStoK6Jij0VpW7WQpDelOkc3p1kNI1EENhSOwppxItJN8=,iv:mPZ26t6PdxPkPWEzCucAGJANBlFTmFPjto2pTooVbXk=,tag:UabHRP6AsspfDuDabFVBeA==,type:str]
    version: 3.13.3
