---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-softhsm
  namespace: openbao
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "${STORAGE_READWRITEONCE}"
  resources:
    requests:
      storage: 1Gi
