apiVersion: v1
kind: Secret
metadata:
    name: openbao-softhsm
    namespace: openbao
type: Opaque
stringData:
    softhsm-so-pin: ENC[AES256_GCM,data:pCJej1J0qZaPQXya0MMMFkLLQ1VUoCg2Eaex+SZCvjUwMmU3PtzhMf9A0ktZlY1t,iv:2HTa89xKWU5dYglpx6vKg5xu7+bZ1q2z5Zt5LnjFa94=,tag:eBiMocPioKHkusjMO/S1Ww==,type:str]
    softhsm-user-pin: ENC[AES256_GCM,data:2YdNBKLcInQCc0t5sHsNThiwM6naw5Ouoq/W28lvI/e4dnhkAiBtJ+Qq3ufW0K6A,iv:qJRcxfm2HG4uWz4D5GPdmw/9/KrVAv8pNgekZFXzwr4=,tag:ufHxY3b8xxagNzyHFyBaKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZmVrc1RaTVZkTmNPSVBy
            SDhMNHBNZ0cyYjBxWG1xV1NpWkdudjVUdGdvClVNdlEyQlFpOEh5amRrRHlsZ2Vu
            Q3RIWjFBVlFxOWFlSHBwemo2OFZRMmcKLS0tIG1rY1AwOHMyZWtSYlhIS0pMVTVm
            eHBjcWZHKzQ1eG9ibXVrS29iR2crVWMKzhDxNDVxnq1RucAkZOcaJ1VkI+uTLNQj
            kSR/HBKi/Yy+kQ7HBkMtC+XosVbSU2Hj0aNN9sQ3LGplupkPHCgqMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T21:43:05Z"
    mac: ENC[AES256_GCM,data:McD/6ARj2rN6ts55IxAcoORV1YMrcO0tw0Rl9xmskRZbOlmXtAvmlZHGFV9iKeqpY7ujFKlwlJZ7/DYrfwqsVx80iw61iAqHqq6S5k63YAYxKUze/ifIOyYGMwhDscnxR8mquM+wqPN6iv1+uierjORd9UIOIBMD0TpBjMFM2fM=,iv:VUWFJ1Do9d5ysbUtl09dqzYqP3mKjgCgopSFooQte0k=,tag:Z2X+qmLlYfY6No72c74bNA==,type:str]
    version: 3.13.1
