apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:f2ASWYI1pl858xk=,iv:h4zbpXOJec8n7L7wtn8/L+a6z1RlPUiiLgaAwJCbu5U=,tag:jybkcBILKHOp7KLeqs9/sA==,type:str]
    password: ENC[AES256_GCM,data:AT0OnMsckB7fHxMgu8way9494pGr78sq2BjfN/mqiscsMiekBwzdBsQbQ/5N0D6/A06jTULdcMtTJTY7kpz8wg==,iv:Zq9jCXi0Oac/pX9R75Tv5Nyh0mAxUVL8NRE4fonqOaA=,tag:r5VZTyt/IXzGMt3NFudgQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcWpvN21PMk1kWGJ0RnEy
            V2pHR01iZEcya1EyWG82NkFkSzRTTURuajF3CitZcHk1b2k5a0g2aTNxTkU0b2U4
            dDBuU3d1cUdZVTloRVI5aktrd1lGQWMKLS0tIGo4QU4yL3V4UkxqNGtINU5OUHhP
            ZDF6MVRWcW5DR3Q5WGN6aFMrV2ZIWU0KzTfZSipmI4B++iQGeLLWaWK1MPDRDemW
            M5APU17eMsUsNLfUoxmElqQoqR4PfpdrG4moUTxH+B9ZpOrr8gY0Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T09:22:03Z"
    mac: ENC[AES256_GCM,data:Ug9/Fw7gfz8rU7ZflQ55BvjYaUGP7u56ZmUGN9vyfCqZOdi5Y/em6m/T0ZMiXC7kkHMeY3Wu4X/jDb6NBi6zLNlU7CmShT4NI+uR27jyIKzmlQlpK6B2yGWmH1PkM2vknTWIOu9P/ZOZeyp70zIzVwuyGEntj0ubjrhWRqh3qwU=,iv:SWjPz1pqBtLnRaeYiwcsIq/AAd2y8trwWIYCg27Y3+k=,tag:VPRtulZ2bMIztP1tyVwsKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dispatcharr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:5tIqfHxlKAi8UpY9hpGeITkboYenB10YdVE=,iv:MVDKRAKuUy5Spaa6Hk5j8jkCbaw8R9/aWChhstmpJX8=,tag:oWf41IJMmZVMQr+LiNk+0Q==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:1FgFv3CI27wu6Jo8Jjzq25fnnWAUHy5Co6yY3P8sACVU20SLIjd6Q84X+BGo6LHMRPNjVOGaScmTEzVMt5eQ8w==,iv:pmyFl6rdA0a+VadrNrXvWTf/U6suyeygQzLPgm0g1Qk=,tag:mlZSvuFYBGmQKxSMluNAnA==,type:str]
    region: ENC[AES256_GCM,data:yfy5645O,iv:LtgN9Cz+MvcR/xCw6T3C60kFm067kRCcIMHqIMn33Vc=,tag:sEDP+KkOSqXTpDbIa3MH1g==,type:str]
    password: ENC[AES256_GCM,data:ndbH5V0sGLAPe7PXwFwOsLR5BhYIhSI6V0u19mY7+22Ygxugg9Ibzt8W043UAGK//PYxHNxH+vVf5mw1H0sCvA==,iv:QcPYYpnMao+rjE9Gxz8ZLlGiWbQW7d7R2TXVpg/HwAk=,tag:1F/BsC4kJMVsYUPgVYHRbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcWpvN21PMk1kWGJ0RnEy
            V2pHR01iZEcya1EyWG82NkFkSzRTTURuajF3CitZcHk1b2k5a0g2aTNxTkU0b2U4
            dDBuU3d1cUdZVTloRVI5aktrd1lGQWMKLS0tIGo4QU4yL3V4UkxqNGtINU5OUHhP
            ZDF6MVRWcW5DR3Q5WGN6aFMrV2ZIWU0KzTfZSipmI4B++iQGeLLWaWK1MPDRDemW
            M5APU17eMsUsNLfUoxmElqQoqR4PfpdrG4moUTxH+B9ZpOrr8gY0Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T09:22:03Z"
    mac: ENC[AES256_GCM,data:Ug9/Fw7gfz8rU7ZflQ55BvjYaUGP7u56ZmUGN9vyfCqZOdi5Y/em6m/T0ZMiXC7kkHMeY3Wu4X/jDb6NBi6zLNlU7CmShT4NI+uR27jyIKzmlQlpK6B2yGWmH1PkM2vknTWIOu9P/ZOZeyp70zIzVwuyGEntj0ubjrhWRqh3qwU=,iv:SWjPz1pqBtLnRaeYiwcsIq/AAd2y8trwWIYCg27Y3+k=,tag:VPRtulZ2bMIztP1tyVwsKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
