---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
  namespace: flux-system
spec:
  interval: 30m
  releaseName: ceph-csi-drivers
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ceph-csi-drivers
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-operator-charts
        namespace: flux-system
      interval: 30m
  targetNamespace: rook-ceph
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: rook-ceph
      namespace: flux-system
  values:
    operatorConfig:
      name: ceph-csi-operator-config
      namespace: rook-ceph
      driverSpecDefaults:
        imageSet:
          name: rook-csi-operator-image-set-configmap
        clusterName: "${CLUSTER_NAME}"
        controllerPlugin:
          hostNetwork: true
          replicas: 2
          deploymentStrategy:
            type: Recreate
          priorityClassName: system-cluster-critical
        nodePlugin:
          kubeletDirPath: /var/lib/kubelet
          priorityClassName: system-node-critical
    drivers:
      rbd:
        name: rook-ceph.rbd.csi.ceph.com
        enabled: true
        clusterName: "${CLUSTER_NAME}"
        imageSet:
          name: rook-csi-operator-image-set-configmap
        controllerPlugin:
          replicas: 2
          priorityClassName: system-cluster-critical
        nodePlugin:
          kubeletDirPath: /var/lib/kubelet
          priorityClassName: system-node-critical
      cephfs:
        name: rook-ceph.cephfs.csi.ceph.com
        enabled: true
        clusterName: "${CLUSTER_NAME}"
        imageSet:
          name: rook-csi-operator-image-set-configmap
        snapshotPolicy: volumeGroupSnapshot
        fsGroupPolicy: File
        kernelMountOptions:
          ms_mode: prefer-crc
        controllerPlugin:
          replicas: 2
          priorityClassName: system-cluster-critical
        nodePlugin:
          kubeletDirPath: /var/lib/kubelet
          priorityClassName: system-node-critical
      nfs:
        enabled: false
      nvmeof:
        enabled: false
