---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name threadfin
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  driftDetection:
    mode: enabled
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      threadfin:
        containers:
          threadfin:
            image:
              repository: docker.io/fyb3roptik/threadfin
              tag: 1.2.9@sha256:99c3556cf465b5c87f6648b232b7f9d84e34ff646719184f0490464bb522d160
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      threadfin:
        controller: *name
        ports:
          http:
            port: &port 34400
    ingress:
      threadfin:
        enabled: true
        annotations:
          haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
          haproxy.org/ssl-redirect-port: "443"
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "DENY"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        hosts:
          - host: &host "threadfin.${SECRET_DEFAULT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: threadfin
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: threadfin
        globalMounts:
          - path: /home/threadfin/conf
    networkpolicies:
      threadfin:
        enabled: true
        controller: *name
        policyTypes:
          - Egress
          - Ingress
        rules:
          egress:
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
                    except:
                      - "${HAPROXY_WHITELIST}"
              ports:
                - port: 80
                  protocol: TCP
                - port: 443
                  protocol: TCP
            - to:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/controller: ersatztv
                    app.kubernetes.io/instance: media-ersatztv
                    app.kubernetes.io/name: media-ersatztv
              ports:
                - port: 8409
            - to:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/controller: tunarr
                    app.kubernetes.io/instance: media-tunarr
                    app.kubernetes.io/name: media-tunarr
              ports:
                - port: 8000
          ingress:
            - from:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/controller: jellyfin
                      app.kubernetes.io/instance: media-jellyfin
                      app.kubernetes.io/name: media-jellyfin
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: haproxy-controller
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: kubernetes-ingress
              ports:
                - port: *port
